### ISSUE TITLE
Need preparation data to run velocyto: samtools version, bam file, repeat_msk.gtf

### ISSUE THREAD

**Issue by Suger0917** [velocyto-team/velocyto.py#112]
Dear velocyto team,
Our pipeline is not 10x,Smartseq2 or Drop-seq. So I don't know the format of prepared data. 
Please give us some examples including: samtools version, bam files, and repeat_msk.gtf dowloaded from UCSC.
When I run velocyto like this:
barcodes=/data1/zhangshu/code/velocity/barcode_96.tsv
output_path=`pwd`
repeat_msk_gtf=/data1/zhangshu/Database/STAR_hg38_genecode/hg38_repeats_repeatMasker.gtf
sorted_genome_bam=out.bam
gtf=/data1/zhangshu/Database/STAR_hg38_genecode/gencode.v28_ercc.gtf
velocyto run -b $barcodes -o $output_path -m $repeat_msk_gtf $sorted_genome_bam $gtf

I got erro like this:
sort: invalid option -- 'l'
sort: invalid option -- 't'
sort: invalid option -- 'O'
sort: invalid option -- '@'
open: No such file or directory
[bam_sort_core] fail to open file 7
/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecate
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/data1/zhangshu/software/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 196, in _run
    mask_ivls_by_chromstrand = exincounter.read_repeats(repmask)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/counter.py", line 345, in read_repeats
    gtf_lines = sorted(gtf_lines, key=sorting_key)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/counter.py", line 343, in sorting_key
    return (x[0], x[6] == "+", int(x[3]), entry)  # The last element of the touple corresponds to the `last resort comparison`
IndexError: list index out of range

I don't know if it is because the samtools version(Version: 0.1.18)  too old, or the gene_id of repeat_msk.gtf downloaded from UCSC is not corresponding to genome annotation (.gtf file) downloaded from GENCODE.
![image](https://user-images.githubusercontent.com/22163018/45411813-c672b500-b6a7-11e8-8dae-260ca6f352a4.png)
Please give some examples to run this pipeline.
Thank you!

**Comment by gioelelm** [comment]
Yes, I recognize the error there is a samtools version problem. Updating it should solve it.

**Comment by Suger0917** [comment]
I updated the samtools, but I still got erro:
/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/data1/zhangshu/software/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 196, in _run
    mask_ivls_by_chromstrand = exincounter.read_repeats(repmask)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/counter.py", line 345, in read_repeats
    gtf_lines = sorted(gtf_lines, key=sorting_key)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/counter.py", line 343, in sorting_key
    return (x[0], x[6] == "+", int(x[3]), entry)  # The last element of the touple corresponds to the `last resort comparison`
IndexError: list index out of range

**Comment by Suger0917** [comment]
I found the reason: the repeat_msk.gtf I used was downloaded from https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=611454127_NtvlaW6xBSIRYJEBI0iRDEWisITa&clade=mammal&org=Human&db=hg38&hgta_group=rep&hgta_track=rmsk&hgta_table=0&hgta_regionType=genome&position=chr1%3A11102837-11267747&hgta_outputType=gff&hgta_outFileName=hg38_repeats_repeatMasker_allTracks.gtf.
The group should select "All Tracks" but I selected "Repeats" which caused the erros.
