### ISSUE TITLE
Genome annotation downloaded from UCSC didn't work

### ISSUE THREAD

**Issue by Suger0917** [velocyto-team/velocyto.py#114]
Dear velocyto team,
I used genome annotation (.gtf file) downloaded from UCSC. The repeat annotation was also downloaded from UCSC:https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=611454127_NtvlaW6xBSIRYJEBI0iRDEWisITa&clade=mammal&org=&db=hg19&hgta_group=allTracks&hgta_track=rmsk&hgta_table=rmsk&hgta_regionType=genome&position=&hgta_outputType=gff&hgta_outFileName=hg38_repeats_repeatMasker_allTracks.gtf

And I got an error like this:
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
Traceback (most recent call last):
  File "/data1/zhangshu/software/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 212, in _run
    exincounter.mark_up_introns(bamfile=bamfile, multimap=multimap)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/counter.py", line 694, in mark_up_introns
    ii.mark_overlapping_ivls(r)
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/indexes.py", line 167, in mark_overlapping_ivls
    downstream_exon = feature.get_downstream_exon()
  File "/data1/zhangshu/software/anaconda3/lib/python3.6/site-packages/velocyto/feature.py", line 59, in get_downstream_exon
    return self.transcript_model.list_features[ix]
IndexError: list index out of range

And it stoped at this place:
2018-09-14 01:57:44,581 - INFO - Load the repeat masking annotation from /data1/zhangshu/Database/hg19/hg19_repeat_masker_allTracks.gtf
2018-09-14 01:57:44,582 - DEBUG - Reading /data1/zhangshu/Database/hg19/hg19_repeat_masker_allTracks.gtf, the file will be sorted in memory
2018-09-14 01:58:17,395 - DEBUG - Processed masked annotation .gtf and generated 4293307 intervals to mask!
2018-09-14 01:58:17,652 - INFO - Scan /data1/zhangshu/project/cuiyueli/raw_data/P8W3-1/out.bam to validate intron intervals
2018-09-14 01:58:19,195 - DEBUG - Reading /data1/zhangshu/project/cuiyueli/raw_data/P8W3-1/out.bam
2018-09-14 01:58:19,197 - DEBUG - Read first 0 million reads
2018-09-14 01:58:19,197 - DEBUG - Marking up chromosome 1

Both of the annotation files were downloaded from UCSC. I tried genome annotation(.gtf file) downloaded from GENECODE. There was no error appeared. Did you processed something to make genome annotation file from GENECODE match repeat annotation file from UCSC, which caused the error when using genome annotation file from UCSC. And I want to know how to solve it. Thank you!

**Comment by gioelelm** [comment]
When I opened the link you attach the format selected was gzip.

I think that if you download it in this way, despite the file will have the
extension gtf the actual format will be gzip. Make sure you are downloading
selecting plain text.

**Comment by gioelelm** [comment]
Also make sure that the aligner and velocyto are ruined using the same gtf
file.

**Comment by Suger0917** [comment]
I tried repeat_msk.gtf downloaded from UCSC by selecting plain text. It still got the same erro. But when I used the same bam file aligned to the UCSC genome fasta files but using genome annotation gtf file downloaded from genecode. It worked! 
I can't figure why genome annotation file downloaded from UCSC did not work?

> Also make sure that the aligner and velocyto are ruined using the same gtf file.

**Comment by Suger0917** [comment]
The error was solved by remove "exon_number" field of genome annotation file downloaded from UCSC.
https://github.com/velocyto-team/velocyto.py/issues/117
