### ISSUE TITLE
MemoryError when generating data table

### ISSUE THREAD

**Issue by tpentim** [velocyto-team/velocyto.py#115]
Hello,
I'm running velocyto (version  0.17.11) on Drop-seq data (human, 2'000 cells, 30'000 genes) in a 1.5T cluster with the following command:
`velocyto run og007_1_star_gene_exon_tagged_corrected.bam Homo_sapiens.GRCh38.84.chr.gtf -b og007_1_topBarcodes.tsv`
(I also provide the `cellsorted_og007_1_star_gene_exon_tagged_corrected.bam` in the same folder)

After a run time of 60h on this sample and 200h (!!) on another (it ended tonight :( ), I got twice the following MemoryError:

```
2018-09-08 03:31:40,661 - DEBUG - Counting for batch 268586, containing 17 cells and 17 reads
2018-09-08 03:31:40,816 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2018-09-08 03:31:40,817 - DEBUG - 0 reads were skipped because no apropiate cell or umi barcode was found
2018-09-08 03:31:40,817 - DEBUG - Counting done!
2018-09-08 03:31:59,173 - DEBUG - Generating output file og007_1_star_gene_exon_tagged_corrected_599QR.loom
2018-09-08 03:31:59,173 - DEBUG - Collecting row attributes
2018-09-08 03:31:59,358 - DEBUG - Generating data table

Traceback (most recent call last):
  File "/home/tpentim/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 274, in _run
    layers[layer_name] = np.concatenate(dict_list_arrays[layer_name], axis=1)
MemoryError
```

I would really appreciate your help in running this amazing tool!

P.s.
Do you have any tip on improving run time besides from masking repeated reads?

**Comment by gioelelm** [comment]
This runtimes are unreasonably long. I have never seen something like that
we are of 1-2 orders of magnitude off! Velocyto should be finished in 4h,
usually less.

How much ram does every process have access to? How fast is hd access, for
example how long does it take to loop through a whole bam file using pysam
(should be less than 15min)? Are you sure that using the top 2000 barcodes
only as barcodefilter file (if you have several tens of thousands thin
might be the problem) ?

Also could you attach the log output ?

**Comment by tpentim** [comment]
> How much ram does every process have access to?

up to 1.5 TB (there is no quota per process)


> How fast is hd access, for example how long does it take to loop through a whole bam file using pysam (should be less than 15min)?

`time samtools view cellsorted_og007_1_star_gene_exon_tagged_corrected.bam > /dev/null` says

```
real    8m57.382s
user    1m45.586s
sys     0m16.133s
```

It was generated using 

`samtools sort -l 0 -m 10G -n -@16 -O BAM -o cellsorted_og007_1_star_gene_exon_tagged_corrected.bam og007_1_star_gene_exon_tagged_corrected.bam`

To give you a feeling for the sizes:

```
-rw-r--r-- 1 tpentim tpentim_usr  17G  4. Sep 17:20 cellsorted_og007_1_star_gene_exon_tagged_corrected.bam
-rw-r--r-- 1 tpentim tpentim_usr 4,4G  4. Sep 11:47 og007_1_star_gene_exon_tagged_corrected.bam

```

> Are you sure that using the top 2000 barcodes only as barcodefilter file (if you have several tens of thousands thin might be the problem) ?

Could you tell me how to check that?
`og007_1_topBarcodes.tsv` has 2228 lines.

> Also could you attach the log output ?

Is there any log file generated? I did not capture the stderr stream in a file.

**Comment by gioelelm** [comment]
I see you are sorting by position and then you call the file cellsorted.
You need to sort by cellbarcode using the flag `-t CB`. If you don't have that in the bamfile you need to insert it as explained by the tutorial.

Otherwise, all the assumption of the pipeline are broken and velocyto will try to transverse the whole genome annotation thousands of time.

**Comment by tpentim** [comment]
Thank you Gioele,
you have been extremely helpful!
I will try and let you know if anaything strange comes up :)

**Comment by tpentim** [comment]
So...
I re-run the command:
`velocyto run Sample_files/og007_1/og007_1_star_gene_exon_tagged_corrected.bam Genome_files/Homo_sapiens.GRCh38.84.chr.gtf -b Sample_files/og007_1/og007_1_topBarcodes.tsv`

after generating the cellsorted file in this way:
`samtools sort -t CB -O BAM -o Sample_files/og007_1/cellsorted_og007_1_star_gene_exon_tagged_corrected.bam Sample_files/og007_1/og007_1_star_gene_exon_tagged_corrected.bam`

and it took just 2h to run :)

However... I still get the same MemoryError  :'(
```
2018-09-14 20:04:17,251 - DEBUG - Counting for batch 134923, containing 100 cells and 138 reads
2018-09-14 20:04:17,253 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2018-09-14 20:04:17,854 - DEBUG - Read first 50 million reads
2018-09-14 20:04:49,180 - DEBUG - Read first 60 million reads
2018-09-14 20:05:21,126 - DEBUG - Read first 70 million reads
2018-09-14 20:05:26,502 - DEBUG - Counting for batch 134924, containing 41 cells and 42 reads
2018-09-14 20:05:26,503 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2018-09-14 20:05:26,509 - DEBUG - 0 reads were skipped because no apropiate cell or umi barcode was found
2018-09-14 20:05:26,509 - DEBUG - Counting done!
2018-09-14 20:05:37,360 - DEBUG - Generating output file Sample_files/og007_1/velocyto/og007_1_star_gene_exon_tagged_corrected_FPBQI.loom
2018-09-14 20:05:37,360 - DEBUG - Collecting row attributes
2018-09-14 20:05:37,688 - DEBUG - Generating data table
Traceback (most recent call last):
  File "/home/tpentim/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/velocyto/commands/run.py", line 113, in run
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/home/tpentim/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 274, in _run
    layers[layer_name] = np.concatenate(dict_list_arrays[layer_name], axis=1)
MemoryError
```

**Comment by tpentim** [comment]
Thanks again, Giole!

I finally managed to generate the loom file :) the problem was as you pointed out in the .bam file. More in detail, it was solved by re-installing samtools and letting velocyto cellsort it :+1:

**Comment by denvercal1234GitHub** [comment]
@tpentim -- Would you mind explaining the code you used to sort the bam file below? 

What does "-O BAM" refer to?

```
samtools sort -t CB -O BAM -o Sample_files/og007_1/cellsorted_og007_1_star_gene_exon_tagged_corrected.bam Sample_files/og007_1/og007_1_star_gene_exon_tagged_corrected.bam
```

And, how did you determine the problems in the .bam file? 

I also kept getting Out-of-memory issue #320 , and trying to sort the bam manually first. Thank you so much!
