### ISSUE TITLE
.gtf flie showing errors while running velocyto run10x

### ISSUE THREAD

**Issue by sharpy013** [velocyto-team/velocyto.py#120]
I ran velocyto run10x -m repeat_msk.gtf try try/gencode.v28.annotation.gtf 
The output was:
Traceback (most recent call last):
  File "/home/sharpy/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/sharpy/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sharpy/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sharpy/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sharpy/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sharpy/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sharpy/anaconda3/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 83, in run10x
    os.path.normcase("outs/filtered_gene_bc_matrices/*/barcodes.tsv")))[0]
IndexError: list index out of range

**Comment by gioelelm** [comment]
As suggested also in other issue (please use the search command). This might be related with a older/newer version of cellranger. Please just use the `run` command
