### ISSUE TITLE
ERROR - This is an older version of cellranger, cannot check if the output are ready, make sure of this yourself

### ISSUE THREAD

**Issue by linwang6** [velocyto-team/velocyto.py#121]
Hi,
 
I 'm running the velocyto on 10X test data, which generated by CellRanger 1.3.1, and the velocyto gives the errors, but the higher version of CellRanger does not works for me, how to run velocyto using the output of the CellRanger 1.3.1 version? Thanks.

2018-09-21 01:17:04,769 - ERROR - This is an older version of cellranger, cannot check if the output are ready, make sure of this yourself
Traceback (most recent call last):
  File "/home/lxy/bin/Python-3.6.3/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto', 'console_scripts', 'velocyto')()
  File "/home/lxy/bin/Python-3.6.3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lxy/bin/Python-3.6.3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lxy/bin/Python-3.6.3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lxy/bin/Python-3.6.3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lxy/bin/Python-3.6.3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lxy/bin/velocyto.py/velocyto/commands/run10x.py", line 83, in run10x
    os.path.normcase("outs/filtered_gene_bc_matrices/*/barcodes.tsv")))[0]
IndexError: list index out of range

**Comment by gioelelm** [comment]
Hi,

You can use the `velocyto run` command making sure you pass the required paths.
`run` is the main command of velocyto and all the other run commands, like `run10x`, are just thin wrappers around `run`.

`run10x`, in particular looks for the input files in the folder structure of the 10x documents and does not allow to set options that do not make sense for the 10X platform.

**Comment by sharpy013** [comment]
I have the same error. Did you resolve it?

**Comment by gioelelm** [comment]
I am pretty sure that using `run` as described in the tutorial solves it.

**Comment by sharpy013** [comment]
But how do i download a bam file. Can you provide with bam and gtf files used to create loom file for velocyto notebooks?

**Comment by linwang6** [comment]
> I am pretty sure that using `run` as described in the tutorial solves it.

Thanks!

**Comment by visaxena2870** [comment]
Yes it works that way

**Comment by dandata123-tech** [comment]
but how can we get .bam file
