### ISSUE TITLE
ValueError: Attribute must have exactly x values but y were given

### ISSUE THREAD

**Issue by davetang** [velocyto-team/velocyto.py#122]
Hi there,

I ran:

```
velocyto run10x --samtools-threads 24 10x genes.gtf 2> error.log

cat error.log
[bam_sort_core] merging from 216 files and 24 in-memory blocks...
Traceback (most recent call last):
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/velocyto/commands/_run.py", line 286, in _run
    ds = loompy.create(filename=outfile, matrix=total, row_attrs=ra, col_attrs=ca, dtype="float32")
TypeError: create() got an unexpected keyword argument 'matrix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dtang/working_data_01/bin/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 106, in run10x
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/velocyto/commands/_run.py", line 297, in _run
    loompy.create(filename=outfile, layers=tmp_layers, row_attrs=ra, col_attrs=ca, file_attrs={"velocyto.__version__": vcy.__version__, "velocyto.logic": logic})
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/loompy/loompy.py", line 934, in create
    raise ve
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/loompy/loompy.py", line 929, in create
    ds.ca[key] = vals
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/loompy/attribute_manager.py", line 111, in __setitem__
    return self.__setattr__(name, val)
  File "/home/dtang/working_data_01/bin/lib/python3.6/site-packages/loompy/attribute_manager.py", line 132, in __setattr__
    raise ValueError(f"Attribute must have exactly {self.ds.shape[self.axis]} values but {len(values)} were given")
ValueError: Attribute must have exactly 3655 values but 3573 were given
```

I did overwrite `barcodes.tsv` in the `filtered_gene_bc_matrices` folder with my list of 3,655 barcodes. I'm currently running `velocyto run` but I'm guessing I'm going to see the same error.

Does velocyto perform any filtering? Any ideas on the error?

Many thanks,

Dave

**Comment by davetang** [comment]
I guessed wrong. I could generate a loom file with the barcodes I specified by using `velocyto run` instead of `velocyto run10x`.

```
velocyto run --bcfile bc.txt \
             --outputfolder velocyto \
             --samtools-threads 24 \
             possorted_genome_bam.bam \
             genes.gtf 2> error.log
```
