### ISSUE TITLE
Output generation error 

### ISSUE THREAD

**Issue by FrancesWong** [velocyto-team/velocyto.py#129]
Hi, 

It's my first time running velocyto and I'm running into a error when it's trying to generate the output. Error message pasted at the end. 

I checked the local directory and the OUTPUT folder is empty. Do you have any suggestions of how to resolve this problem? 

Thank you very much for you help!

Best, 
-Frances

2018-10-04 18:12:09,869 - DEBUG - Counting done!
2018-10-04 18:12:09,869 - DEBUG - Example of barcode: P11_unique.bam and cell_id: SS2_17_408_BAM/A10/A10_unique.bam:P11_unique.bam
2018-10-04 18:12:09,870 - DEBUG - Generating output file OUTPUT/SS2_17_408_BAM/A10/A10_unique.bam.loom
2018-10-04 18:12:09,870 - DEBUG - Collecting row attributes
2018-10-04 18:12:10,046 - DEBUG - Generating data table
2018-10-04 18:12:10,373 - DEBUG - Writing loom file
Traceback (most recent call last):
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/velocyto/commands/_run.py", line 286, in _run
    ds = loompy.create(filename=outfile, matrix=total, row_attrs=ra, col_attrs=ca, dtype="float32")
TypeError: create() got an unexpected keyword argument 'matrix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brian/anaconda3/envs/condaEnv/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/velocyto/commands/run_smartseq2.py", line 71, in run_smartseq2
    samtools_memory=1, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/velocyto/commands/_run.py", line 297, in _run
    loompy.create(filename=outfile, layers=tmp_layers, row_attrs=ra, col_attrs=ca, file_attrs={"velocyto.__version__": vcy.__version__, "velocyto.logic": logic})
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/loompy/loompy.py", line 1001, in create
    with new(filename, file_attrs=file_attrs) as ds:
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/loompy/loompy.py", line 930, in new
    f = h5py.File(name=filename, mode='w')
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/brian/anaconda3/envs/condaEnv/lib/python3.7/site-packages/h5py/_hl/files.py", line 148, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'OUTPUT/SS2_17_408_BAM/A10/A10_unique.bam.loom', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)

**Comment by gioelelm** [comment]
Can you please copy paste the command you are trying to run and give some info on the folder structure.

From the error message I can see that there is something wrong in the way you are running velocyto. Are you trying to run it on a single cell of the smartseq2 protocol, maybe?

**Comment by FrancesWong** [comment]
The command to initiate the run was: 

run-smartseq2 -o OUTPUT -e SS2_17_408_BAM/*/*unique.bam gencode.vM18.annotation.gtf

Yes, I'm running the smartseq2 protocol. (I noticed when following http://velocyto.org/velocyto.py/tutorial/cli.html#run-smartseq2-run-on-smartseq2-samples that the example said run_smartseq2 but I got the error "No such command "run_smartseq2" so I changed it to run-smartseq2)

I'm running this on Ubuntu, directories are on a RAID hard drive, one folder for the files for this project. 

Thank you very much for your troubleshooting! 

Best, 
-Frances

**Comment by gioelelm** [comment]
Ok the confusion comes from the help on the function that states `-e PATH` but the command -e actually takes just the name of the sample, it is opitonal, the bam instead are positional argument. The two are mixed and cause an unespected bug.

Do the following it will work:

`veloctyo run_smartseq2 -o OUTPUT -e SS2_17_408 SS2_17_408_BAM/*/*unique.bam gencode.vM18.annotation.gtf`

**Comment by FrancesWong** [comment]
Thank you, I'll give it a go and let you know what happens!

**Comment by FrancesWong** [comment]
Hi! 

Sorry for the delay, ran through perfectly and just pushed it through the rest of the pipeline for the beautiful plots. Thank you for the troubleshooting, and the great package! 

Best, 
-Frances
