### ISSUE TITLE
AttributeError: 'VelocytoLoom' object has no attribute 'colorandum'

### ISSUE THREAD

**Issue by EularTang** [velocyto-team/velocyto.py#132]
When I use the Analysis Pipeline, It always shows 'VelocytoLoom' object has no attribute 'colorandum'.Then I check the code 'analysis.py' and did not find the function 'colorandum'.Is this function really undefined? 

The following is the traceback:
```
vlm.plot_grid_arrows(quiver_scale=0.6,min_mass=24, angles='xy', scale_units='xy',headaxislength=2.75, headlength=5, headwidth=4.8, minlength=1.5,plot_random=True, scale_type="absolute")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/tangchen/anaconda3/lib/python3.7/site-packages/velocyto/analysis.py", line 2030, in plot_grid_arrows
scatter_dict = {"s": 20, "zorder": -1, "alpha": 0.2, "lw": 0,"c": self.colorandum}
AttributeError: 'VelocytoLoom' object has no attribute 'colorandum'

```

**Comment by EularTang** [comment]
I have resolved it ,thanks.
