### ISSUE TITLE
YFP reporter lacking exon_number

### ISSUE THREAD

**Issue by jayypaul** [velocyto-team/velocyto.py#145]
Hello,

I seem to have a problem with my genes.gtf input file; ther reporter_YFP is lacking the exon_number feature. Any ideas on how to circumvent the issue?

Below is a snippet of my command, and traceback/error.

Also note, I had to switch to run, instead of run10x, because my cellranger output file was likely an older version, which caused problems. 

Thanks.

sudo velocyto run -m mm10_rmsk.gtf e12_outs/possorted_genome_bam.bam genes.gtf 

    # ...

    # 2018-11-01 21:55:25,892 - DEBUG - Parsing Chromosome reporter_YFP strand + [line 1409510]
    # Traceback (most recent call last):
    #   File "/Users/cahanlab/anaconda3/envs/veloEnv/lib/python3.6/site-packages/velocyto/counter.py", line 519, in read_transcriptmodels
    #     exonno = regex_exonno.search(tags).group(1)
    # AttributeError: 'NoneType' object has no attribute 'group'
    # 
    # During handling of the above exception, another exception occurred:

    # ... 

    # File "/Users/cahanlab/anaconda3/envs/veloEnv/lib/python3.6/site-packages/velocyto/counter.py", line 522, in read_transcriptmodels
    # raise IOError("The genome annotation .gtf file provided does not contain exon_number. `exon_number` is described as a mandatory field by GENCODE gtf file specification and we rely on it for easier processing")

**Comment by cstrlln** [comment]
did you manage to circumvent the issue? facing the same

**Comment by jayypaul** [comment]
> did you manage to circumvent the issue? facing the same

Yeah, had to go into the gtf file & manually add in "exon_number" annotation for the extra genes that we had added into the file at the end.

**Comment by cstrlln** [comment]
thanks, just figured it also!

**Comment by Rui-Jing** [comment]
@jayypaul Hi, How do you know the exon number for added genes? Where can I get the information about added genes?(eg tdTomato). Thanks.

**Comment by ShobiStassen** [comment]
@jayypaul @cstrlln @Rui-Jing Hi, I'm facing exactly the same problem when running velocyto (.gtf file provided does not contain exon_number.)
Do you mind sharing how you managed to circumvent this issue? thanks !

**Comment by Cai-Costa** [comment]
You can open the .gtf file in notepad or sublime text for example, find your gene and write into your gene row a new section like this: " ; exon_number "Type the Number of exons here"; "

The whole row would look like something like this: 

GFP	unknown	exon	1	922	.	+	.	gene_id "GFP"; transcript_id "GFP"; exon_number "Replace_by_NUMBER_OF_EXONS";gene_name "GFP"; gene_biotype "protein_coding";

At least for me it worked, I hope that helps.

**Comment by kmcandre88** [comment]
This worked for me, although I am unsure how many exons my transgenes have (added Cre, eGFP and RFP to mine, it is a dual color reporter Rosa mTmG aka Tomato

Ran this before with no exon number and it worked but it has been a while, seems to be running ok so far. THANK YOU!
