### ISSUE TITLE
Issues with installing pysam (and velocyto) in windows

### ISSUE THREAD

**Issue by PattF** [velocyto-team/velocyto.py#161]
Hi velocyto team,

I'm trying to install velocyto but am running into a commonly described issue when attempting to first install pysam.
Currently running python 3.6.7 on conda 4.5.11 on windows 10.
I've followed the installation instructions and run all the required dependencies through conda (conda install numpy scipy cython numba matplotlib scikit-learn h5py click) but when trying to run 'pip install pysam' I run into the following error:
"Collecting pysam
  Using cached https://files.pythonhosted.org/packages/73/59/c319f1bde3019bbce4583cecb12b9e3e52ffcfbe2c96d8b1fb131c0d4fb7/pysam-0.15.1.tar.gz
    Complete output from command python setup.py egg_info:
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Patt\AppData\Local\Temp\pip-install-ynuifqik\pysam\setup.py", line 223, in <module>
        htslib_make_options = run_make_print_config()
      File "C:\Users\Patt\AppData\Local\Temp\pip-install-ynuifqik\pysam\setup.py", line 69, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "C:\Users\Patt\Anaconda3\lib\subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "C:\Users\Patt\Anaconda3\lib\subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\Patt\Anaconda3\lib\subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "C:\Users\Patt\Anaconda3\lib\subprocess.py", line 997, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Patt\AppData\Local\Temp\pip-install-ynuifqik\pysam\"

I've attempted to update gcc, setuptools and everything else I could find related to the issue but always run into the same pysam installation issue as shown above.

Would appreciate any help with getting this up and running.
Thanks!

**Comment by gioelelm** [comment]
I am afraid we don't support Windows, it might accidentally work but velocyto was never tested by us on a Windows OS. However,  this particular error might not be platform specific, it started to be reported recently even on macOs. It is probably related to an update in pysam and I am worried the only solution is downgrading pysam to 1.4 version but I don't have a recipee to fix this yet and I am trying to define one. Sent from my mobile - excuse the typos

**Comment by PattF** [comment]
Thanks for replying about the issue.
Bugger, that's a pity. If all else fails, would it possibly work if I installed Ubuntu virtual system in windows and installed from there?
Good luck with the fix!

**Comment by Acribbs** [comment]
Just as another comment, pysam is not tested on windows either, best option would be to use linux.
