### ISSUE TITLE
What is the schema of barcodes_<BAM_FILE>.bam.tsv file?

### ISSUE THREAD

**Issue by picrin** [velocyto-team/velocyto.py#162]
We've generated a BAM file from our DropSeq analysis following the instructions [here](http://velocyto.org/velocyto.py/tutorial/cli.html#running-velocyto), tweaking dropest parameters to fix any issues that came up on the way, as described [here](https://github.com/hms-dbmi/dropEst/pull/62).

The issue we are experiencing just now, and we can't fix, has to do with generating a file with the corrected barcodes, which in our case is named "barcodes_result.bam.tsv".

We attempt to generate the file using the command `velocyto tools dropest-bc-correct result.bam dropEst_out.rds`

The command finishes successfully, but the "barcodes_result.bam.tsv" has no content. The log produced is:

```
velocyto tools dropest-bc-correct result.bam dropEst_out.rds 
2018-12-11 06:24:44,795 - INFO - Loading `merge_targets` from /home/picrin/programming/cancer_velocyto/dropEst_out.rds using R / rpy2
2018-12-11 06:24:45,465 - INFO - Generating /home/picrin/programming/cancer_velocyto/barcodes_result.bam.tsv
2018-12-11 06:25:18,116 - INFO - Done
```

We would like to generate this file ourselves, but we would have to know what is the correct schema of such file. Could someone share this information?

**Comment by gioelelm** [comment]
Sorry for the problem. I thought that with the latest version of dropest that command is not needed anymore... The schema is the same as for 10X barcodes list file. It is just one barcode per line, barcodes should be the same  as they appear in the bam cellbarcode tag. (hint: you coukd try to have a look at the source of the command if you have doubts on what is going wrong)BestGioele-------- Original Message --------Subject: [velocyto-team/velocyto.py] What is the schema of barcodes_.bam.tsv file? (#162)From: picrin To: "velocyto-team/velocyto.py" CC: Subscribed We've generated a BAM file from our DropSeq analysis following the instructions here, tweaking dropest parameters to fix any issues that came up on the way, as described here.
The issue we are experiencing just now, and we can't fix, has to do with generating a file with the corrected barcodes, which in our case is named "barcodes_result.bam.tsv".
We attempt to generate the file using the command velocyto tools dropest-bc-correct result.bam dropEst_out.rds
The command finishes successfully, but the "barcodes_result.bam.tsv" has no content. The log produced is:
velocyto tools dropest-bc-correct result.bam dropEst_out.rds 
2018-12-11 06:24:44,795 - INFO - Loading `merge_targets` from /home/picrin/programming/cancer_velocyto/dropEst_out.rds using R / rpy2
2018-12-11 06:24:45,465 - INFO - Generating /home/picrin/programming/cancer_velocyto/barcodes_result.bam.tsv
2018-12-11 06:25:18,116 - INFO - Done

We would like to generate this file ourselves, but we would have to know what is the correct schema of such file. Could someone share this information?

**Comment by picrin** [comment]
Thank you @gioelelm. I'm still confused about the "barcodes_result.bam.tsv". We are using the latest version of dropest (downloaded from the github repository), and we generate our bam file with:

`-g <our-gtf-file>.gtf -o dropEst_out -L eiEIBA -c drop_seq_velocyto.xml <our-DropSeq-BAM-file>.bam`

According to your information, the resulting "<our-DropSeq-BAM-file>.tagged.bam" file should be directly usable by the `velocyto run-dropest`. However, when we try this, we get an error that "barcodes_result.bam.tsv" couldn't be found.

Maybe the `velocyto run-dropest` pipeline needs to be modified to accept input without enforcing the barcodes file?

For the immediate solution, does the barcode file need to contain a set of unique barcodes, or a list of barcodes corresponding to reads from the BAM file?

**Comment by picrin** [comment]
I assumed a set of unique barcodes, and was able to get past the error regarding the tsv file.

However, a new error now appears, which is due to argument parsing. Running `velocyto run-dropest correct_result.bam yang38.gtf` gives:

```
2018-12-11 08:00:05,221 - INFO - Attempting to find automatically the valid barcode list file /home/picrin/programming/cancer_velocyto/barcodes_correct.tsv
2018-12-11 08:00:05,221 - INFO - /home/picrin/programming/cancer_velocyto/barcodes_correct.tsv found 
Traceback (most recent call last):
  File "/home/picrin/programming/Ruibin_scNGS/venv/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/picrin/programming/Ruibin_scNGS/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/picrin/programming/Ruibin_scNGS/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/picrin/programming/Ruibin_scNGS/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/picrin/programming/Ruibin_scNGS/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/picrin/programming/Ruibin_scNGS/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/picrin/programming/Ruibin_scNGS/venv/lib/python3.6/site-packages/velocyto/commands/run_dropest.py", line 104, in run_dropest
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/home/picrin/programming/Ruibin_scNGS/venv/lib/python3.6/site-packages/velocyto/commands/_run.py", line 54, in _run
    raise IOError(f"Something went wrong in the argument parsing. You passed as bamfile: {bamfile}")
OSError: Something went wrong in the argument parsing. You passed as bamfile: /home/picrin/programming/cancer_velocyto/correct_result.bam
```

Is there a known fix for the problem?

**Comment by gioelelm** [comment]
I can't spot the problem without a deeper check. Maybe somebody from @pkharchenko can spot the problem.

My suggestion for now is just using the normal run command.

**Comment by picrin** [comment]
It turns out the problem manifests itself in line 49 in _run.py

https://github.com/velocyto-team/velocyto.py/blob/20eee627e78b62444c2656e041668f48ac49dcb8/velocyto/commands/_run.py#L49

Due to a suspected bug earlier in the pipeline the variable `bamfile` is of type string as opposed to of type tuple. A hotfix is to comment out all the lines 49 -- 54 and replace them with

```
bamfile = [bamfile]
multi = False
```

**Comment by picrin** [comment]
However, there are further issues in the pipeline, in line 233:
```
FileNotFoundError: [Errno 2] could not open alignment file `/home/picrin/programming/cancer_velocyto/cellsorted_correct_result.bam`: No such file or directory
```

**Comment by picrin** [comment]
The problem was with samtools version, the samtools version I used did not support the `-t` switch.
