### ISSUE TITLE
Error running pip install on mac: Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by kristens17** [velocyto-team/velocyto.py#171]
Hi guys,

I am trying to install velocyto on mac 10.13.6. I have tried everything I can find on here but nothing has worked yet. 

I get the following error message

(base) Kristens-MBP:~ Kristen$ pip install velocyto
Collecting velocyto
  Using cached https://files.pythonhosted.org/packages/20/93/a3225b29f9631c14c1c5b82e5efc115c72af9307aaea5547cd92d39cae9d/velocyto-0.17.16.tar.gz
Requirement already satisfied: numpy in ./anaconda3/lib/python3.6/site-packages (from velocyto) (1.15.4)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.6/site-packages (from velocyto) (1.2.0)
Requirement already satisfied: cython in ./anaconda3/lib/python3.6/site-packages (from velocyto) (0.29.2)
Requirement already satisfied: numba in ./anaconda3/lib/python3.6/site-packages (from velocyto) (0.42.0)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.6/site-packages (from velocyto) (3.0.2)
Requirement already satisfied: scikit-learn in ./anaconda3/lib/python3.6/site-packages (from velocyto) (0.20.2)
Requirement already satisfied: h5py in ./anaconda3/lib/python3.6/site-packages (from velocyto) (2.9.0)
Collecting loompy (from velocyto)
  Using cached https://files.pythonhosted.org/packages/62/8d/60bdbdc1cd09e751a171b8c1b54744c053d6193a17ffec75494fe9d60d17/loompy-2.0.16.tar.gz
Collecting pysam (from velocyto)
  Using cached https://files.pythonhosted.org/packages/15/f6/ce0611aaa1865a616f7dc164fbf046eaf38f2b17c6d404403c56250beb93/pysam-0.15.2.tar.gz
    Complete output from command python setup.py egg_info:
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/pz/rtjbpsns4k52vbw534jfk71r0000gq/T/pip-install-7bfcq2ty/pysam/htslib':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/pz/rtjbpsns4k52vbw534jfk71r0000gq/T/pip-install-7bfcq2ty/pysam/htslib':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pz/rtjbpsns4k52vbw534jfk71r0000gq/T/pip-install-7bfcq2ty/pysam/setup.py", line 223, in <module>
        htslib_make_options = run_make_print_config()
      File "/private/var/folders/pz/rtjbpsns4k52vbw534jfk71r0000gq/T/pip-install-7bfcq2ty/pysam/setup.py", line 69, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "/Users/Kristen/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/Users/Kristen/anaconda3/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/pz/rtjbpsns4k52vbw534jfk71r0000gq/T/pip-install-7bfcq2ty/pysam/

Please help

**Comment by gioelelm** [comment]
Have you searched other solved issues here? This is similar to a couple already encountered and solved problems.
You have a compiler problem.
Just to cover all the possible flavours of this problem do:

conda install gcc libgcc llvm cython

Even if probably "conda install gcc" alone would do.

**Comment by kristens17** [comment]
@gioelelm yes I've searched around but nothing I've seen yet has worked. 
I tried the above but still get the same error
other ideas?

**Comment by gioelelm** [comment]
MAybe the problem then is pysam. I think a similar problem was also reported there but I was not able to reproduce it when I recently did a fresh install of anaconda (py3.7 version), followed the instructions and install velocyto. It all just worked. Would you like to try that? You could also try to check first whether pysam is available using conda and through the bioconda channel, maybe you solve the problem that way. Another suggestion is to make sure you are in the conda root env not in a secondary environment, sometimes I had trouble with compilation on secondary conda envs

**Comment by brianpenghe** [comment]
Have you tried this?
`conda install python=3.7`
`source activate python3.7`
`conda install numpy scipy cython numba matplotlib scikit-learn h5py click`
`conda install gcc`
`pip install -e .`

**Comment by armenwould** [comment]
I have tried this, but no luck still.

> Have you tried this?
> `conda install python=3.7`
> `source activate python3.7`
> `conda install numpy scipy cython numba matplotlib scikit-learn h5py click`
> `conda install gcc`
> `pip install -e .`

**Comment by mxposed** [comment]
@armenwould What is the error you're getting?
I successfully installed velocyto on mac on 10.13.6 with and without conda, and can probably help.
With conda you need couple of extra packages:
`conda install clang llvm`
