### ISSUE TITLE
SyntaxError: invalid syntax after successfully installing velocyto

### ISSUE THREAD

**Issue by sharvari14** [velocyto-team/velocyto.py#176]
Hi,

I have velocyto successfully installed, however I am getting an error testing it:

Collecting velocyto
Installing collected packages: velocyto
  Found existing installation: velocyto 0.17.16
    Uninstalling velocyto-0.17.16:
      Successfully uninstalled velocyto-0.17.16
Successfully installed velocyto-0.17.17
Successfully installed velocyto-0.17.17

velocyto --help
Traceback (most recent call last):
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/bin/velocyto", line 6, in <module>
    from velocyto.commands.velocyto import cli
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/velocyto/__init__.py", line 12, in <module>
    from .neighbors import BalancedKNN, convolve_by_sparse_weights
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/velocyto/neighbors.py", line 3, in <module>
    from sklearn.neighbors import kneighbors_graph, NearestNeighbors
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 14, in <module>
    from . import _joblib
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/utils/_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/__init__.py", line 6, in <module>
    from ._base import Executor, Future
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/_base.py", line 22, in <module>
    from concurrent.futures import wait, as_completed
  File "/boston_bioinfo/bifx/app/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/boston_bioinfo/bifx/app/dx-toolkit/share/dnanexus/lib/python2.7/site-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax

Can you please help.

Thanks
Sharvari

**Comment by sharvari14** [comment]
I've installed in a conda environment, and following the issue in the link below:
https://github.com/velocyto-team/velocyto.py/issues/53

(python3.6.env): velocyto --help
ImportError: /home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/numba/typeconv/../../../../libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/numba/typeconv/_typeconv.cpython-36m-x86_64-linux-gnu.so)

**Comment by gioelelm** [comment]
You were looking at the right solved issue for your problem. conda install libgcc cythonshould have been the solution... I guess you tried it already, isn't it? Sent from my mobile - excuse the typos

**Comment by sharvari14** [comment]
Thank you so much for the reply. 
Yes, I've tried running the command below:
conda install libgcc cython

And, used the source installation (tried both C_COMPLIE = True and False) in my conda env, however I still get the same error:

velocyto --help
Traceback (most recent call last):
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto', 'console_scripts', 'velocyto')()
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/velocyto/__init__.py", line 12, in <module>
    from .neighbors import BalancedKNN, convolve_by_sparse_weights
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/velocyto/neighbors.py", line 3, in <module>
    from sklearn.neighbors import kneighbors_graph, NearestNeighbors
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 14, in <module>
    from . import _joblib
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/utils/_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/__init__.py", line 6, in <module>
    from ._base import Executor, Future
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/_base.py", line 22, in <module>
    from concurrent.futures import wait, as_completed
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/NextCODE.local/sgujja/.conda/envs/python3.6.env/lib/python3.6/site-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax

Can you please let me know if I missed anything.
Thanks for helping.

**Comment by gioelelm** [comment]
The error shows without a doubt that there is some problem in your environment.
The line:
```
raise type(self._exception), self._exception, self._traceback
```
contains a python 2.7 syntax incompatible with python 3.6.  Meaning somehow that your environment is mixing python 2.7 source code with python 3.6 source code.
I am not sure where the problem is but you should easily solve it by using a clean install of anaconda.

Best

**Comment by sharvari14** [comment]
I did a clean installation of anaconda3 and created a virtual environment to install the required packages/modules, however, I get this error

```
velocyto
Traceback (most recent call last):
  File "/home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/bin/velocyto", line 6, in <module>
    from velocyto.commands.velocyto import cli
  File "/home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/velocyto/__init__.py", line 12, in <module>
    from .neighbors import BalancedKNN, convolve_by_sparse_weights
  File "/home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/velocyto/neighbors.py", line 2, in <module>
    from numba import jit
  File "/home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/numba/__init__.py", line 14, in <module>
    from .special import typeof, prange, pndindex, gdb, gdb_breakpoint, gdb_init
  File "/home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/numba/special.py", line 3, in <module>
    from .typing.typeof import typeof
  File "/home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/numba/typing/__init__.py", line 2, in <module>
    from .context import BaseContext, Context
  File "/home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/numba/typing/context.py", line 11, in <module>
    from numba.typeconv import Conversion, rules
  File "/home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/numba/typeconv/rules.py", line 3, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "/home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/numba/typeconv/typeconv.py", line 3, in <module>
    from . import _typeconv, castgraph, Conversion

ImportError: /home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/numba/typeconv/../../../../libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env/lib/python3.7/site-packages/numba/typeconv/_typeconv.cpython-37m-x86_64-linux-gnu.so)

 $ strings ~/anaconda3/envs/velocyto_env/lib/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1

conda info

     active environment : velocyto_env
    active env location : /home/NextCODE.local/sgujja/anaconda3/envs/velocyto_env
            shell level : 1
       user config file : /home/NextCODE.local/sgujja/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /home/NextCODE.local/sgujja/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/NextCODE.local/sgujja/anaconda3/pkgs
                          /home/NextCODE.local/sgujja/.conda/pkgs
       envs directories : /home/NextCODE.local/sgujja/anaconda3/envs
                          /home/NextCODE.local/sgujja/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/3.10.0-862.11.6.el7.x86_64 rhel/7.5 glibc/2.17
                UID:GID : 223601536:223601536
             netrc file : None
           offline mode : False
```


Can you please let me know if I am missing something.

Thanks

**Comment by sharvari14** [comment]
Hi Gioele,

Can you please let me know if there's anything else to install or load to
make velocyto run?

It's not clear to me how to fix this error. Can you please help.

Thanks
Sharvari

**Comment by gioelelm** [comment]
What I was suggesting is to wipe out the current anaconda installation and install a fresh one from scratch and follow the installation instructions in the tutorial. Sent from my mobile - excuse the typos
