### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group', (gif file about Macaca)

### ISSUE THREAD

**Issue by ogujessica** [velocyto-team/velocyto.py#181]
Hi, Velocyto team!

I love velocyto, so I often use it with my mouse scRNAseq data etc.

This time, I need to analyze scRNAseq data about Macaca.
My collaborators ran Cellranger using their own gtf.file(macFas5_annot_wo_pseudo_v2a_chrx_filtered.gtf) .

Using their datas from Cellranger and gtf file, I attempted to run velocyto, but it failed as follows.
akiko@d405:~/DATA/Sasaki/E40F_Real$ velocyto run10x /home/akiko/DATA/Sasaki/E40F_Real/MS149_mf5v3_B6_20180615 /home/akiko/DATA/Sasaki/E40F_Real/macFas5_annot_wo_pseudo_v2a_chrx_filtered.gtf

/home/akiko/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-03-07 20:55:40,863 - DEBUG - Using logic: Default
2019-03-07 20:55:40,890 - INFO - Read 3907 cell barcodes from /home/akiko/DATA/Sasaki/E40F_Real/MS149_mf5v3_B6_20180615/outs/filtered_gene_bc_matrices/macFas5_v3/barcodes.tsv
2019-03-07 20:55:40,890 - DEBUG - Example of barcode: AAACCTGAGACAATAC and cell_id: MS149_mf5v3_B6_20180615:AAACCTGAGACAATAC-1
2019-03-07 20:55:40,912 - DEBUG - Peeking into /home/akiko/DATA/Sasaki/E40F_Real/MS149_mf5v3_B6_20180615/outs/possorted_genome_bam.bam
2019-03-07 20:55:41,299 - WARNING - Not found cell and umi barcode in entry 14 of the bam file
2019-03-07 20:55:41,300 - WARNING - Not found cell and umi barcode in entry 15 of the bam file
2019-03-07 20:55:41,300 - WARNING - Not found cell and umi barcode in entry 23 of the bam file
2019-03-07 20:55:41,300 - WARNING - Not found cell and umi barcode in entry 79 of the bam file
2019-03-07 20:55:41,301 - WARNING - Not found cell and umi barcode in entry 252 of the bam file
2019-03-07 20:55:41,427 - WARNING - Not found cell and umi barcode in entry 692 of the bam file
2019-03-07 20:55:41,439 - WARNING - The file /home/akiko/DATA/Sasaki/E40F_Real/MS149_mf5v3_B6_20180615/outs/cellsorted_possorted_genome_bam.bam already exists. The sorting step will be skipped and the existing file will be used.
2019-03-07 20:55:41,439 - INFO - Load the annotation from /home/akiko/DATA/Sasaki/E40F_Real/macFas5_annot_wo_pseudo_v2a_chrx_filtered.gtf
2019-03-07 20:55:43,085 - WARNING - The entry exon_number was not present in the gtf file. It will be infferred from the position.
2019-03-07 20:55:50,213 - DEBUG - Parsing Chromosome 1 strand - [line 0]
2019-03-07 20:55:50,760 - DEBUG - Done with 1- [line 46194]
2019-03-07 20:55:50,760 - DEBUG - Assigning indexes to genes
2019-03-07 20:55:50,768 - DEBUG - Seen 1276 genes until now
2019-03-07 20:55:50,768 - DEBUG - Parsing Chromosome 1 strand + [line 46195]
2019-03-07 20:55:51,490 - DEBUG - Done with 1+ [line 96817]
2019-03-07 20:55:51,490 - DEBUG - Assigning indexes to genes
2019-03-07 20:55:51,498 - DEBUG - Seen 2546 genes until now
2019-03-07 20:55:51,498 - DEBUG - Parsing Chromosome 10 strand - [line 96818]
2019-03-07 20:55:51,849 - DEBUG - Done with 10- [line 115248]
2019-03-07 20:55:51,849 - DEBUG - Assigning indexes to genes
2019-03-07 20:55:51,852 - DEBUG - Seen 3170 genes until now
2019-03-07 20:55:51,852 - DEBUG - Parsing Chromosome 10 strand + [line 115249]
2019-03-07 20:55:52,090 - DEBUG - Done with 10+ [line 134883]
2019-03-07 20:55:52,091 - DEBUG - Assigning indexes to genes
2019-03-07 20:55:52,094 - DEBUG - Seen 3835 genes until now
2019-03-07 20:55:52,094 - DEBUG - Parsing Chromosome 11 strand - [line 134884]
2019-03-07 20:55:52,587 - DEBUG - Done with 11- [line 163814]
2019-03-07 20:55:52,587 - DEBUG - Assigning indexes to genes
2019-03-07 20:55:52,591 - DEBUG - Seen 4520 genes until now
2019-03-07 20:55:52,592 - DEBUG - Parsing Chromosome 11 strand + [line 163815]
2019-03-07 20:55:52,906 - DEBUG - Done with 11+ [line 189366]
2019-03-07 20:55:52,906 - DEBUG - Assigning indexes to genes
2019-03-07 20:55:52,910 - DEBUG - Seen 5251 genes until now
2019-03-07 20:55:52,910 - DEBUG - Parsing Chromosome 12 strand - [line 189367]
Traceback (most recent call last):
  File "/home/akiko/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/akiko/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/akiko/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/akiko/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/akiko/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/akiko/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/akiko/anaconda3/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 106, in run10x
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/home/akiko/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 186, in _run
    annotations_by_chrm_strand = exincounter.read_transcriptmodels(gtffile)
  File "/home/akiko/anaconda3/lib/python3.6/site-packages/velocyto/counter.py", line 512, in read_transcriptmodels
    geneid = regex_geneid.search(tags).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Is it gtf file problem？
Gtf file used this time is as follow,

akiko@d405:~/DATA/Sasaki/E40F_Real$ head *.gtf
chr1	Gnomon	exon	43401	45943	.	-	.	transcript_id "rna2"; gene_id "gene1"; gene_name "PGBD2";
chr1	Gnomon	exon	48672	48735	.	-	.	transcript_id "rna2"; gene_id "gene1"; gene_name "PGBD2";
chr1	Gnomon	exon	53456	53477	.	-	.	transcript_id "rna2"; gene_id "gene1"; gene_name "PGBD2";
chr1	Gnomon	CiS	44182	45943	.	-	1	transcript_id "rna2"; gene_id "gene1"; gene_name "PGBD2";
chr1	Gnomon	CiS	48672	48688	.	-	0	transcript_id "rna2"; gene_id "gene1"; gene_name "PGBD2";
chr1	Gnomon	exon	43401	45266	.	-	.	transcript_id "rna1"; gene_id "gene1"; gene_name "PGBD2";
chr1	Gnomon	exon	48672	48735	.	-	.	transcript_id "rna1"; gene_id "gene1"; gene_name "PGBD2";
chr1	Gnomon	exon	61854	63279	.	-	.	transcript_id "rna1"; gene_id "gene1"; gene_name "PGBD2";
chr1	Gnomon	CiS	44182	45207	.	-	0	transcript_id "rna1"; gene_id "gene1"; gene_name "PGBD2";
chr1	Gnomon	exon	43401	45943	.	-	.	transcript_id "rna0"; gene_id "gene1"; gene_name "PGBD2";

I would greatly appreciate it if you could let me know how I solve this error.

Best regards,
Akiko　Oguchi

P.S. Thank you for good lectures in KI course last year!

**Comment by kokitsuyuzaki** [comment]
https://github.com/velocyto-team/velocyto.py/issues/328#issuecomment-1268016084
