### ISSUE TITLE
Issues running velocyto

### ISSUE THREAD

**Issue by roofya** [velocyto-team/velocyto.py#192]
Hi,
I am trying to run velocyto using  run10x command. I'm running on cluster by requesting 60 GB memory. Do I need more memory for that? Thank you so much for your help.

initial position.
2019-04-29 20:09:26,261 - DEBUG - 2745314 reads were skipped because no apropiate cell or umi barcode was found
2019-04-29 20:09:26,262 - INFO - Now just waiting that the bam sorting process terminates
Traceback (most recent call last):
  File "/home/mrr2006/.conda/envs/velocyto/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/mrr2006/.conda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/mrr2006/.conda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/mrr2006/.conda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mrr2006/.conda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mrr2006/.conda/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mrr2006/.conda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 115, in run10x
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/home/mrr2006/.conda/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/_run.py", line 225, in _run
    Otherwise sort manually by samtools ``sort -l [compression] -m [mb_to_use]M -t [tagname] -O BAM -@ [threads_to_use] -o cellsorted_[bamfile] [bamfile]``")
MemoryError: bam file #0 could not be sorted by cells.
                This is probably related to an old version of samtools, please install samtools >= 1.6.                In alternative this could be a memory error, try to set the --samtools_memory option to a value compatible with your system.                 Otherwise sort manually by samtools ``sort -l [compression] -m [mb_to_use]M -t [tagname] -O BAM -@ [threads_to_use] -o cellsorted_[bamfile] [bamfile]``

**Comment by saeedfc** [comment]
Had same problem. Solved this way.
Ran samtools first to get the cellsorted_possorted.genome_bam.bam file. And then ran velocyto.
In the velocyto documentation, it says "If the file cellsorted_[ORIGINALBAMNAME] exists, the sorting procedure will be skipped and the file present will be used."

```
(base) u0119129@gbw-d-l0099:~$ samtools sort -t CB -O BAM -o/mnt/DATA2/RAW_DATA/Re_Run_\ 2018_Data_with_updated_reference_genome/KUL-1-1000cells/outs/cellsorted_possorted_genome_bam.bam /mnt/DATA2/RAW_DATA/Re_Run_\ 2018_Data_with_updated_reference_genome/KUL-1-1000cells/outs/possorted_genome_bam.bam

(base) u0119129@gbw-d-l0099:~$ velocyto run10x -m /mnt/DATA1/Velocyto/alltracks_mask.gtf /mnt/DATA2/RAW_DATA/Re_Run_\ 2018_Data_with_updated_reference_genome/KUL-1-1000cells /mnt/DATA1/Velocyto/refdata-cellranger-mm10-3.0.0/genes/genes.gtf
```

Hope it helps

**Comment by kaizen89** [comment]
@saeedfc I tried your suggestion but did not change the result. Still have the samtools error message above. Also, velocyto does not seem to skip the sorting.
```
velocyto, version 0.17.16
2020-02-04 11:44:58,389 - INFO - No SAMPLEID specified, the sample will be called cellsorted_possorted_genome_bam714T_Q7O0H (last 5 digits are a random-id to avoid overwriting some other file by mistake)
2020-02-04 11:44:58,389 - DEBUG - Using logic: Default
2020-02-04 11:44:58,389 - DEBUG - Cell barcodes will be determined while reading the .bam file
2020-02-04 11:44:58,395 - DEBUG - Peeking into /home/abbas/Desktop/lab/bioinfo/projects/lung/Velocyto/714T/cellsorted_possorted_genome_bam714T.bam
2020-02-04 11:44:58,396 - WARNING - Not found cell and umi barcode in entry 81 of the bam file
2020-02-04 11:44:58,396 - WARNING - Not found cell and umi barcode in entry 418 of the bam file
2020-02-04 11:44:58,396 - WARNING - Not found cell and umi barcode in entry 419 of the bam file
2020-02-04 11:44:58,402 - INFO - Starting the sorting process of /home/abbas/Desktop/lab/bioinfo/projects/lung/Velocyto/714T/cellsorted_possorted_genome_bam714T.bam the output will be at: /home/abbas/Desktop/lab/bioinfo/projects/lung/Velocyto/714T/cellsorted_cellsorted_possorted_genome_bam714T.bam
2020-02-04 11:44:58,402 - INFO - Command being run is: samtools sort -l 7 -m 1840M -t CB -O BAM -@ 16 -o /home/abbas/Desktop/lab/bioinfo/projects/lung/Velocyto/714T/cellsorted_cellsorted_possorted_genome_bam714T.bam /home/abbas/Desktop/lab/bioinfo/projects/lung/Velocyto/714T/cellsorted_possorted_genome_bam714T.bam
2020-02-04 11:44:58,402 - INFO - While the bam sorting happens do other things...
```
As you can see velocyto still tries to repeat te sorting or maybe be its just a default message.
Any suggestions?

**Comment by SiyiWanggou** [comment]
I meet the same error.
I am just wondering what's the meaning of "-t CB" in samtools sort here?
Could you show me about this? 
Thanks,

**Comment by SiyiWanggou** [comment]
Does CB meanings "Cell Barcodes" here?

**Comment by kaizen89** [comment]
As I understand, CB is a tag in the bam file whichi contains the barcodes.If you want to sort by cell barcodes then you should set -t CB. Do not put the path to cell bacodes file here.

**Comment by SiyiWanggou** [comment]
@kaizen89 Thanks. I get some information from 10X genomics website. It discibes CB as "Chromium cellular barcode sequence that is error-corrected and confirmed against a list of known-good barcode sequences". I think you are correct.

**Comment by grimwoo** [comment]
@saeedfc Thanks for your solution.
I didn't really understand your code, hence failed to perform the "samtools". 

My failed velocyto code is :
```
velocyto run10x /public-dss/share/WQF_lab/ZYH/E14-R2-Result /public-supool/home/wuhaoda/Cell_Ranger/opt/refdata-cellranger-mm10-3.0.0/genes/genes.gtf
```

And the "samtools" code imitating yours (but failed) :
```
samtools sort -t CB -O BAM -o/public-dss/share/WQF_lab/ZYH/E14-R2-Result/outs\
/public-dss/share/WQF_lab/ZYH/E14-R2-Result/outs/cellsorted_possorted_genome_bam.bam /public-dss/share/WQF_lab/ZYH/E14-R2-Result/outs\
/public-dss/share/WQF_lab/ZYH/E14-R2-Result/outs/possorted_genome_bam.bam
```
Could you help me correct my samtools code?

**Comment by arjun0502** [comment]
@kaizen89 I created the cellsorted_possorted_genome_bam.bam. Can I just do 'velocity run' and not 'velocity run 10x' with this file? If so, how do I do it? I tried 
velocyto run -b barcodes.tsv -o ./velocyto_mcf10a_results -m repeat_msk.gtf cellsorted_possorted_genome_bam.bam hg38_ens94.chr.gtf and it did not work

**Comment by denvercal1234GitHub** [comment]
@saeedfc -- When you manually sort your bam first, did you then need to use the original bam.bai (index) file that came with the cellranger count? Or, did you have to index your cellsorted_possorted...bam file? If so, how did you index it? 

```
# like this? or any options?
samtools index sample.sorted.bam
```

**Comment by creixellmarc** [comment]
@ywen1407 @arjun0502 I got the same error. Did you figure out a way to fix this? Thanks.
