### ISSUE TITLE
"tag 'NH' not present"

### ISSUE THREAD

**Issue by Cumol** [velocyto-team/velocyto.py#198]
Trying to run velocyto with the following command:

`velocyto run-smartseq2 -o OUTPUT -e *sorted.bam gencode.vM21.annotation.gtf`

Getting following error:
```
2019-05-27 17:00:20,075 - DEBUG - Read first 0 million reads
Traceback (most recent call last):
  File "/home/generalubuntu/anaconda3/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto', 'console_scripts', 'velocyto')()
  File "/home/generalubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/generalubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/generalubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/generalubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/generalubuntu/anaconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/generalubuntu/velocyto.py/velocyto/commands/run_smartseq2.py", line 74, in run_smartseq2
    samtools_memory=1, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/home/generalubuntu/velocyto.py/velocyto/commands/_run.py", line 229, in _run
    results = exincounter.count(bamfile_cellsorted, multimap=multimap)  # NOTE: we would avoid some millions of if statements evaluations if we write two function count and count_with output
  File "/home/generalubuntu/velocyto.py/velocyto/counter.py", line 756, in count
    for r in self.iter_alignments(bamfile, unique=not multimap):
  File "/home/generalubuntu/velocyto.py/velocyto/counter.py", line 258, in iter_alignments
    if unique and read.get_tag("NH") != 1:
  File "pysam/libcalignedsegment.pyx", line 2392, in pysam.libcalignedsegment.AlignedSegment.get_tag
  File "pysam/libcalignedsegment.pyx", line 2434, in pysam.libcalignedsegment.AlignedSegment.get_tag
KeyError: "tag 'NH' not present"

```

If I understood correctly, the NH tag is something that is found in the bam files and is added by the alignment software.

**Comment by cap76** [comment]
@Cumol did you resolve this? Having the same problem now.

**Comment by Cumol** [comment]
@cap76 I don't remember that well but I think that the alignment did not work that well.

Had to re-run the alignment with STAR and it resolved it.

Good luck!

**Comment by cap76** [comment]
Great, thanks @Cumol I think I figured it out. In this case I was using data from a SOLiD sequencing run, hence colourspace. I don't think either bowtie or bwa add the NT tag.

**Comment by stsiebert** [comment]
Running into the same problem using a Bowtie2 bam file. It seems this tag is not needed according to the velocyto manual? Could this be case be caught?

**Comment by Smriti1990** [comment]
@cap76 Can you please tell me how did you align your files in case of SOLiD sequencing? Thanks
