### ISSUE TITLE
run10x Trouble creating loom files : cellsorted file not found

### ISSUE THREAD

**Issue by reginawongg** [velocyto-team/velocyto.py#204]
Hi, 

I ran this command 

> velocyto run -b "/path/barcodes.tsv" -m "/path/hg38_rmsk.gtf" "/path/outs/possorted_genome_bam.bam" "/path/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf"

and received the following errors: 

> 2019-06-21 14:42:09,834 - INFO - Starting the sorting process of /path/outs/possorted_genome_bam.bam the output will be at: /path/outs/cellsorted_possorted_genome_bam.bam
> 2019-06-21 14:42:09,834 - INFO - Command being run is: samtools sort -l 7 -m 2000M -t CB -O BAM -@ 16 -o /path/outs/cellsorted_possorted_genome_bam.bam /path/outs/possorted_genome_bam.bam
> 2019-06-21 14:42:09,834 - INFO - While the bam sorting happens do other things...
> 2019-06-21 14:42:09,834 - INFO - Load the annotation from /path/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf
> sort: invalid option -- 't'
> sort: invalid option -- 'O'
> open: No such file or directory
> [bam_sort_core] fail to open file CB
> 
> 2019-06-21 15:59:20,518 - DEBUG - End of file. Reset index: start scanning from initial position.
> 2019-06-21 15:59:20,519 - DEBUG - 3416460 reads were skipped because no apropiate cell or umi barcode was found
> 2019-06-21 15:59:20,519 - INFO - Now just waiting that the bam sorting process terminates
> 2019-06-21 15:59:20,519 - INFO - bam file #0 has been sorted
> 2019-06-21 15:59:20,519 - DEBUG - Start molecule counting!

> Failed to open file /path/outs/cellsorted_possorted_genome_bam.bam
> Traceback (most recent call last):
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/mamba/bin/velocyto", line 10, in <module>
>     sys.exit(cli())
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/mamba/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/ma/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/ma/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/ma/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/ma/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/ma/lib/python3.7/site-packages/velocyto/commands/run.py", line 116, in run
>     samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/ma/lib/python3.7/site-packages/velocyto/commands/_run.py", line 229, in _run
>     results = exincounter.count(bamfile_cellsorted, multimap=multimap)  # NOTE: we would avoid some millions of if statements evaluations if we write two function count and count_with output
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/ma/lib/python3.7/site-packages/velocyto/counter.py", line 756, in count
>     for r in self.iter_alignments(bamfile, unique=not multimap):
>   File "/mnt/software/unstowable/miniconda3-4.6.14/envs/ma/lib/python3.7/site-packages/velocyto/counter.py", line 251, in iter_alignments
>     fin = pysam.AlignmentFile(bamfile)  # type: pysam.AlignmentFile
>   File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
>   File "pysam/libcalignmentfile.pyx", line 935, in pysam.libcalignmentfile.AlignmentFile._open
> FileNotFoundError: [Errno 2] could not open alignment file `/path/outs/cellsorted_possorted_genome_bam.bam`: No such file or directory
> 

Does anyone know the solution to this? 
I cannot find the file called cellsorted_postsorted_genome_bam.bam in the output folder it listed.

Thanks!

**Comment by GildasLepennetier** [comment]
Hi there. I have the same problem:
Obviously the call to the "samtools sort" fail because trying to use options that are not available
see in previous message:
```
sort: invalid option -- 't'
sort: invalid option -- 'O'
```
Therefore the sorted bam file is never created.
cellsorted_postsorted_genome_bam.bam


> Usage:   samtools sort [options] <in.bam> <out.prefix>
> 
> Options: -n        sort by read name
>          -f        use <out.prefix> as full file name instead of prefix
>          -o        final output to stdout
>          -l INT    compression level, from 0 to 9 [-1]
>          -@ INT    number of sorting and compression threads [1]
>          -m INT    max memory per thread; suffix K/M/G recognized [768M]

sametools
Version: 0.1.19-96b5f2294a
(installed and updated from apt on Linux mint; #41~16.04.1-Ubuntu)

(1) It would be great to include a check for the presence of the file in the workflow, and stop it in case of error
(2) Any idea on how to solve that? The command

> samtools sort -l 7 -m 1604M -t CB -O BAM -@ 16 -o ..../cellsorted_possorted_genome_bam.bam ..../possorted_genome_bam.bam

could be run before the beginning of the velocyto command with compatible arguments, maybe, without the "-t CB -O BAM"

**Comment by ArcusGears** [comment]
I have a similar problem, though the only error I'm getting is a FileNotFoundError which keeps throwing however I've checked the path several times and that file should exist.  

`$ velocyto run -m /home/alex/lab/drugres/10x/hg19_rmsk.gtf /home/alex/lab/drugres/10x/D0D3FullSeq/Day0/outs/possorted_genome_bam.bam /data2/CellRanger/REFERENCE/hg19/genes/genes.gtf`

> 2019-10-10 18:47:55,273 - DEBUG - Reading /home/alex/lab/drugres/10x/D0D3FullSeq/Day0/outs/cellsorted_possorted_genome_bam.bam
> [E::hts_open_format] Failed to open file /home/alex/lab/drugres/10x/D0D3FullSeq/Day0/outs/cellsorted_possorted_genome_bam.bam
> Traceback (most recent call last):
>   File "/usr/local/bin/velocyto", line 11, in <module>
>     load_entry_point('velocyto==0.17.17', 'console_scripts', 'velocyto')()
>   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib64/python3.6/site-packages/velocyto/commands/run.py", line 116, in run
>     samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
>   File "/usr/local/lib64/python3.6/site-packages/velocyto/commands/_run.py", line 229, in _run
>     results = exincounter.count(bamfile_cellsorted, multimap=multimap)  # NOTE: we would avoid some millions of if statements evaluations if we write two function count and count_with output
>   File "/usr/local/lib64/python3.6/site-packages/velocyto/counter.py", line 756, in count
>     for r in self.iter_alignments(bamfile, unique=not multimap):
>   File "/usr/local/lib64/python3.6/site-packages/velocyto/counter.py", line 251, in iter_alignments
>     fin = pysam.AlignmentFile(bamfile)  # type: pysam.AlignmentFile
>   File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
>   File "pysam/libcalignmentfile.pyx", line 935, in pysam.libcalignmentfile.AlignmentFile._open
> FileNotFoundError: [Errno 2] could not open alignment file `/home/alex/lab/drugres/10x/D0D3FullSeq/Day0/outs/cellsorted_possorted_genome_bam.bam`: No such file or directory

**Comment by karakach** [comment]
Did anyone ever get a response or a solution to this? I'm running into the same problem and I think the issue is that velocyto is using the wrong syntax for samtools (rather an older syntax). 
So, your options are: (a) use an older version of samtools, (b) sort the cells outside of velocyto and create a dummy file called 'cellsorted_possorted_genome_bam.bam' or, (c) find an updated version of velocyto that uses the correct syntax. Not sure if (c) is a possibility.

**Comment by GildasLepennetier** [comment]
Guys, I think I found the problem for me:
I had install a samtools using **apt-get**
Try this: 

> - uninstall this version that does not have the options (apt remove samtools)
> - get the samtools from github: **git clone https://github.com/samtools/samtools.git**
> - get the htslib which is a requirement I believe: **git clone https://github.com/samtools/htslib**
> - follow the instructions concerning the installation of those two packages, meaning use the --with-htslib=DIR when compiling saltools
> - once samtools is build, either it is installed (already in $PATH) or the program is in a directory, and you can just add this directory to the $PATH (I added the PATH in the ~/.bashrc file)
> - open a new terminal, and try to run again your velocyto run 

@karakach -> try to use **velocyto run10x** which is a wrapper. you have to give the path of the director that contain the **outs/** directory
@ArcusGears This seem to be another problem. I suspect the file is not where it is expected "could not open alignment file : cellsorted_possorted_genome_bam.bam". You are giving the pyth to possorted_genome_bam.bam, and the **cellsorted_**possorted_genome_bam.bam should be created just there too. If it is not there, then the samtools did not create it properly.

**Comment by karakach** [comment]
@GildasLepennetier Thanks for your suggestion. That doesn't work either, I have had to work around that issue. I think this would be a very good time to get a response/suggestion from the authors.
After I circumvented that issue I ended up with a different one that goes like this for over 6 hours:
2019-10-13 13:54:56,888 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:56,891 - DEBUG - Counting for batch 36357, containing 100 cells and 115 reads
2019-10-13 13:54:56,900 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:56,902 - DEBUG - Counting for batch 36358, containing 100 cells and 124 reads
2019-10-13 13:54:56,909 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:56,911 - DEBUG - Counting for batch 36359, containing 100 cells and 119 reads
2019-10-13 13:54:56,928 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:56,931 - DEBUG - Counting for batch 36360, containing 100 cells and 108 reads
2019-10-13 13:54:56,939 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:56,940 - DEBUG - Counting for batch 36361, containing 100 cells and 106 reads
2019-10-13 13:54:56,947 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:56,949 - DEBUG - Counting for batch 36362, containing 100 cells and 111 reads
2019-10-13 13:54:56,956 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:56,958 - DEBUG - Counting for batch 36363, containing 100 cells and 114 reads
2019-10-13 13:54:56,965 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:56,969 - DEBUG - Counting for batch 36364, containing 100 cells and 105 reads
2019-10-13 13:54:56,992 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:56,994 - DEBUG - Counting for batch 36365, containing 100 cells and 118 reads
2019-10-13 13:54:57,007 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,010 - DEBUG - Counting for batch 36366, containing 100 cells and 118 reads
2019-10-13 13:54:57,019 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,022 - DEBUG - Counting for batch 36367, containing 100 cells and 116 reads
2019-10-13 13:54:57,029 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,031 - DEBUG - Counting for batch 36368, containing 100 cells and 121 reads
2019-10-13 13:54:57,039 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,041 - DEBUG - Counting for batch 36369, containing 100 cells and 118 reads
2019-10-13 13:54:57,054 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,057 - DEBUG - Counting for batch 36370, containing 100 cells and 128 reads
2019-10-13 13:54:57,070 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,072 - DEBUG - Counting for batch 36371, containing 100 cells and 148 reads
2019-10-13 13:54:57,087 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,089 - DEBUG - Counting for batch 36372, containing 100 cells and 196 reads
2019-10-13 13:54:57,104 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,107 - DEBUG - Counting for batch 36373, containing 100 cells and 181 reads
2019-10-13 13:54:57,122 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,124 - DEBUG - Counting for batch 36374, containing 100 cells and 138 reads
2019-10-13 13:54:57,138 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,140 - DEBUG - Counting for batch 36375, containing 100 cells and 138 reads
2019-10-13 13:54:57,148 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,150 - DEBUG - Counting for batch 36376, containing 100 cells and 141 reads
2019-10-13 13:54:57,158 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,161 - DEBUG - Counting for batch 36377, containing 100 cells and 141 reads
2019-10-13 13:54:57,169 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,171 - DEBUG - Counting for batch 36378, containing 100 cells and 128 reads
2019-10-13 13:54:57,179 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,183 - DEBUG - Counting for batch 36379, containing 100 cells and 113 reads
2019-10-13 13:54:57,201 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,204 - DEBUG - Counting for batch 36380, containing 100 cells and 124 reads
2019-10-13 13:54:57,212 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,214 - DEBUG - Counting for batch 36381, containing 100 cells and 131 reads
2019-10-13 13:54:57,228 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,230 - DEBUG - Counting for batch 36382, containing 100 cells and 131 reads
2019-10-13 13:54:57,237 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,239 - DEBUG - Counting for batch 36383, containing 100 cells and 138 reads
2019-10-13 13:54:57,247 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,249 - DEBUG - Counting for batch 36384, containing 100 cells and 137 reads
2019-10-13 13:54:57,257 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,263 - DEBUG - Counting for batch 36385, containing 100 cells and 134 reads
2019-10-13 13:54:57,279 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,281 - DEBUG - Counting for batch 36386, containing 100 cells and 131 reads
2019-10-13 13:54:57,296 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,299 - DEBUG - Counting for batch 36387, containing 100 cells and 146 reads
2019-10-13 13:54:57,308 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,311 - DEBUG - Counting for batch 36388, containing 100 cells and 136 reads
2019-10-13 13:54:57,318 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,320 - DEBUG - Counting for batch 36389, containing 100 cells and 141 reads
2019-10-13 13:54:57,328 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-10-13 13:54:57,330 - DEBUG - Counting for batch 36390, containing 100 cells and 149 reads
2019-10-13 13:54:57,344 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions

**Comment by reginawongg** [comment]
Hi, 

I realized there was an issue with samtools sort. Thus I ran this command separately first: 

`samtools sort -t CB -O BAM -o ~/outputfolder/cellsorted_possorted_genome_bam.bam ~path/possorted_genome_bam.bam`

This requires samtools to be installed separately. Once this cellsorted file was generated, I placed it/outputted it in the expected folder where cellsorted is supposed to be found. Then, I subsequently ran **velocyto run** where it was able to skip this step as the file already exists. 

Hope this helps!

**Comment by sidrahmaryam** [comment]
> Hi,
> 
> I realized there was an issue with samtools sort. Thus I ran this command separately first:
> 
> `samtools sort -t CB -O BAM -o ~/outputfolder/cellsorted_possorted_genome_bam.bam ~path/possorted_genome_bam.bam`
> 
> This requires samtools to be installed separately. Once this cellsorted file was generated, I placed it/outputted it in the expected folder where cellsorted is supposed to be found. Then, I subsequently ran **velocyto run** where it was able to skip this step as the file already exists.
> 
> Hope this helps!



Hello,
I did the same. I firstly executed samtools sort command and then tried velocyto run. However, I am getting a big issue. 
I am doing it without UMI-barcode file, and also i am using -U tag.

My command line is :

`velocyto run --without-umi -o /5TB-storage/gaurav.ahuja/sidrah/Data/b_mouse_linda/trimmed/bams/cellsorted/loom -m /5TB-storage/gaurav.ahuja/sidrah/Data/filesforvelocyto/mm10_rmsk.gtf /5TB-storage/gaurav.ahuja/sidrah/Data/b_mouse_linda/trimmed/bams/cellsorted/$line1.bam /5TB-storage/gaurav.ahuja/sidrah/Data/filesforvelocyto/Mus_musculus.GRCm38.101.gtf`
I got this error.

ile "/home/gaurav.ahuja/anaconda2/envs/velocyto/bin/velocyto", line 8, in
sys.exit(cli())
File "/home/gaurav.ahuja/anaconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 764, in call
return self.main(*args, **kwargs)
File "/home/gaurav.ahuja/anaconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/home/gaurav.ahuja/anaconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/gaurav.ahuja/anaconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/gaurav.ahuja/anaconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/home/gaurav.ahuja/anaconda2/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/run.py", line 116, in run
samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
File "/home/gaurav.ahuja/anaconda2/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/_run.py", line 159, in _run
exincounter.peek(bamfile[0])
File "/home/gaurav.ahuja/anaconda2/envs/velocyto/lib/python3.6/site-packages/velocyto/counter.py", line 158, in peek
raise IOError("The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")
OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are running UMI-less data you should use the -U flag.
^CTraceback (most recent call last):
File "/home/gaurav.ahuja/anaconda2/envs/velocyto/lib/python3.6/site-packages/llvmlite/ir/_utils.py", line 48, in str
return self.__cached_str
AttributeError: 'GEPInstr' object has no attribute '_StrCaching__cached_str'


Please help me in this regard. Thank you.
