### ISSUE TITLE
FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future

### ISSUE THREAD

**Issue by zl7515** [velocyto-team/velocyto.py#209]
I'm now trying to reproduce the results from https://github.com/velocyto-team/velocyto-notebooks/blob/master/python/DentateGyrus.ipynb

Unfortunately, vlm.estimate_transition_prob(hidim="Sx_sz", embed="ts", transform="sqrt", psc=1, n_neighbors=2000, knn_random=True, sampled_fraction=0.5)  raises warning:

FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future

Can anyone help me resolve this?

Thanks in advance for your help!

Allen

**Comment by tanpuekai** [comment]
same problem.

**Comment by swaggyLi** [comment]
same warning

**Comment by zeysert** [comment]
same issue

**Comment by Norreanea** [comment]
For the following packages:
```
numpy==1.26.4
scipy==1.13.0
matplotlib==3.8.4
loompy==3.0.7
velocyto==0.17.17
pandas==2.2.2
logging==0.5.1.2
```

`vlm.estimate_transition_prob(hidim="Sx_sz", embed="ts", transform="sqrt",n_neighbors=5000, knn_random=True, sampled_fraction=1) `gives now not a warning, but an error: 
File [~/anaconda3/envs/paga/lib/python3.12/site-packages/velocyto/analysis.py:1566](http://localhost:8888/lab/tree/~/anaconda3/envs/paga/lib/python3.12/site-packages/velocyto/analysis.py#line=1565), in VelocytoLoom.estimate_transition_prob(self, hidim, embed, transform, ndims, n_sight, psc, knn_random, sampled_fraction, sampling_probs, max_dist_embed, n_jobs, threads, calculate_randomized, random_seed, **kwargs)
   1559 p = p / p.sum()
   1561 # There was a problem of API consistency because the random.choice can pick the diagonal value (or not)
   1562 # resulting self.corrcoeff with different number of nonzero entry per row.
   1563 # Not updated yet not to break previous analyses
   1564 # Fix is substituting below `neigh_ixs.shape[1]` with `np.arange(1,neigh_ixs.shape[1]-1)`
   1565 # I change it here since I am doing some breaking changes
-> 1566 sampling_ixs = np.stack((np.random.choice(neigh_ixs.shape[1],
   1567                                           size=(int(sampled_fraction * (n_neighbors + 1)),),
   1568                                           replace=False,
   1569                                           p=p) for i in range(neigh_ixs.shape[0])), 0)
   1570 self.sampling_ixs = sampling_ixs
   1571 neigh_ixs = neigh_ixs[np.arange(neigh_ixs.shape[0])[:, None], sampling_ixs]

File [~/anaconda3/envs/paga/lib/python3.12/site-packages/numpy/core/shape_base.py:364](http://localhost:8888/lab/tree/~/anaconda3/envs/paga/lib/python3.12/site-packages/numpy/core/shape_base.py#line=363), in _stack_dispatcher(arrays, axis, out, dtype, casting)
    362 def _stack_dispatcher(arrays, axis=None, out=None, *,
    363                       dtype=None, casting=None):
--> 364     arrays = _arrays_for_stack_dispatcher(arrays)
    365     if out is not None:
    366         # optimize for the typical case where only arrays is provided
    367         arrays = list(arrays)

File [~/anaconda3/envs/paga/lib/python3.12/site-packages/numpy/core/shape_base.py:209](http://localhost:8888/lab/tree/~/anaconda3/envs/paga/lib/python3.12/site-packages/numpy/core/shape_base.py#line=208), in _arrays_for_stack_dispatcher(arrays)
    207 def _arrays_for_stack_dispatcher(arrays):
    208     if not hasattr(arrays, "__getitem__"):
--> 209         raise TypeError('arrays to stack must be passed as a "sequence" type '
    210                         'such as list or tuple.')
    212     return tuple(arrays)

TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

**Comment by SilenWang** [comment]
As the FutureWarning indicates, there is an API change in NumPy. In versions of NumPy prior to 1.16, the code can run with a warning, so you should consider using conda to lock the NumPy version to 1.16 or earlier. If you have other single-cell packages, such as Scanpy, that have a dependency conflict with NumPy versions less than or equal to 1.16, you might try installing the packages using pip from PyPI, or consider splitting those packages into different environments.

> For the following packages:
> 
> ```
> numpy==1.26.4
> scipy==1.13.0
> matplotlib==3.8.4
> loompy==3.0.7
> velocyto==0.17.17
> pandas==2.2.2
> logging==0.5.1.2
> ```
> 
> `vlm.estimate_transition_prob(hidim="Sx_sz", embed="ts", transform="sqrt",n_neighbors=5000, knn_random=True, sampled_fraction=1) `gives now not a warning, but an error:
> 
> ```
> File [~/anaconda3/envs/paga/lib/python3.12/site-packages/velocyto/analysis.py:1566](http://localhost:8888/lab/tree/~/anaconda3/envs/paga/lib/python3.12/site-packages/velocyto/analysis.py#line=1565), in VelocytoLoom.estimate_transition_prob(self, hidim, embed, transform, ndims, n_sight, psc, knn_random, sampled_fraction, sampling_probs, max_dist_embed, n_jobs, threads, calculate_randomized, random_seed, **kwargs)
>    1559 p = p / p.sum()
>    1561 # There was a problem of API consistency because the random.choice can pick the diagonal value (or not)
>    1562 # resulting self.corrcoeff with different number of nonzero entry per row.
>    1563 # Not updated yet not to break previous analyses
>    1564 # Fix is substituting below `neigh_ixs.shape[1]` with `np.arange(1,neigh_ixs.shape[1]-1)`
>    1565 # I change it here since I am doing some breaking changes
> -> 1566 sampling_ixs = np.stack((np.random.choice(neigh_ixs.shape[1],
>    1567                                           size=(int(sampled_fraction * (n_neighbors + 1)),),
>    1568                                           replace=False,
>    1569                                           p=p) for i in range(neigh_ixs.shape[0])), 0)
>    1570 self.sampling_ixs = sampling_ixs
>    1571 neigh_ixs = neigh_ixs[np.arange(neigh_ixs.shape[0])[:, None], sampling_ixs]
> 
> File [~/anaconda3/envs/paga/lib/python3.12/site-packages/numpy/core/shape_base.py:364](http://localhost:8888/lab/tree/~/anaconda3/envs/paga/lib/python3.12/site-packages/numpy/core/shape_base.py#line=363), in _stack_dispatcher(arrays, axis, out, dtype, casting)
>     362 def _stack_dispatcher(arrays, axis=None, out=None, *,
>     363                       dtype=None, casting=None):
> --> 364     arrays = _arrays_for_stack_dispatcher(arrays)
>     365     if out is not None:
>     366         # optimize for the typical case where only arrays is provided
>     367         arrays = list(arrays)
> 
> File [~/anaconda3/envs/paga/lib/python3.12/site-packages/numpy/core/shape_base.py:209](http://localhost:8888/lab/tree/~/anaconda3/envs/paga/lib/python3.12/site-packages/numpy/core/shape_base.py#line=208), in _arrays_for_stack_dispatcher(arrays)
>     207 def _arrays_for_stack_dispatcher(arrays):
>     208     if not hasattr(arrays, "__getitem__"):
> --> 209         raise TypeError('arrays to stack must be passed as a "sequence" type '
>     210                         'such as list or tuple.')
>     212     return tuple(arrays)
> 
> TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.
> ```

**Comment by SilenWang** [comment]
> As the FutureWarning indicates, there is an API change in NumPy. In versions of NumPy prior to 1.16, the code can run with a warning, so you should consider using conda to lock the NumPy version to 1.16 or earlier. If you have other single-cell packages, such as Scanpy, that have a dependency conflict with NumPy versions less than or equal to 1.16, you might try installing the packages using pip from PyPI, or consider splitting those packages into different environments.

As the FutureWarning indicates, there is an API change in NumPy. In versions of NumPy prior to 1.16, the code can run with a warning, so you should consider using conda to lock the NumPy version to 1.16 or earlier. If you have other single-cell packages, such as Scanpy, that have a dependency conflict with NumPy versions less than or equal to 1.16, you might try installing the packages using pip from PyPI, or consider splitting those packages into different environments.

**Comment by HannanehF** [comment]
Hello,
I want to reproduce the results from (https://github.com/velocyto-team/velocyto-notebooks/blob/master/python/Haber_et_al.ipynb)

Unfortunately, vlm.estimate_transition_prob(hidim="Sx_sz", embed="ts", transform="sqrt", psc=1, n_neighbors=2000, knn_random=True, sampled_fraction=0.5)gives the following error, Could you please help me to solve it.  I want to run it on python 3.11 with package numpy==1.26.4. 

2024-10-02 18:41:32,321 - DEBUG - SSA violators <numba.core.utils.OrderedSet object at 0x7f47b450cdd0>
2024-10-02 18:41:32,691 - DEBUG - Calculate KNN in the embedding space
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/.../Documents/submission_illustrations/Haber2.py", line 178, in <module>
    vlm.estimate_transition_prob(hidim="Sx_sz", embed="ts", transform="sqrt", psc=1,
  File "/net/st1/export/clusterhome/.../myenv/lib/python3.11/site-packages/velocyto/analysis.py", line 1566, in estimate_transition_prob
    sampling_ixs = np.stack((np.random.choice(neigh_ixs.shape[1],
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/st1/export/clusterhome/.../myenv/lib/python3.11/site-packages/numpy/core/shape_base.py", line 364, in _stack_dispatcher
    arrays = _arrays_for_stack_dispatcher(arrays)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/st1/export/clusterhome/.../myenv/lib/python3.11/site-packages/numpy/core/shape_base.py", line 209, in _arrays_for_stack_dispatcher
    raise TypeError('arrays to stack must be passed as a "sequence" type '
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.
