### ISSUE TITLE
Memory error at final step of loom generation

### ISSUE THREAD

**Issue by ChelseaCHENX** [velocyto-team/velocyto.py#211]
Hi, I was having memory problem at final step of loom file generation - there is a similar issue which was solved with a machine with more memory but mine has used the best machine in our department (500G) and still cannot work out. 

I was thinking
- 1 if it was something other than developing issues that I may had problem with.
- 2 if it really is a memory issue whether I can piece the bam file => proceed individually => merge the final loom file (but not sure how)

I had used same script to have successfully generated loom files for other two samples - the unsorted (by barcode) bam files for the three samples are all `63G`. I used velocyto to sort the previous two which produced sorted bam files `76G`, `85G`; for the last one because the intrinsic velocyto samtools also reported out of memory, I used external samtools to sort by CB `~/.conda/envs/py37/bin/samtools sort -t CB -O BAM -o cellsorted_possorted_genome_bam.bam possorted_genome_bam.bam` which produced a `80G` post-sorted bam file (the samtools is the newest). Thus I was confused as the `85G` sample succeeded w/o memory error while the `80G` did.

Std error:
```
Traceback (most recent call last):
  File "/ihome/alee/fangyuan/.conda/envs/py37/bin/velocyto", line 10, in <module>
    sys.exit(cli())
  File "/ihome/alee/fangyuan/.conda/envs/py37/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/ihome/alee/fangyuan/.conda/envs/py37/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/ihome/alee/fangyuan/.conda/envs/py37/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ihome/alee/fangyuan/.conda/envs/py37/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ihome/alee/fangyuan/.conda/envs/py37/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/ihome/alee/fangyuan/.conda/envs/py37/lib/python3.7/site-packages/velocyto/commands/run10x.py", line 115, in run10x
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/ihome/alee/fangyuan/.conda/envs/py37/lib/python3.7/site-packages/velocyto/commands/_run.py", line 274, in _run
    layers[layer_name] = np.concatenate(dict_list_arrays[layer_name], axis=1)
MemoryError
```
tail -30 Std out:
```
tail -30 AL9-runVelocyto.job.out
2019-08-24 18:13:30,246 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:13:32,527 - DEBUG - Counting for batch 22111, containing 100 cells and 103176 reads
2019-08-24 18:13:36,900 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:13:37,516 - DEBUG - Counting for batch 22112, containing 100 cells and 1089 reads
2019-08-24 18:13:38,313 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:13:38,816 - DEBUG - Counting for batch 22113, containing 100 cells and 52008 reads
2019-08-24 18:13:40,847 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:13:41,201 - DEBUG - Counting for batch 22114, containing 100 cells and 2720 reads
2019-08-24 18:13:42,097 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:13:44,979 - DEBUG - Counting for batch 22115, containing 100 cells and 178256 reads
2019-08-24 18:13:51,181 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:13:53,736 - DEBUG - Counting for batch 22116, containing 100 cells and 160862 reads
2019-08-24 18:13:59,172 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:14:00,027 - DEBUG - Counting for batch 22117, containing 100 cells and 919 reads
2019-08-24 18:14:00,798 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:14:03,765 - DEBUG - Counting for batch 22118, containing 100 cells and 196340 reads
2019-08-24 18:14:11,673 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:14:13,078 - DEBUG - Counting for batch 22119, containing 100 cells and 26192 reads
2019-08-24 18:14:14,531 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:14:14,718 - DEBUG - Counting for batch 22120, containing 100 cells and 2018 reads
2019-08-24 18:14:15,566 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:14:15,922 - DEBUG - Counting for batch 22121, containing 100 cells and 36776 reads
2019-08-24 18:14:17,509 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:14:17,769 - DEBUG - Counting for batch 22122, containing 91 cells and 3765 reads
2019-08-24 18:14:18,688 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-08-24 18:14:18,720 - DEBUG - 14362082 reads were skipped because no apropiate cell or umi barcode was found
2019-08-24 18:14:18,721 - DEBUG - Counting done!
2019-08-24 18:14:19,416 - DEBUG - Generating output file /bgfs/alee/10Xseq/1907_10X/cellranger-count/cellranger-count-v3.0.2/AL9/velocyto/AL9.loom
2019-08-24 18:14:19,417 - DEBUG - Collecting row attributes
2019-08-24 18:14:19,521 - DEBUG - Generating data table
```

**Comment by ChelseaCHENX** [comment]
It is solved by splitting original bam -> samtools sort -> velocyto quantification -> loom merge

**Comment by tqh003** [comment]
Hi Chelsea,
I had the same memory error as you, and I tried to solve it using the method you suggested.
I splitted the orginal bam into chromosomes, which resulted in 22 bam files(chr1-19, X,Y, MT), and then velocyto run on these 22 splitted bam files to get 22 loom files.
Could you please tell me how to merge these 22 loom files into one loom file?
I am trying loompy.combine now, but I am not sure whether it is suitable or not, will it treat different chromosomes as different samples?
Thank you in advance.
