### ISSUE TITLE
Installation issue with matlibplot

### ISSUE THREAD

**Issue by rryan2019** [velocyto-team/velocyto.py#219]
Hi there,

Trying to install on mac. Seems like installation was fine but when I run velocyto --help, I get a matlibplot error which seems to be already installed.

Thanks in advance.

rr@al-rr-mgtdy [~/velocyto.py]$ pip install scipy
Requirement already satisfied: scipy in /Users/rr/anaconda3/lib/python3.6/site-packages (1.3.1)
Requirement already satisfied: numpy>=1.13.3 in /Users/rr/anaconda3/lib/python3.6/site-packages (from scipy) (1.17.2)
(base) rr@al-rr-mgtdy [~/velocyto.py]$ vim setup.py 
(base) rr@al-rr-mgtdy [~/velocyto.py]$ pip install -e .
Obtaining file:///Users/rr/velocyto.py
Requirement already satisfied: numpy in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (1.17.2)
Requirement already satisfied: scipy in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (1.3.1)
Requirement already satisfied: cython in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (0.29.13)
Requirement already satisfied: numba in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (0.45.1)
Requirement already satisfied: matplotlib in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (3.1.1)
Requirement already satisfied: scikit-learn in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (0.21.3)
Requirement already satisfied: h5py in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (2.10.0)
Requirement already satisfied: loompy in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (2.0.17)
Requirement already satisfied: pysam in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (0.15.3)
Requirement already satisfied: Click in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (7.0)
Requirement already satisfied: pandas in /Users/rr/anaconda3/lib/python3.6/site-packages (from velocyto==0.17.16) (0.25.1)
Requirement already satisfied: llvmlite>=0.29.0dev0 in /Users/rr/anaconda3/lib/python3.6/site-packages (from numba->velocyto==0.17.16) (0.29.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/rr/anaconda3/lib/python3.6/site-packages (from matplotlib->velocyto==0.17.16) (2.4.2)
Requirement already satisfied: cycler>=0.10 in /Users/rr/anaconda3/lib/python3.6/site-packages (from matplotlib->velocyto==0.17.16) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/rr/anaconda3/lib/python3.6/site-packages (from matplotlib->velocyto==0.17.16) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/rr/anaconda3/lib/python3.6/site-packages (from matplotlib->velocyto==0.17.16) (1.1.0)
Requirement already satisfied: joblib>=0.11 in /Users/rr/anaconda3/lib/python3.6/site-packages (from scikit-learn->velocyto==0.17.16) (0.13.2)
Requirement already satisfied: six in /Users/rr/anaconda3/lib/python3.6/site-packages (from h5py->velocyto==0.17.16) (1.12.0)
Requirement already satisfied: setuptools in /Users/rr/anaconda3/lib/python3.6/site-packages (from loompy->velocyto==0.17.16) (41.2.0)
Requirement already satisfied: pytz>=2017.2 in /Users/rr/anaconda3/lib/python3.6/site-packages (from pandas->velocyto==0.17.16) (2019.2)
Installing collected packages: velocyto
  Running setup.py develop for velocyto
Successfully installed velocyto

(base) rr@al-rr-mgtdy [~/velocyto.py]$ velocyto --help
Traceback (most recent call last):
  File "/Users/rr/anaconda3/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto', 'console_scripts', 'velocyto')()
  File "/Users/rr/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/rr/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/rr/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/rr/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/rr/velocyto.py/velocyto/__init__.py", line 15, in <module>
    from .analysis import VelocytoLoom, scatter_viz, ixs_thatsort_a2b, load_velocyto_hdf5
  File "/Users/rr/velocyto.py/velocyto/analysis.py", line 9, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
(base) rr@al-rrmgtdy [~/velocyto.py]$ conda install matplotlib -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

**Comment by rryan2019** [comment]
Had to restart terminal. Resolved
