### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by acesnik** [velocyto-team/velocyto.py#221]
Hi there,

I'm struggling to install velocyto. No matter how many times and ways I try to install zlib, I still get the following. I've tried installing from source and from PyPI.

AJC

```
Cloning into 'velocyto.py'...
Obtaining file:///mnt/e/source/repos/CellQuant/velocyto.py
Requirement already satisfied: numpy in /home/acesnik/miniconda3/envs/cellquant/lib/python3.6/site-packages (from velocyto==0.17.16) (1.12.1)
Requirement already satisfied: scipy in /home/acesnik/miniconda3/envs/cellquant/lib/python3.6/site-packages (from velocyto==0.17.16) (1.2.1)
Requirement already satisfied: cython in /home/acesnik/miniconda3/envs/cellquant/lib/python3.6/site-packages (from velocyto==0.17.16) (0.29.13)
Requirement already satisfied: numba in /home/acesnik/miniconda3/envs/cellquant/lib/python3.6/site-packages (from velocyto==0.17.16) (0.43.1)
Requirement already satisfied: matplotlib in /home/acesnik/miniconda3/envs/cellquant/lib/python3.6/site-packages (from velocyto==0.17.16) (3.1.0)
Requirement already satisfied: scikit-learn in /home/acesnik/miniconda3/envs/cellquant/lib/python3.6/site-packages (from velocyto==0.17.16) (0.21.2)
Requirement already satisfied: h5py in /home/acesnik/miniconda3/envs/cellquant/lib/python3.6/site-packages (from velocyto==0.17.16) (2.9.0)
Collecting loompy (from velocyto==0.17.16)
  Using cached https://files.pythonhosted.org/packages/d7/ba/7d5cd9fb4e50ddc985d6211a71b91ffa1840e6e23649ef31ee3ad7529c1e/loompy-3.0.1.tar.gz
Collecting pysam (from velocyto==0.17.16)
  Using cached https://files.pythonhosted.org/packages/15/e7/2dab8bb0ac739555e69586f1492f0ff6bc4a1f8312992a83001d3deb77ac/pysam-0.15.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/acesnik/miniconda3/envs/cellquant/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-znhn0mbu/pysam/setup.py'"'"'; __file__='"'"'/tmp/pip-install-znhn0mbu/pysam/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-znhn0mbu/pysam/
    Complete output (121 lines):
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: (env) CC=/home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-cc
    # pysam: (env) CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe
    # pysam: (env) LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections
    checking for gcc... /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-cc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
    checking for /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
    checking for ranlib... /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-ranlib
    checking for grep that handles long lines and -e... /bin/grep
    checking for C compiler warning flags... -Wall
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-cpp
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... no
    checking for inflate in -lz... no
    configure: error: zlib development files not found
    
    HTSlib uses compression routines from the zlib library <http://zlib.net>.
    Building HTSlib requires zlib development files to be installed on the build
    machine; you may need to ensure a package such as zlib1g-dev (on Debian or
    Ubuntu Linux) or zlib-devel (on RPM-based Linux distributions or Cygwin)
    is installed.
    
    FAILED.  This error must be resolved in order to build HTSlib successfully.
    checking for gcc... /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-cc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
    checking for /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
    checking for ranlib... /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-ranlib
    checking for grep that handles long lines and -e... /bin/grep
    checking for C compiler warning flags... -Wall
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... /home/acesnik/miniconda3/envs/cellquant/bin/x86_64-conda_cos6-linux-gnu-cpp
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... no
    checking for inflate in -lz... no
    configure: error: zlib development files not found
    
    HTSlib uses compression routines from the zlib library <http://zlib.net>.
    Building HTSlib requires zlib development files to be installed on the build
    machine; you may need to ensure a package such as zlib1g-dev (on Debian or
    Ubuntu Linux) or zlib-devel (on RPM-based Linux distributions or Cygwin)
    is installed.
    
    FAILED.  This error must be resolved in order to build HTSlib successfully.
    make: ./version.sh: Command not found
    make: ./version.sh: Command not found
    config.mk:2: *** Resolve configure error first.  Stop.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-znhn0mbu/pysam/setup.py", line 241, in <module>
        htslib_make_options = run_make_print_config()
      File "/tmp/pip-install-znhn0mbu/pysam/setup.py", line 68, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "/home/acesnik/miniconda3/envs/cellquant/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/acesnik/miniconda3/envs/cellquant/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by acesnik** [comment]
I've installed `zlib1g-dev` from aptitude, and I've installed `zlib` from conda. Still no luck.

**Comment by acesnik** [comment]
In installed all the stuff like this, and it worked: https://hub.docker.com/r/jsschrepping/velocyto-docker/dockerfile
