### ISSUE TITLE
Error of bulk RNA-seq analysis

### ISSUE THREAD

**Issue by biostat0903** [velocyto-team/velocyto.py#237]
Hi, 
I try to use `velocyto` to analyze the bulk RNA-seq data. Following the setps from others, I first fix the `bam` file, including adding `UB`, `CB` and `NH`. 
Using `simplesam`, the first seqencing of fixed `bam` file is:
````python
>>> x=next(bam)
>>> x.seq
'CTGTTGGGGAGGCAGCTGTAACTCAAAGCCTTAGCCTCTGTTCCCACGAAGGCAGGGCCATCAGGCACCAAAGGG'
>>> x.tags
{'CB': '130', 'NH': 3, 'NM': 3, 'RG': '0', 'UB': 'C037KACXX', 'XA': 'chrY,-59359485,75M,1;chrX,-155256479,75M,1;chr9,+13283,75M,1;chr2,-114357772,75M,1;chr15,-102517926,75M,2;chr12,-92369,75M,2;', 'XT': 'U', 'md': '75'}
>>> x.qname
'HWI-ST661:130:C037KACXX:6:2307:8186:172941'
````
I then sort the `bam` file and use `velocyto`. The code is:
````bash
bamfile3=cellsorted_HG00096.1.M_111124_6.bam
rmskfile=hg19_rmsk.gtf
genefile=genes.gtf
velocyto run ${bamfile3} ${genefile} -m ${rmskfile} -U -c
````
The output of `velocyto` is:
````bash
2019-12-22 10:46:02,336 - DEBUG - Reading cellsorted_HG00096.1.M_111124_6.bam
2019-12-22 10:46:02,337 - DEBUG - Read first 0 million reads
2019-12-22 10:46:22,889 - DEBUG - Read first 10 million reads
2019-12-22 10:46:44,502 - DEBUG - Read first 20 million reads
2019-12-22 10:47:05,499 - DEBUG - Read first 30 million reads
2019-12-22 10:47:26,701 - DEBUG - Read first 40 million reads
2019-12-22 10:47:48,193 - DEBUG - Read first 50 million reads
2019-12-22 10:47:55,151 - DEBUG - End of file. Reset index: start scanning from initial position.
2019-12-22 10:47:55,151 - DEBUG - 0 reads were skipped because no apropiate cell or umi barcode was found
2019-12-22 10:47:55,151 - DEBUG - Start molecule counting!
2019-12-22 10:47:59,338 - DEBUG - Features available for chromosomes : ['1-', '1+', '10-', '10+', '11-', '11+', '12-', '12+', '13-', '13+', '14-', '14+', '15-', '15+', '16-', '16+', '17-', '17+', '18-', '18+', '19-', '19+', '2-', '2+', '20-', '20+', '21-', '21+', '22-', '22+', '3-', '3+', '4-', '4+', '5-', '5+', '6-', '6+', '7-', '7+', '8-', '8+', '9-', '9+', 'GL000191.1-', 'GL000191.1+', 'GL000192.1-', 'GL000193.1-', 'GL000194.1-', 'GL000195.1-', 'GL000201.1-', 'GL000201.1+', 'GL000204.1-', 'GL000205.1+', 'GL000209.1+', 'GL000212.1+', 'GL000213.1-', 'GL000213.1+', 'GL000215.1-', 'GL000218.1-', 'GL000219.1-', 'GL000221.1-', 'GL000222.1-', 'GL000222.1+', 'GL000223.1-', 'GL000223.1+', 'GL000228.1-', 'GL000237.1-', 'GL000242.1+', 'MT-', 'MT+', 'X-', 'X+', 'Y-', 'Y+']
2019-12-22 10:47:59,338 - DEBUG - Mask available for chromosomes : ['1-', '1+', '10-', '10+', '11-', '11+', '11_gl000202_random-', '11_gl000202_random+', '12-', '12+', '13-', '13+', '14-', '14+', '15-', '15+', '16-', '16+', '17-', '17+', '17_ctg5_hap1-', '17_ctg5_hap1+', '17_gl000203_random-', '17_gl000203_random+', '17_gl000204_random-', '17_gl000204_random+', '17_gl000205_random-', '17_gl000205_random+', '17_gl000206_random-', '17_gl000206_random+', '18-', '18+', '18_gl000207_random+', '19-', '19+', '19_gl000208_random-', '19_gl000208_random+', '19_gl000209_random-', '19_gl000209_random+', '1_gl000191_random-', '1_gl000191_random+', '1_gl000192_random-', '1_gl000192_random+', '2-', '2+', '20-', '20+', '21-', '21+', '21_gl000210_random-', '21_gl000210_random+', '22-', '22+', '3-', '3+', '4-', '4+', '4_ctg9_hap1-', '4_ctg9_hap1+', '4_gl000193_random-', '4_gl000193_random+', '4_gl000194_random-', '4_gl000194_random+', '5-', '5+', '6-', '6+', '6_apd_hap1-', '6_apd_hap1+', '6_cox_hap2-', '6_cox_hap2+', '6_dbb_hap3-', '6_dbb_hap3+', '6_mann_hap4-', '6_mann_hap4+', '6_mcf_hap5-', '6_mcf_hap5+', '6_qbl_hap6-', '6_qbl_hap6+', '6_ssto_hap7-', '6_ssto_hap7+', '7-', '7+', '7_gl000195_random-', '7_gl000195_random+', '8-', '8+', '8_gl000196_random-', '8_gl000196_random+', '8_gl000197_random-', '8_gl000197_random+', '9-', '9+', '9_gl000198_random-', '9_gl000198_random+', '9_gl000199_random-', '9_gl000199_random+', '9_gl000200_random-', '9_gl000200_random+', '9_gl000201_random-', '9_gl000201_random+', 'M-', 'M+', 'Un_gl000211-', 'Un_gl000211+', 'Un_gl000212-', 'Un_gl000212+', 'Un_gl000213-', 'Un_gl000213+', 'Un_gl000214-', 'Un_gl000214+', 'Un_gl000215-', 'Un_gl000215+', 'Un_gl000216-', 'Un_gl000216+', 'Un_gl000217-', 'Un_gl000217+', 'Un_gl000218-', 'Un_gl000218+', 'Un_gl000219-', 'Un_gl000219+', 'Un_gl000220-', 'Un_gl000220+', 'Un_gl000221-', 'Un_gl000221+', 'Un_gl000222-', 'Un_gl000222+', 'Un_gl000223-', 'Un_gl000223+', 'Un_gl000224-', 'Un_gl000224+', 'Un_gl000225-', 'Un_gl000225+', 'Un_gl000226+', 'Un_gl000227-', 'Un_gl000227+', 'Un_gl000228-', 'Un_gl000228+', 'Un_gl000229-', 'Un_gl000229+', 'Un_gl000230-', 'Un_gl000230+', 'Un_gl000231-', 'Un_gl000231+', 'Un_gl000232-', 'Un_gl000232+', 'Un_gl000233-', 'Un_gl000233+', 'Un_gl000234-', 'Un_gl000234+', 'Un_gl000235-', 'Un_gl000235+', 'Un_gl000236-', 'Un_gl000236+', 'Un_gl000237-', 'Un_gl000237+', 'Un_gl000238-', 'Un_gl000238+', 'Un_gl000239-', 'Un_gl000239+', 'Un_gl000240-', 'Un_gl000240+', 'Un_gl000241-', 'Un_gl000241+', 'Un_gl000242-', 'Un_gl000242+', 'Un_gl000243-', 'Un_gl000243+', 'Un_gl000244-', 'Un_gl000244+', 'Un_gl000245-', 'Un_gl000245+', 'Un_gl000246-', 'Un_gl000246+', 'Un_gl000247-', 'Un_gl000247+', 'Un_gl000248-', 'Un_gl000248+', 'Un_gl000249-', 'Un_gl000249+', 'X-', 'X+', 'Y-']
2019-12-22 10:47:59,338 - DEBUG - Summarizing the results of intron validation.
2019-12-22 10:47:59,627 - DEBUG - Validated 0 introns (of which unique intervals 0) out of 964599 total possible introns (considering each possible transcript models).
2019-12-22 10:47:59,628 - DEBUG - Reading cellsorted_HG00096.1.M_111124_6.bam
2019-12-22 10:47:59,628 - DEBUG - Read first 0 million reads
2019-12-22 10:48:20,318 - DEBUG - Read first 10 million reads
2019-12-22 10:48:41,419 - DEBUG - Read first 20 million reads
2019-12-22 10:49:02,291 - DEBUG - Read first 30 million reads
2019-12-22 10:49:23,183 - DEBUG - Read first 40 million reads
2019-12-22 10:49:44,123 - DEBUG - Read first 50 million reads
2019-12-22 10:49:50,993 - DEBUG - Counting for batch 1, containing 0 cells and 0 reads
2019-12-22 10:49:50,993 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2019-12-22 10:49:50,993 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
2019-12-22 10:49:50,993 - WARNING - 0 of the barcodes where without cell
2019-12-22 10:49:50,993 - DEBUG - 0 reads were skipped because no apropiate cell or umi barcode was found
2019-12-22 10:49:50,993 - DEBUG - Counting done!
Traceback (most recent call last):
  File "/net/mulan/home/yasheng/py3/bin/velocyto", line 10, in <module>
    sys.exit(cli())
  File "/net/mulan/home/yasheng/py3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/net/mulan/home/yasheng/py3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/net/mulan/home/yasheng/py3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/net/mulan/home/yasheng/py3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/net/mulan/home/yasheng/py3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/net/mulan/home/yasheng/py3/lib/python3.7/site-packages/velocyto/commands/run.py", line 116, in run
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/net/mulan/home/yasheng/py3/lib/python3.7/site-packages/velocyto/commands/_run.py", line 242, in _run
    logging.debug(f"Example of barcode: {valid_bcs_list[0]} and cell_id: {valid_cellid_list[0]}")
IndexError: list index out of range
````
Would you like to tell me why `velocyto` can not get the read information? Is there still some problem of `bam` file?
Thanks for your kindly help!
Best, 
Sheng

**Comment by biostat0903** [comment]
Hi, 
All the problems have been solved. Thanks!
Best, 
Sheng
