### ISSUE TITLE
Bam file does not have umi tags

### ISSUE THREAD

**Issue by shaaaarpy** [velocyto-team/velocyto.py#251]
Hi
I am using https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8869110 this data for my processing.

When i am using only the bam file, i get killed error in creating loom file part. But as suggested in the tutorial, i sorted it using samtools (i think this bam was already sorted) and start geeting the UMI error. 
OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.
-U flag is also not working and giving the same error again
Can you please suggest how to proceed.

Thank you

**Comment by HoxB8** [comment]
Hi I've been trying to trouble shoot a similar problem when trying to run velocyto on the bamfiles.  I try to use samtool to sort as recommended

samtools sort -t CB -O BAM -o cellsorted_possorted_genome_bam.bam possorted_genome_bam.bam


AND THEN I RAN VELOCYTO		


velocyto run -b filtered_feature_bc_matrix/barcodes.tsv -o ./ -m ../../repeat_msk.gtf cellsorted_possorted_genome_bam.bam ../../gencode.vM24.annotation.gtf

Output...it tries to read 5000 lines 
2020-03-28 08:36:05,941 - WARNING - Not found cell and umi barcode in entry 4991 of the bam file
2020-03-28 08:36:05,941 - WARNING - Not found cell and umi barcode in entry 4992 of the bam file
2020-03-28 08:36:05,941 - WARNING - Not found cell and umi barcode in entry 4993 of the bam file
2020-03-28 08:36:05,941 - WARNING - Not found cell and umi barcode in entry 4994 of the bam file
2020-03-28 08:36:05,941 - WARNING - Not found cell and umi barcode in entry 4995 of the bam file
2020-03-28 08:36:05,941 - WARNING - Not found cell and umi barcode in entry 4996 of the bam file
2020-03-28 08:36:05,941 - WARNING - Not found cell and umi barcode in entry 4997 of the bam file
2020-03-28 08:36:05,941 - WARNING - Not found cell and umi barcode in entry 4998 of the bam file
2020-03-28 08:36:05,942 - WARNING - Not found cell and umi barcode in entry 4999 of the bam file
2020-03-28 08:36:05,942 - WARNING - Not found cell and umi barcode in entry 5000 of the bam file
Traceback (most recent call last):
  File "/wynton/home/werblab/liusuy/.local/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto==0.17.17', 'console_scripts', 'velocyto')()
  File "/wynton/home/werblab/liusuy/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/wynton/home/werblab/liusuy/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/wynton/home/werblab/liusuy/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/wynton/home/werblab/liusuy/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/wynton/home/werblab/liusuy/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/wynton/home/werblab/liusuy/.local/lib/python3.6/site-packages/velocyto/commands/run.py", line 116, in run
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/wynton/home/werblab/liusuy/.local/lib/python3.6/site-packages/velocyto/commands/_run.py", line 159, in _run
    exincounter.peek(bamfile[0])
  File "/wynton/home/werblab/liusuy/.local/lib/python3.6/site-packages/velocyto/counter.py", line 158, in peek
    raise IOError("The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")
OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.
[liusuy@qb3-dev3 outs]$ velocyto run -b filtered_feature_bc_matrix/barcodes.tsv -o ./ -m ../../repeat_msk.gtf cellsorted_possorted_timed out waiting for input: auto-logouttion.gtf

I much appreciate any insights.

**Comment by wupeng2** [comment]
Hi shaaaarpy,
 I have the same problem when i run samtools sort. 
OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you 
do you fix it ,and how?
thanks

**Comment by ZJ-zuojing** [comment]
@shaaaarpy @wupeng2 
Hi,
I also have the same problem, do you slove it? 
look forward to your reply . thanks!
