### ISSUE TITLE
ModuleNotFoundError: No module named 'velocyto.speedboosted'

### ISSUE THREAD

**Issue by nmbaker** [velocyto-team/velocyto.py#252]
Hi! I've successfully installed velocyto.py and velocyto.R (after 12+ hours of troubleshooting). Now, when I try and run velocyto --help, I get the following:

(base) $ velocyto --help
Traceback (most recent call last):
  File "/opt/anaconda3/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto', 'console_scripts', 'velocyto')()
  File "/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2855, in load_entry_point
    return ep.load()
  File "/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2446, in load
    return self.resolve()
  File "/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2452, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/NMBaker/velocyto.py/velocyto/__init__.py", line 13, in <module>
    from .estimation import fit_slope, _fit1_slope, clusters_stats
  File "/Users/NMBaker/velocyto.py/velocyto/estimation.py", line 7, in <module>
    from .speedboosted import _colDeltaCor, _colDeltaCorLog10, _colDeltaCorSqrt
ModuleNotFoundError: No module named 'velocyto.speedboosted'

I'm working in a conda environment. I git cloned the repo and did cd velocyto.py pip install -e . I also tried installing the gcc compiler (https://anaconda.org/anaconda/gcc), openMP (https://anaconda.org/conda-forge/openmp), and llvm (https://anaconda.org/anaconda/llvm) through conda (I had already installed using brew for the .R install). I also installed libgcc and cython using conda.

I upgraded to the latest python, anaconda, R, Xcode, and operating system (High Sierra). I've reviewed all related posts to this issue, and saw that the last post said it might have something to do with the compatibility of the compiler with openMP. I wasn't sure what to make of this or how to move forward.

I would really really appreciate any insight you might have to offer.

**Comment by Sumithrasank** [comment]
I am having the same issue

**Comment by alexanderlewis99** [comment]
I am also having the same issue

**Comment by alexanderlewis99** [comment]
I think I found the solution. I've have been doing some research and have found that Mac computer use Apple's compiler Clang by default. As a result, clang is used as the compiler even when you installed the compiler gcc. This is important because clang does not support openMP while gcc does and openMP is needed to install velocyto. Thus, in order to have pip use gcc instead of clang you can do the following.
1. Find out what your version and directory are for gcc.
`gcc --version`
`which gcc`
2. Run the following command:
`CC=PATH/TO/gcc-VERSION pip install velocyto`
I hope this helps. :)

**Comment by felixradtke** [comment]
@alexanderlewis99 How where you able to install a working version of gcc? gcc --version returns "Apple clang version 11.0.3 (clang-1103.0.32.29)", which likely is the reason why I get "unsupported option '-fopenmp'".

**Comment by BenjaminDEMAILLE** [comment]
> I think I found the solution. I've have been doing some research and have found that Mac computer use Apple's compiler Clang by default. As a result, clang is used as the compiler even when you installed the compiler gcc. This is important because clang does not support openMP while gcc does and openMP is needed to install velocyto. Thus, in order to have pip use gcc instead of clang you can do the following.
> 
> 1. Find out what your version and directory are for gcc.
>    `gcc --version`
>    `which gcc`
> 2. Run the following command:
>    `CC=PATH/TO/gcc-VERSION pip install velocyto`
>    I hope this helps. :)

Done but the same
