### ISSUE TITLE
pip install velocyto: ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by sruthi-hub** [velocyto-team/velocyto.py#258]
There is a problem installing velocyto - both on macOS and in Windows. Any help is appreciated!

All the dependencies were installed successfully using:
conda install numpy scipy cython numba matplotlib scikit-learn h5py click

My system info:
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32

Complete error:
(base) C:\Users\sruth>pip install velocyto
Collecting velocyto
  Using cached velocyto-0.17.17.tar.gz (198 kB)
Requirement already satisfied: numpy in c:\users\sruth\appdata\local\continuum\anaconda3\lib\site-packages (from velocyto) (1.18.1)
Requirement already satisfied: scipy in c:\users\sruth\appdata\local\continuum\anaconda3\lib\site-packages (from velocyto) (1.4.1)
Requirement already satisfied: cython in c:\users\sruth\appdata\local\continuum\anaconda3\lib\site-packages (from velocyto) (0.29.17)
Requirement already satisfied: numba in c:\users\sruth\appdata\local\continuum\anaconda3\lib\site-packages (from velocyto) (0.49.0)
Requirement already satisfied: matplotlib in c:\users\sruth\appdata\local\continuum\anaconda3\lib\site-packages (from velocyto) (3.1.3)
Requirement already satisfied: scikit-learn in c:\users\sruth\appdata\local\continuum\anaconda3\lib\site-packages (from velocyto) (0.22.1)
Requirement already satisfied: h5py in c:\users\sruth\appdata\local\continuum\anaconda3\lib\site-packages (from velocyto) (2.10.0)
Collecting loompy
  Using cached loompy-3.0.6.tar.gz (41 kB)
Collecting pysam
  Using cached pysam-0.15.4.tar.gz (1.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\sruth\appdata\local\continuum\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sruth\\AppData\\Local\\Temp\\pip-install-jregty3v\\pysam\\setup.py'"'"'; __file__='"'"'C:\\Users\\sruth\\AppData\\Local\\Temp\\pip-install-jregty3v\\pysam\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sruth\AppData\Local\Temp\pip-install-jregty3v\pysam\pip-egg-info'
         cwd: C:\Users\sruth\AppData\Local\Temp\pip-install-jregty3v\pysam\
    Complete output (23 lines):
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sruth\AppData\Local\Temp\pip-install-jregty3v\pysam\setup.py", line 241, in <module>
        htslib_make_options = run_make_print_config()
      File "C:\Users\sruth\AppData\Local\Temp\pip-install-jregty3v\pysam\setup.py", line 68, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "c:\users\sruth\appdata\local\continuum\anaconda3\lib\subprocess.py", line 376, in check_output
        **kwargs).stdout
      File "c:\users\sruth\appdata\local\continuum\anaconda3\lib\subprocess.py", line 453, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\users\sruth\appdata\local\continuum\anaconda3\lib\subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "c:\users\sruth\appdata\local\continuum\anaconda3\lib\subprocess.py", line 1155, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alexanderlewis99** [comment]
I have this same issue :(

**Comment by hemadelon** [comment]
Me too.
Any solution?

**Comment by sruthi-hub** [comment]
After a year and a half, I still have the same error. How to install pysam dependency successfully?
If anyone figured it out, help is appreciated! Thanks!
