### ISSUE TITLE
velocyto run bam file error

### ISSUE THREAD

**Issue by rsggsr** [velocyto-team/velocyto.py#261]
Hi,

I recently installed velocyto.py on ubutu18.04 by WSL in win10 (Finally czu it get so much troubles to install in win env). But I still could not figure why I could not run velocyto.

I still got "UnicodeDecodeError". Does anyone know how to deal with it? Thanks.

(velocyto) rsggsr@lulab01:/mnt/c/Users/LINM14/Downloads$ velocyto run -b barcodes.tsv -o output_path possorted_genome_bam.bam hg19.refGene.gtf.gz
2020-05-22 19:42:18,432 - INFO - No SAMPLEID specified, the sample will be called possorted_genome_bam_3AG62 (last 5 digits are a random-id to avoid overwriting some other file by mistake)
2020-05-22 19:42:18,433 - DEBUG - Using logic: Default
2020-05-22 19:42:18,437 - INFO - Read 2776 cell barcodes from /mnt/c/Users/LINM14/Downloads/barcodes.tsv
2020-05-22 19:42:18,438 - DEBUG - Example of barcode: AAACCTGCACGCATCG and cell_id: possorted_genome_bam_3AG62:AAACCTGCACGCATCG-1
2020-05-22 19:42:18,769 - WARNING - Your system does not support calling `grep MemAvailable /proc/meminfo` so the memory effort for the samtools command could not be chosen appropriately. 32Gb will be assumed
2020-05-22 19:42:18,770 - DEBUG - Peeking into /mnt/c/Users/LINM14/Downloads/possorted_genome_bam.bam
2020-05-22 19:42:18,772 - WARNING - Not found cell and umi barcode in entry 0 of the bam file
2020-05-22 19:42:18,772 - WARNING - Not found cell and umi barcode in entry 1 of the bam file
2020-05-22 19:42:18,772 - WARNING - Not found cell and umi barcode in entry 45 of the bam file
2020-05-22 19:42:18,772 - WARNING - Not found cell and umi barcode in entry 156 of the bam file
2020-05-22 19:42:18,773 - WARNING - Not found cell and umi barcode in entry 183 of the bam file
2020-05-22 19:42:18,773 - WARNING - Not found cell and umi barcode in entry 184 of the bam file
2020-05-22 19:42:18,773 - WARNING - Not found cell and umi barcode in entry 190 of the bam file
2020-05-22 19:42:18,773 - WARNING - Not found cell and umi barcode in entry 204 of the bam file
2020-05-22 19:42:18,774 - WARNING - Not found cell and umi barcode in entry 205 of the bam file
2020-05-22 19:42:18,774 - WARNING - Not found cell and umi barcode in entry 249 of the bam file
2020-05-22 19:42:18,775 - WARNING - Not found cell and umi barcode in entry 250 of the bam file
2020-05-22 19:42:18,776 - WARNING - Not found cell and umi barcode in entry 365 of the bam file
2020-05-22 19:42:18,777 - WARNING - Not found cell and umi barcode in entry 659 of the bam file
2020-05-22 19:42:18,778 - WARNING - Not found cell and umi barcode in entry 660 of the bam file
2020-05-22 19:42:18,779 - WARNING - Not found cell and umi barcode in entry 661 of the bam file
2020-05-22 19:42:18,779 - WARNING - Not found cell and umi barcode in entry 692 of the bam file
2020-05-22 19:42:18,780 - WARNING - Not found cell and umi barcode in entry 693 of the bam file
2020-05-22 19:42:18,781 - WARNING - Not found cell and umi barcode in entry 700 of the bam file
2020-05-22 19:42:18,781 - WARNING - Not found cell and umi barcode in entry 701 of the bam file
2020-05-22 19:42:18,782 - WARNING - Not found cell and umi barcode in entry 702 of the bam file
2020-05-22 19:42:18,786 - WARNING - Not found cell and umi barcode in entry 747 of the bam file
2020-05-22 19:42:19,129 - INFO - Starting the sorting process of /mnt/c/Users/LINM14/Downloads/possorted_genome_bam.bam the output will be at: /mnt/c/Users/LINM14/Downloads/cellsorted_possorted_genome_bam.bam
2020-05-22 19:42:19,131 - INFO - Command being run is: samtools sort -l 7 -m 2000M -t CB -O BAM -@ 16 -o /mnt/c/Users/LINM14/Downloads/cellsorted_possorted_genome_bam.bam /mnt/c/Users/LINM14/Downloads/possorted_genome_bam.bam
2020-05-22 19:42:19,133 - INFO - While the bam sorting happens do other things...
2020-05-22 19:42:19,134 - INFO - Load the annotation from /mnt/c/Users/LINM14/Downloads/hg19.refGene.gtf.gz
Traceback (most recent call last):
  File "/home/rsggsr/miniconda3/envs/velocyto/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/commands/run.py", line 113, in run
    return _run(bamfile=bamfile, gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/commands/_run.py", line 186, in _run
    annotations_by_chrm_strand = exincounter.read_transcriptmodels(gtffile)
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/counter.py", line 463, in read_transcriptmodels
    gtf_lines = [line for line in open(gtf_file) if not line.startswith('#')]
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/counter.py", line 463, in <listcomp>
    gtf_lines = [line for line in open(gtf_file) if not line.startswith('#')]
  File "/home/rsggsr/miniconda3/envs/velocyto/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by rsggsr** [comment]
I found it's my mistake using the wrong gtf file input. No worries!

**Comment by vagabond12** [comment]
But I have the same error with the right file when with the  repeat mask file.

**Comment by ATpoint** [comment]
Be sure that you do not use a gzipped GTF file.

**Comment by nroak** [comment]
Can someone help with the solution to this error? I have the correct GTF file and still have this issue.

**Comment by ATpoint** [comment]
@nroak Feel free to open s wuestion at biostars.org including code and a `head` of that GTF.
