### ISSUE TITLE
IndexError when using repeat_rmsk.gtf

### ISSUE THREAD

**Issue by ZxyChopcat** [velocyto-team/velocyto.py#263]
Hi velocyto-team,
I tried to analyze 10x scRNA-seq data,but when I added the "-m repeat_rmsk.gtf" option, run10x gives me an error.
`2020-05-27 21:14:15,943 - DEBUG - Assigning indexes to genes
2020-05-27 21:14:15,943 - DEBUG - Seen 33485 genes until now
2020-05-27 21:14:15,943 - DEBUG - Parsing Chromosome Y strand + [line 2562447]
2020-05-27 21:14:15,951 - DEBUG - Assigning indexes to genes
2020-05-27 21:14:15,952 - DEBUG - Done with Y+ [line 2565059]
2020-05-27 21:14:15,952 - DEBUG - Fixing corner cases of transcript models containg intron longer than 1000Kbp
2020-05-27 21:14:18,047 - DEBUG - Generated 2165800 features corresponding to 172912 transcript models from /home/u100337/velocyto/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf
2020-05-27 21:14:18,070 - INFO - Load the repeat masking annotation from /home/u100337/velocyto/repeat_rmsk.gtf
2020-05-27 21:14:18,070 - DEBUG - Reading /home/u100337/velocyto/repeat_rmsk.gtf, the file will be sorted in memory
Traceback (most recent call last):
  File "/home/u100337/miniconda3/envs/velocyto/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/home/u100337/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/u100337/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/u100337/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/u100337/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/u100337/miniconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/u100337/miniconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/commands/run10x.py", line 112, in run10x
    return _run(bamfile=(bamfile, ), gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
  File "/home/u100337/miniconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/commands/_run.py", line 196, in _run
    mask_ivls_by_chromstrand = exincounter.read_repeats(repmask)
  File "/home/u100337/miniconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/counter.py", line 347, in read_repeats
    gtf_lines = sorted(gtf_lines, key=sorting_key)
  File "/home/u100337/miniconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/counter.py", line 345, in sorting_key
    return (x[0], x[6] == "+", int(x[3]), entry)  # The last element of the touple corresponds to the `last resort comparison`
IndexError: list index out of range
`
I run `samtools sort -t CB -O BAM -o /home/u100337/velocyto/sampletest1/outs/cellsorted_possorted_genome_bam.bam /home/u100337/velocyto/sampletest3/outs/possorted_genome_bam.bam` to get a cellsorted_possorted_genome_bam.bam file before this.And the Cellranger version is 3.1.0.

It's the same with run command.I tried `velocyto run -b /home/u100337/velocyto/sampletest/outs/filtered_feature_bc_matrix/filtered_barcodes.tsv -o /home/u100337/velocyto/outputtest -m /home/u100337/velocyto/hg38_rmsk.gtf /home/u100337/velocyto/sampletest/outs/possorted_genome_bam.bam /home/u100337/velocyto/gencode.v34.annotation.gtf`.The error was simillar.

Then I delete the "-m" option.My code is like this:`velocyto run10x -m /home/u100337/velocyto/repeat_rmsk.gtf /home/u100337/velocyto/sampletest1 /home/u100337/velocyto/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf`
But the process was killed
`2020-05-26 23:14:38,009 - DEBUG - Read first 180 million reads
2020-05-26 23:14:43,781 - DEBUG - Counting for batch 38, containing 100 cells and 2000986 reads
2020-05-26 23:16:06,704 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2020-05-26 23:16:50,418 - DEBUG - Counting for batch 39, containing 100 cells and 2140789 reads
2020-05-26 23:18:16,091 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2020-05-26 23:19:01,916 - DEBUG - Counting for batch 40, containing 100 cells and 2112020 reads
2020-05-26 23:20:27,655 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
2020-05-26 23:20:43,370 - DEBUG - Read first 190 million reads
2020-05-26 23:21:14,292 - DEBUG - Counting for batch 41, containing 100 cells and 2434346 reads
Killed
`

Could anybody help me.Thanks a lot!

**Comment by JingleW** [comment]
Hi, I think I met the same problem as you. Have you figured out how to make it work?
When I tried to run velocyto with my 10X data using velocyto run (not velocyto run10X) and delete the "-m" option. It worked. So I guess there is some problems with the rmsk.gtf downloaded from UCSC.  According to https://github.com/velocyto-team/velocyto.py/issues/117, removeing "exon_number" field of the file downloaded from UCSC should be fine. However, I could not find the "exon_number" field in my downloaded file. Could anyone help to specify how to download the rmsk.gtf file correctly from UCSC?

**Comment by sysulance** [comment]
I have encountered a similar problem.
In my case, I double checked the repeat_rmsk.gtf file downloaded from UCSC. It seems that the file was incomplete due to internet problem, revealed by comparing files size in 2 different downloads. So when I found a way to ensure the file was correctly downloaded, [velocyto run] works fine.
I hope this may help!

Just for reference, the correct size for GRCh38_rmsk.gtf should be around 500M.
