### ISSUE TITLE
Not found cell and umi barcode in entry xx of the bam file

### ISSUE THREAD

**Issue by akhst7** [velocyto-team/velocyto.py#276]
I am testing amazon AWS to run Velocyto by using 10X  PBMC_10K.bam file.   Velocyte (one step without splitting a samtools step) seems to run fine without an error (although it takes greater than 7hours!!)  however, it will not complete the run if a sorted bam file is created first separately by samtools as recommenced in the velocity cli guide.

Anyway,  I created a sorted bam file by 

`samtools sort -l 7 -m 2048M -t CB -O BAM -@100 -o /temp/home/cellsorted_PBMC.bam /temp/home/PBMC_10K.bam`

and fired up Velocyte by 

`velocyto run -b filtered_feature_bc_matrix/barcodes.tsv -o /temp/home -m GRCh38_rmsk.gtf cellsorted_PBMC.bam refdata-gex-GRCh38-2020-A/genes/genes.gtf`.

Then I got the error:

```
2020-09-27 21:17:36,428 - INFO - No SAMPLEID specified, the sample will be called cellsorted_PBMC_CQIPR (last 5 digits are a random-id to avoid overwriting some other file by mistake)
2020-09-27 21:17:36,428 - DEBUG - Using logic: Default
2020-09-27 21:17:36,438 - INFO - Read 10985 cell barcodes from /temp/home/filtered_feature_bc_matrix/barcodes.tsv
2020-09-27 21:17:36,438 - DEBUG - Example of barcode: AAACCCAGTATATGGA and cell_id: cellsorted_PBMC_CQIPR:AAACCCAGTATATGGA-1
2020-09-27 21:17:36,448 - DEBUG - Peeking into /temp/home/cellsorted_PBMC.bam
2020-09-27 21:17:36,449 - WARNING - Not found cell and umi barcode in entry 0 of the bam file
.......

E::idx_find_and_load] Could not retrieve index file for '/temp/home/cellsorted_PBMC.bam'
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/velocyto/commands/run.py", line 113, in run
    return _run(bamfile=bamfile, gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/velocyto/commands/_run.py", line 159, in _run
    exincounter.peek(bamfile[0])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/velocyto/counter.py", line 158, in peek
    raise IOError("The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")
OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.

```
AWS set is as follows;

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```
Also, some cpu info;

```
~ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
NUMA node(s):                    4
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           1
Model name:                      AMD EPYC 7571
Stepping:                        2
CPU MHz:                         2477.215
BogoMIPS:                        4399.39
Hypervisor vendor:               KVM
Virtualization type:             full
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdp
                                 e1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma c
                                 x16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefet
                                 ch topoext perfctr_core vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero xsave
                                 erptr arat npt nrip_save
```
I really appreciate any inputs to solve this issue. 

Thanks.

**Comment by akhst7** [comment]
solved

**Comment by kaizen89** [comment]
I have the same messages 
```
Not found cell and umi barcode in entry 128 of the bam file
2021-01-14 15:36:40,749 - WARNING - Not found cell and umi barcode in entry 213 of the bam file
2021-01-14 15:36:40,749 - WARNING - Not found cell and umi barcode in entry 214 of the bam file
2021-01-14 15:36:40,750 - WARNING - Not found cell and umi barcode in entry 313 of the bam file
2021-01-14 15:36:40,750 - WARNING - Not found cell and umi barcode in entry 314 of the bam file
2021-01-14 15:36:40,750 - WARNING - Not found cell and umi barcode in entry 315 of the bam file
2021-01-14 15:36:40,750 - WARNING - Not found cell and umi barcode in entry 827 of the bam file
2021-01-14 15:36:40,751 - WARNING - Not found cell and umi barcode in entry 1003 of the bam file
2021-01-14 15:36:40,777 - INFO - Starting the sorting process of...
```
But then velocyto keeps running normally. Should I care about these warnings?

**Comment by akhst7** [comment]
@kaizen89,  You can just let Velocity run till the end, as long as  there is not issue.   Apparently, my issue raises when the samtool sort step is performed separately form Velocyto.   As long you let Velocyto run samtools sort , it will be ok to run the whole process.

**Comment by 117999** [comment]
@akhst7 Hello, I have also encounter the same problem where the bam file does not contain cell and umi barcodes appropriately formatted.
I have used trimmed R2 file and aligned with StarSolo2.76a, generating an input file `$i'_75bpAligned.sortedByCoord.out.bam` for velocyto running
my code is:
`cd /public/home/ycxiang_zju/XYC/project/2021-4-4/B-PC
for i in B-PC
do
/public/software/genomics/approved/samtools-1.3.1/samtools index $i"_75bpAligned.sortedByCoord.out.bam"
#/public/software/genomics/approved/samtools-1.3.1/samtools sort -o /public/home/ycxiang_zju/XYC/project/2021-4-4/B-PC/$i'_75bpAligned.sort.out.bam' /public/home/ycxiang_zju/XYC/project/2021-4-4/B-PC/$i'_75bpAligned.sortedByCoord.out.bam'
~/.conda/envs/rpy1/bin/velocyto run \
-b bp1_12.TXT.TXT \
-o velocyto1_$i \
-m /public/home/qigao_gdl/XYC/reference/mm10_rmsk.gtf \
$i"_75bpAligned.sort.out.bam" \
/public/home/frlu_gibh/Reference/mm10-3.0.0/gencode.vM22.annotation.gtf
done
`
And it reports:
`2021-04-08 14:40:38,396 - WARNING - Not found cell and umi barcode in entry 4995 of the bam file
2021-04-08 14:40:38,396 - WARNING - Not found cell and umi barcode in entry 4996 of the bam file
2021-04-08 14:40:38,396 - WARNING - Not found cell and umi barcode in entry 4997 of the bam file
2021-04-08 14:40:38,397 - WARNING - Not found cell and umi barcode in entry 4998 of the bam file
2021-04-08 14:40:38,397 - WARNING - Not found cell and umi barcode in entry 4999 of the bam file
2021-04-08 14:40:38,397 - WARNING - Not found cell and umi barcode in entry 5000 of the bam file
/public/home/ycxiang_zju/.local/lib/python3.7/site-packages/numba/np/ufunc/parallel.py:363: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 6103. The TBB threading layer is disabled.
  warnings.warn(problem)
Traceback (most recent call last):
  File "/public/home/ycxiang_zju/.conda/envs/rpy1/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/public/home/ycxiang_zju/.conda/envs/rpy1/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/public/home/ycxiang_zju/.conda/envs/rpy1/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/public/home/ycxiang_zju/.conda/envs/rpy1/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/ycxiang_zju/.conda/envs/rpy1/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/public/home/ycxiang_zju/.conda/envs/rpy1/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/public/home/ycxiang_zju/.conda/envs/rpy1/lib/python3.7/site-packages/velocyto/commands/run.py", line 116, in run
    samtools_memory=samtools_memory, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/public/home/ycxiang_zju/.conda/envs/rpy1/lib/python3.7/site-packages/velocyto/commands/_run.py", line 159, in _run
    exincounter.peek(bamfile[0])
  File "/public/home/ycxiang_zju/.conda/envs/rpy1/lib/python3.7/site-packages/velocyto/counter.py", line 158, in peek
    raise IOError("The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")
OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.
`

**Comment by akhst7** [comment]
@117999, 

Run this code and see 

truncate your baffle:

`samtools view -h yourbamfile.bam | head -n 1000 | samtools view -bS > test.bam`

and then,

```
 samtools view -h truncated.bam |head -n 100
 samtools view -h truncated.bam |head -n 1000
```

and look for `CB:Z` which is a bam tag for UMI.  

You can also try `samtools view -h yourbamfile.bam |grep CB:Z` and see if there is a CB:Z tag.  

My take on this issue is that Velocyte.py definitely has a bug that somehow deletes CB:Z tag.  When I loaded the manually sorted bam and I always got the same error.  So I stop loading the sorted bam to Velocyte and let  Velocyte run samtools and this solved this issue.

**Comment by 117999** [comment]
@akhst7 
Hello,
I have already tried your suggestions to let velocyto run samtools; however, it did not work either. The same error reported.

**Comment by akhst7** [comment]
@117999 
 
So did you run samtools view -h test.bam |head -n 1000 and saw CB:Z tags ?

**Comment by 117999** [comment]
@akhst7 
I have used STARsolo to do alignment, and the output bam file contains CR:Z for barcode, no CB:Z tag.
do I need to change the tag name

**Comment by akhst7** [comment]
@117999 

A following is the output of a bam created by CellRanger;

`A00519:643:HCMYWDSXY:3:2144:3649:12790  16  chr1    498309  1   65M26S  *   0   0   GGCCAAAATATGTAAGCACATTTGCATTTATTAGGCACTTTATTTCCATTATTACACTGTGATATCCCATGTACTCTGCGTTGATACCACT F,,,FF:F,FFFFF:FFFF:FFFFFFFFFFFFF:FFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F:FFFF:FFF:FFFFFFFFFFF NH:i:4  HI:i:1  AS:i:61 nM:i:1  ts:i:26 RG:Z:SC3_v3_NextGem_SI_PBMC_10K:0:1:HCMYWDSXY:3 RE:A:I  xf:i:0  CR:Z:TCATTGTAGTATAGAC   CY:Z:FFFFFFFFFFFFFFFF   CB:Z:TCATTGTAGTATAGAC-1 UR:Z:ACTCTAATCTGC   UY:Z:FFFFF:FFFFFF   UB:Z:ACTCTAATCTGC`

As you can see CB:Z is the UMI tag, CR:Z is UMI sequence.   You may not want change CR to CB so you should create CB.

**Comment by 117999** [comment]
@akhst7 
Thanks, I have changed the outSAMattributes of starsolo to include the CB and UB.
After running, I have got sequences like that 
`A00358:462:HVYTKDSXY:2:2443:27832:28651	0	chr10	3132703	255	75M	*	0	0	GAGACACATGGAAACTAAAAGAAGTTATGAAACAAATGGATTTAATAGATATCTACAGAACATTTTATCCTAAAA	FFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF	NH:i:1	HI:i:1	nM:i:0	AS:i:73	CR:Z:CACGTA	UR:Z:TGAGCAGA	sS:Z:GGTATCAACGCAGAGTACCACGTATGAGCAGATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGGGGGGCGGTTTTGTGACCAATTATATGGTAAATTTTGGTGGTGGTAACATGTGGCACTGTGAATAAGGTATATAATTTTGTTTTAGG	sQ:Z:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFF,FF,,,FFF,F:F,,,FFF,F,F,:F:F,FF::F,,F,:F,FF::,::,:FFFF:::,,,:F,::F,,F:FF,,,F:F,FFFF,,F	sM:i:0	CB:Z:CACGTA	UB:Z:TGAGCAGA`,
while for some unmapped reads, the CB and UB tag would not appear. 
However, when I used the new Aligned Bam to run velocyto, the same error of inappropriately formatted barcode and umi appears. 
Do I need to delete those unmapped reads? If possible, could you give me some example code to do this.
Thanks again

**Comment by akhst7** [comment]
@117999 

Did you check the BAM header ?   Try `samtools view -H` and make sure CB and UB are listed.  Also, run `samtools flagstat `and see anything weird in your reads.

**Comment by akhst7** [comment]
@Junedays 

If sam is not sorted internally or externally, Velocyto will complain and stop. You can run either top or htop and check Velocyte output to see what Velocyte is doing live.   Velocyte runs `samtools` sort first  if bam is not sorted and then proceed to the alignment.
