### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by YifeiSheng** [velocyto-team/velocyto.py#277]
Hi:
I just installed velocyto.py and received this error after typing **velocyto --help**:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hwfssz4/BC_PUB/Software/07.User-defined/04.Medical/shengyifei/cpdb-venv/lib/python3.6/site-packages/velocyto/__init__.py", line 13, in <module>
    from .estimation import fit_slope, _fit1_slope, clusters_stats
  File "/hwfssz4/BC_PUB/Software/07.User-defined/04.Medical/shengyifei/cpdb-venv/lib/python3.6/site-packages/velocyto/estimation.py", line 7, in <module>
    from .speedboosted import _colDeltaCor, _colDeltaCorLog10, _colDeltaCorSqrt
ImportError: dlopen: cannot load any more object with static TLS
```
How to fix this error?
Thank you in advance.

**Comment by xf78** [comment]
I have also encountered this problem. Is there any corresponding solution？

**Comment by xxyyll-1999** [comment]
I have the same problem.Hope there is a solution.

**Comment by yoeHuuui** [comment]
Hi! I find a way to solve this problem. It sames like a bug in lower version of glibc; For more information you can see: https://lover.blog.csdn.net/article/details/117623889. 
For me, I vim the script __init.py__, let the code "from .estimation import fit_slope, _fit1_slope, clusters_stats" at line2.
The modified __init.py__ like this:
```
from .constants import *
from .estimation import fit_slope, _fit1_slope, clusters_stats
from .gene_info import GeneInfo
from .read import Read
from .feature import Feature
from .transcript_model import TranscriptModel
from .segment_match import SegmentMatch
from .indexes import FeatureIndex, TransciptsIndex
from .molitem import Molitem
from .logic import *
from .counter import ExInCounter
from .metadata import MetadataCollection, Metadata
from .neighbors import BalancedKNN, convolve_by_sparse_weights
from .serialization import dump_hdf5, load_hdf5
from .analysis import VelocytoLoom, scatter_viz, ixs_thatsort_a2b, load_velocyto_hdf5
from ._version import __version__

```

**Comment by xxyyll-1999** [comment]
您好，我已收到您的邮件，我会尽快回复。祝生活愉快。

**Comment by ShuqingL** [comment]
Is there any other way to solve this problem?
I installed the glibc-2.26 on my path, then:
export LD_LIBRARY_PATH=/my_path/glibc-2.26/build/lib:$LD_LIBRARY_PATH
velocyto --help #error info: Segmentation fault (core dumped)

**Comment by xxyyll-1999** [comment]
您好，我已收到您的邮件，我会尽快回复。祝生活愉快。
