### ISSUE TITLE
MemoryError when generating data table

### ISSUE THREAD

**Issue by juhaa** [velocyto-team/velocyto.py#28]
Hi,

When running velocyto run on a bam file generated with the cellranger pipeline, I get the following error:
```
2017-11-30 04:28:37,293 - DEBUG - Save 3' junction/exon read counts
2017-11-30 04:28:44,852 - DEBUG - Collecting genes structural info statistics
2017-11-30 04:29:41,614 - DEBUG - Mapping statistics have been saved to D26/possorted_genome_bam_5ON9O_mapstats.hdf5
2017-11-30 04:29:41,616 - DEBUG - Generating output file D26/possorted_genome_bam_5ON9O.loom
2017-11-30 04:29:41,617 - DEBUG - Collecting row attributes
2017-11-30 04:29:41,732 - DEBUG - Generating data table
Traceback (most recent call last):
  File "/home/users/jmehtone/miniconda2/envs/velocyto/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/users/jmehtone/miniconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/jmehtone/miniconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/users/jmehtone/miniconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/users/jmehtone/miniconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/jmehtone/miniconda2/envs/velocyto/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/users/jmehtone/miniconda2/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/run.py", line 90, in run
    intron_validation=introns, additional_ca=additional_ca)
  File "/home/users/jmehtone/miniconda2/envs/velocyto/lib/python3.6/site-packages/velocyto/commands/_run.py", line 205, in _run
    total = spliced + unspliced + ambiguous
MemoryError
```
velocyto was installed to a fresh conda environment with python 3.6 following the installation guide from the docs. velocyto v0.11.0 and loompy v1.1.0 used. Intronic/exonic intervals and repeats annotations were generated as guided by the docs.

Any idea what might be causing this? The bam file consists of around 2k cells with around 200 million mapped reads. This is run on a computing server, so resources (CPU/RAM/disk space) _should not_ be the problem. The bam file itself is ok as I have processed it with other tools.

**Comment by gioelelm** [comment]
Memory error in general indicates impossibility to allocate more memory. It would be useful to specify the comand you are running. Could it be that you are not using the -b option? In that case you might be generating quite big numpy arrays since the pipeline won't filter on the BC tag provided by the bam. However I hardly believe that they will be so huge you can really use up all the memory of a server that way... 

Anyways, I am about to release (hopefully next week) a major update of velocyto where this part of the code has undergone a major refactoring. I will try to debug on the new version if the problem is not solved.

**Comment by juhaa** [comment]
Thanks for the swift reply! The command I was using is this:
```
velocyto run -b raw_gene_bc_matrices/D26/hg19/barcodes.tsv -o D26 -m hg19_rmsk_joined.gtf bam/D26/possorted_genome_bam.bam hg19_gene_ivls.txt
```
Should be ok, right? At least reading the first few lines of the log seems like it's processing the barcodes (and repeats)
```
2017-11-30 00:12:55,666 - DEBUG - No SAMPLEID specified, the sample will be called possorted_genome_bam_5ON9O
2017-11-30 00:12:57,768 - DEBUG - Read 737280 cell barcodes from /research/groups/allseq/data/scRNAseq/raw_data/all/170712_J00117_0051_AHJF3VBBXX/raw_gene_bc_matrices/D26/hg19/barcodes.tsv
2017-11-30 00:12:57,768 - DEBUG - Example of barcode: AAACCTGAGAAACCAT and cell_id: possorted_genome_bam_5ON9O:AAACCTGAGAAACCAT-1
2017-11-30 00:13:15,678 - DEBUG - Read 809544 intervals for 32738 genes from /research/groups/allseq/data/scRNAseq/raw_data/all/170712_J00117_0051_AHJF3VBBXX/hg19_gene_ivls.txt
2017-11-30 00:14:27,386 - DEBUG - Read 4313835 repeat intervals to mask from /research/groups/allseq/data/scRNAseq/raw_data/all/170712_J00117_0051_AHJF3VBBXX/hg19_rmsk_joined.gtf
2017-11-30 00:14:27,386 - DEBUG - Marking up introns...
2017-11-30 00:14:27,387 - DEBUG - Peeking into /research/groups/allseq/data/scRNAseq/raw_data/all/170712_J00117_0051_AHJF3VBBXX/bam/D26/possorted_genome_bam.bam
2017-11-30 00:14:27,586 - DEBUG - Reading /research/groups/allseq/data/scRNAseq/raw_data/all/170712_J00117_0051_AHJF3VBBXX/bam/D26/possorted_genome_bam.bam
```

In any case, I can try again with the new version when you release it.

Until then,
Juha

**Comment by gioelelm** [comment]
Actually is not completelly correct. You should use the filtered barcodes not the raw barcodes. Give it a try.

**Comment by juhaa** [comment]
Ah, I see the problem now. We have been using the unfiltered data in our downstream analyses and foolishly expected I can just plug it in here without thinking the consequences. The memory problems arise from velocyto trying to process all the raw barcodes (740k) as valid cells when in reality only about 2k of them are valid, and only those are listed in the filtered barcodes.

Thanks for your help! Running it now again.
