### ISSUE TITLE
unable to open file hdf5 file 

### ISSUE THREAD

**Issue by dd422** [velocyto-team/velocyto.py#300]
Hi, I am trying to run velocyto on the SmartSeq2 data with following command

    velocyto run-smartseq2 -d 1 `find ./01-genomeAligned/ -name "*.bam" -print` ~/Genomes/Mus_musculus.GRCm39.103.gtf -o 03-velocyto 2> velocyto.log

I am getting following error.  I would really appreciate some advice to fix this error. Thanks

Traceback (most recent call last):
  File "/home/user/anaconda/bin/velocyto", line 33, in <module>
    sys.exit(load_entry_point('velocyto', 'console_scripts', 'velocyto')())
  File "/home/user/anaconda/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/anaconda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/shared/home/user/software/velocyto.py/velocyto/commands/run_smartseq2.py", line 74, in run_smartseq2
    samtools_memory=1, dump=dump, loom_numeric_dtype=dtype, verbose=verbose, additional_ca=additional_ca)
  File "/shared/home/user/software/velocyto.py/velocyto/commands/_run.py", line 229, in _run
    results = exincounter.count(bamfile_cellsorted, multimap=multimap)  # NOTE: we would avoid some millions of if statements evaluations if we write two function count
  File "/shared/home/user/software/velocyto.py/velocyto/counter.py", line 761, in count
    dict_layer_columns, list_bcs = self.count_cell_batch()
  File "/shared/home/user/software/velocyto.py/velocyto/counter.py", line 1182, in _count_cell_batch_non_stranded
    f = h5py.File(os.path.join(self.outputfolder, f"dump/{self.sampleid}.hdf5"))  # From the docs: Read/write if exists, create otherwise (default)
  File "/home/user/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/user/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '03-velocyto/dump/onefilepercell_Cell1_Aligned_and_others_543PS.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

package versions:
loompy (3.0.6), h5py (3.1.0), scipy (1.5.3), numpy-groupies (0.9.13), , click  (7.1.2), numba  (0.52.0), numpy  (1.19.5)

**Comment by NyxSLY** [comment]
use h5py version <= 2.10 can fix the problem
