### ISSUE TITLE
BlockingIOError: [Errno 11] Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

### ISSUE THREAD

**Issue by varunkas** [velocyto-team/velocyto.py#313]
Hi, I am trying to run velocyto on 10x output, but unable to troubleshoot. Does anyone have a clue as to what could be wrong? Thanks!

Code:
`velocyto run10x -m mm10_rmsk.gtf /results/sample1 /genes/genes.gtf`

Here is the error, including the last few lines before it:
`2021-07-29 21:11:16,763 - DEBUG - Counting for batch 195, containing 3 cells and 84554 reads
2021-07-29 21:11:21,300 - DEBUG - 11555 reads not considered because fully enclosed in repeat masked regions
2021-07-29 21:11:21,650 - DEBUG - 9013021 reads were skipped because no apropiate cell or umi barcode was found
2021-07-29 21:11:21,650 - DEBUG - Counting done!
2021-07-29 21:11:21,673 - DEBUG - Generating output file /data/humangen_mouse/hypthmsMittag/results/mpimg_L20987-1_C-wt_wIntrons/velocyto/mpimg_L20987-1_C-wt_wIntrons.loom
2021-07-29 21:11:21,673 - DEBUG - Collecting row attributes
2021-07-29 21:11:21,744 - DEBUG - Generating data table
2021-07-29 21:11:26,582 - DEBUG - Writing loom file
Traceback (most recent call last):
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/velocyto/commands/_run.py", line 286, in _run
    ds = loompy.create(filename=outfile, matrix=total, row_attrs=ra, col_attrs=ca, dtype="float32")
TypeError: create() got an unexpected keyword argument 'matrix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sreenivasan/.omics/python3/3.8.3/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/velocyto/commands/run10x.py", line 112, in run10x
    return _run(bamfile=(bamfile, ), gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/velocyto/commands/_run.py", line 297, in _run
    loompy.create(filename=outfile, layers=tmp_layers, row_attrs=ra, col_attrs=ca, file_attrs={"velocyto.__version__": vcy.__version__, "velocyto.logic": logic})
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/loompy/loompy.py", line 1057, in create
    with new(filename, file_attrs=file_attrs) as ds:
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/loompy/loompy.py", line 993, in new
    ds = connect(filename, validate=False)
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/loompy/loompy.py", line 1389, in connect
    return LoomConnection(filename, mode, validate=validate)
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/loompy/loompy.py", line 84, in __init__
    self._file = h5py.File(filename, mode)
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/h5py/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/work/sreenivasan/.omics/python3/3.8.3/lib/python3.8/site-packages/h5py/_hl/files.py", line 201, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
BlockingIOError: [Errno 11] Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
`

**Comment by varunkas** [comment]
Just as an update - solved. 
Turns out that the error originates from loom.create(). I tested saving a small test numpy.array using the loom.create() and it was generating the same "BlockingIOError: [Errno 11] Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')". To fix this, I added the following line to the script "<dir>/anaconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/commands/run.py":

`os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"`

and ran the `velocyto run` command. I will now test the same fix for the run10x.py file too. Should work. If it does not, I will give an update.
