### ISSUE TITLE
velocyto run  OSError: no BGZF EOF marker; file may be truncated

### ISSUE THREAD

**Issue by shijianasdf** [velocyto-team/velocyto.py#316]
when I run velocyto like this:
>```r
>velocyto run -b /home/shijian/scvelo1/ESCA-5-post-T_.tsv -m /home/shijian/scvelo/human_rmsk.gtf /WFDATA/yang_res_z/0901cp/ESCA-5-post-T/outs/possorted_genome_bam.bam /home/shijian/scvelo/genes.gtf -o /WFDATA/yang_scvelo/ESCA-5-post-T
>
and I got error as follow:
> ```r
>Traceback (most recent call last):
>  File "/home/shijian/anaconda3/bin/velocyto", line 8, in <module>
>    sys.exit(cli())
>  File "/home/shijian/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
>    return self.main(*args, **kwargs)
>  File "/home/shijian/anaconda3/lib/python3.8/site-packages/click/core.py", line 1062, in main
>    rv = self.invoke(ctx)
>  File "/home/shijian/anaconda3/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
>    return _process_result(sub_ctx.command.invoke(sub_ctx))
>  File "/home/shijian/anaconda3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>    return ctx.invoke(self.callback, **ctx.params)
>  File "/home/shijian/anaconda3/lib/python3.8/site-packages/click/core.py", line 763, in invoke
>    return __callback(*args, **kwargs)
>  File "/home/shijian/anaconda3/lib/python3.8/site-packages/velocyto/commands/run.py", line 113, in run
>   return _run(bamfile=bamfile, gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
>  File "/home/shijian/anaconda3/lib/python3.8/site-packages/velocyto/commands/_run.py", line 229, in _run
>    results = exincounter.count(bamfile_cellsorted, multimap=multimap)  # NOTE: we would avoid some millions of if >statements evaluations if we write two function count and count_with output
>  File "/home/shijian/anaconda3/lib/python3.8/site-packages/velocyto/counter.py", line 756, in count
>    for r in self.iter_alignments(bamfile, unique=not multimap):
>  File "/home/shijian/anaconda3/lib/python3.8/site-packages/velocyto/counter.py", line 251, in iter_alignments
>    fin = pysam.AlignmentFile(bamfile)  # type: pysam.AlignmentFile
>  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
>  File "pysam/libcalignmentfile.pyx", line 952, in pysam.libcalignmentfile.AlignmentFile._open
>  File "pysam/libchtslib.pyx", line 365, in pysam.libchtslib.HTSFile.check_truncation
>OSError: no BGZF EOF marker; file may be truncated
>```

**Comment by ShobiStassen** [comment]
@shijianasdf hi did you managed to solve this issue, I also get the EOF error

**Comment by GouQiao** [comment]
> 

Hi did you find a solution about this matter?

**Comment by hyjforesight** [comment]
@GouQiao see here https://github.com/velocyto-team/velocyto.py/issues/250

**Comment by LorenzoLF** [comment]
Hello,

Has anyone found how to fix this recurrent problem? The solutions posted on previous threads (including #250 and #106) do not seem to work.

Thank you very much.
