### ISSUE TITLE
Error while running velocyto run10x

### ISSUE THREAD

**Issue by yurasong** [velocyto-team/velocyto.py#317]
Hello,
I have tried to run velocyto run10x on my data with `velocyto run10x test_set/outs/ test_set/refdata-gex-mm10-2020-A.gtf `
However, it returns the error as below;

2021-10-25 15:35:07,730 - ERROR - This is an older version of cellranger, cannot check if the output are ready, make sure of this yourself
2021-10-25 15:35:07,730 - ERROR - Can not locate the barcodes.tsv file!
Traceback (most recent call last):
  File "/home/audrey/anaconda3/envs/velocyto/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/home/audrey/anaconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/audrey/anaconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/audrey/anaconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/audrey/anaconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/audrey/anaconda3/envs/velocyto/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/audrey/anaconda3/envs/velocyto/lib/python3.8/site-packages/velocyto/commands/run10x.py", line 91, in run10x
    bcfile = bcmatches[0]
IndexError: list index out of range

Could you give me some advice about this issue? Thanks!

Best,

Yura

**Comment by hyjforesight** [comment]
Can not locate the barcodes.tsv file---- u need the barcodes.tsv
change all the files into an absolute path

**Comment by yurasong** [comment]
Hi, sorry for the late response! It works now :) Thanks!!

**Comment by kragrawa** [comment]
Hi, were you able to just solve the problem by specifying the full filepath? I am having the same error, even though I am specifying the full file path.
