### ISSUE TITLE
click CLI - positional argument missing 'test'

### ISSUE THREAD

**Issue by MikeDMorgan** [velocyto-team/velocyto.py#35]
I'm attempting to run Velocyto within a condo environment, a la issue #32.  Upon calling the `run` command, I get a missing argument error that appears to originate from the click module:

Invocation:
velocyto run bam.dir/Uber_sort.bam  mm10_genes.gtf

Traceback (most recent call last):
  File "/home/morgan02/.local/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/Users/morgan02/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/morgan02/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/morgan02/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/morgan02/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/morgan02/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: run() missing 1 required positional argument: 'test'

**Comment by gioelelm** [comment]
Should be fixed now, feel free to reopen in case there are still encountering problems
