### ISSUE TITLE
Fresh Installation is not working

### ISSUE THREAD

**Issue by adRn-s** [velocyto-team/velocyto.py#352]
Commands to reproduce:

````
conda create -n velocyto python=3.9
conda activate velocyto
conda install numpy scipy cython numba matplotlib scikit-learn h5py click
pip install velocyto
velocyto --help
````

Output

````
Traceback (most recent call last):
  File "/data/anaconda/envs/velocyto/bin/velocyto", line 5, in <module>
    from velocyto.commands.velocyto import cli
  File "/data/anaconda/envs/velocyto/lib/python3.9/site-packages/velocyto/__init__.py", line 12, in <module>
    from .neighbors import BalancedKNN, convolve_by_sparse_weights
  File "/data/anaconda/envs/velocyto/lib/python3.9/site-packages/velocyto/neighbors.py", line 2, in <module>
    from numba import jit
  File "/data/anaconda/envs/velocyto/lib/python3.9/site-packages/numba/__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/data/anaconda/envs/velocyto/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/data/anaconda/envs/velocyto/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
`

**Comment by Rohit-Satyam** [comment]
I am getting same error.
