### ISSUE TITLE
memory samtools problems in velocyto run

### ISSUE THREAD

**Issue by ElenaSLuis** [velocyto-team/velocyto.py#354]
Hey, I am having memory problems in velocyto run:

[elenasl@cicdna ~]$ velocyto run --bcfile /home/elenasl/scRNAseq/cellranger/run_msc_CTL_Ranger_count/outs/filtered_feature_bc_matrix/barcodes.tsv.gz --outputfolder /home/elenasl/scRNAseq/scvelo --samtools-threads 16 --samtools-memory 120000 /home/elenasl/scRNAseq/cellranger/run_msc_CTL_Ranger_count/outs/possorted_genome_bam.bam /home/elenasl/scRNAseq/cellranger/refdata/refdata-gex-GRCh38-2020-A/genes/genes.gtf 2> velocyto_control.err > velocyto_CTL.outs

[elenasl@cicdna ~]$ cat velocyto_control.err
samtools sort: couldn't allocate memory for bam_mem
Traceback (most recent call last):
  File "/home/elenasl/.local/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/home/elenasl/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/elenasl/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/elenasl/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/elenasl/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/elenasl/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/elenasl/.local/lib/python3.10/site-packages/velocyto/commands/run.py", line 113, in run
    return _run(bamfile=bamfile, gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
  File "/home/elenasl/.local/lib/python3.10/site-packages/velocyto/commands/_run.py", line 222, in _run
    raise MemoryError(f"bam file #{k} could not be sorted by cells.\n\
MemoryError: bam file #0 could not be sorted by cells.
                This is probably related to an old version of samtools, please install samtools >= 1.6.                In alternative this could be a memory error, try to set the --samtools_memory option to a value compatible with your system.                 Otherwise sort manually by samtools ``sort -l [compression] -m [mb_to_use]M -t [tagname] -O BAM -@ [threads_to_use] -o cellsorted_[bamfile] [bamfile]``

how can I solve?

Elena

**Comment by MishalAshraf** [comment]
hello, bumping this as I am having a similar issue. 

did you ever find a solution?
