### ISSUE TITLE
Trace

### ISSUE THREAD

**Issue by ETAOIK** [velocyto-team/velocyto.py#359]

**Comment by SevenTea7** [comment]
> 亲爱的 velocyto-team， 很抱歉打开这个问题，当我使用 velocyto run-smartseq2 命令操作我排序的 .bam 文件时，我遇到了一个未知的问题。我使用的命令如下：
> 
> `velocyto run-smartseq2 -o results -m ../mm10_repeat_rmsk.gtf -e ./bam/*.bam ../Mus_musculus.GRCm38.91.chr.gtf > velocyto.out &`
> 
> 但是，我得到了我无法理解的回溯，如下所示：
> 
> ```
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/velocyto/commands/_run.py", line 286, in _run
>     ds = loompy.create(filename=outfile, matrix=total, row_attrs=ra, col_attrs=ca, dtype="float32")
> TypeError: create() got an unexpected keyword argument 'matrix'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/bin/velocyto", line 8, in <module>
>     sys.exit(cli())
>   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/velocyto/commands/run_smartseq2.py", line 70, in run_smartseq2
>     return _run(bamfile=bamfiles, gtffile=gtffile, bcfile=None, outputfolder=outputfolder,
>   File "/opt/conda/lib/python3.8/site-packages/velocyto/commands/_run.py", line 297, in _run
>     loompy.create(filename=outfile, layers=tmp_layers, row_attrs=ra, col_attrs=ca, file_attrs={"velocyto.__version__": vcy.__version__, "velocyto.logic": logic})
>   File "/opt/conda/lib/python3.8/site-packages/loompy/loompy.py", line 1065, in create
>     with new(filename, file_attrs=file_attrs) as ds:
>   File "/opt/conda/lib/python3.8/site-packages/loompy/loompy.py", line 991, in new
>     f = h5py.File(name=filename, mode='w')
>   File "/opt/conda/lib/python3.8/site-packages/h5py/_hl/files.py", line 533, in __init__
>     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
>   File "/opt/conda/lib/python3.8/site-packages/h5py/_hl/files.py", line 232, in make_fid
>     fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 126, in h5py.h5f.create
> FileNotFoundError: [Errno 2] Unable to create file (unable to open file: name = '/home/sc_user/test/bam/velocyto/results/./bam/SRR5763767.bam.loom', 
> errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
> ```
> 
> 输出文件的最后几行内容如下：
> 
> ```
> 2023-04-19 06:08:48,878 - DEBUG - Summarizing the results of intron validation.
> 2023-04-19 06:08:49,366 - DEBUG - Validated 0 introns (of which unique intervals 0) out of 660870 total possible introns (considering each possible transcript models).
> 2023-04-19 06:08:49,367 - DEBUG - Reading /home/sc_user/test/bam/SRR5764035.bam
> 2023-04-19 06:08:49,370 - DEBUG - Read first 0 million reads
> 2023-04-19 06:11:29,577 - DEBUG - Counting for batch 1, containing 1 cells and 2959380 reads
> 2023-04-19 06:15:59,586 - DEBUG - 191152 reads in repeat masked regions
> 2023-04-19 06:15:59,587 - DEBUG - 1403417 reads overlapping with features on plus strand
> 2023-04-19 06:15:59,587 - DEBUG - 1354872 reads overlapping with features on minus strand
> 2023-04-19 06:15:59,587 - DEBUG - 127136 reads overlapping with features on both strands
> 2023-04-19 06:17:06,479 - WARNING - The barcode selection mode is off, no cell events will be identified by <80 counts
> 2023-04-19 06:17:06,483 - WARNING - 0 of the barcodes where without cell
> 2023-04-19 06:17:09,193 - DEBUG - 0 reads were skipped because no apropiate cell or umi barcode was found
> 2023-04-19 06:17:09,195 - DEBUG - Counting done!
> 2023-04-19 06:17:09,195 - DEBUG - Example of barcode: SRR5764035.bam and cell_id: ./bam/SRR5763767.bam:SRR5764035.bam
> 2023-04-19 06:17:09,195 - DEBUG - Generating output file /home/sc_user/test/bam/velocyto/./bam/SRR5763767.bam.loom
> 2023-04-19 06:17:09,196 - DEBUG - Collecting row attributes
> 2023-04-19 06:17:09,859 - DEBUG - Generating data table
> 2023-04-19 06:17:09,861 - DEBUG - Writing loom file
> ```
> 
> velocity的版本是V0.17.17。 看来错误发生在最终的 .loom 文件创建过程中，但我不知道如何调试。因此，我想请求您的帮助，非常感谢您的帮助！

I probably had the same problem. But instead of reporting an error, I got a loom file. But, I only have "0 of the barcodes where without cell" "0 reads were skipped because no apropiate cell or umi barcode was found". Running the final loom file with scvelo or velocyto.R will give information about the incorrect file format. Unable to perform rate analysis.
