### ISSUE TITLE
logging.debug(f"Example of barcode: {valid_bcs_list[0].split('-')[0]} and cell_id: {valid_cellid_list[0]}") - IndexError: list index out of range

### ISSUE THREAD

**Issue by denvercal1234GitHub** [velocyto-team/velocyto.py#373]
Hi there, 

I was running `velocyto run10x -m /ceph/project/....../mm10_rmsk_chrMTGTF.gtf /ceph/project/........../10x_scRNA_704-187_CD8P_GEX /ceph/project/borrowlab/shared/scRNASeq_blood_220210/xenon/Blood_CD8T_TranscriptomeTCRseq/Blood_CD8T_scTranscriptome/run_cellranger_count_chrMTGTF/refdata-gex-GRCh38-2020-A_chrMTGTF/genes/genes.gtf`

The `/ceph/project/........../10x_scRNA_704-187_CD8P_GEX` points to the folder `10x_scRNA_704-187_CD8P_GEX` that contains my `outs` folder, which contains the `possorted_genome_bam.bam` that I had ran `samtools` on to sort the cells `samtools sort -t CB -O BAM -o cellsorted_possorted_genome_bam.bam /ceph/project/......./10x_scRNA_704-187_CD8P_GEX/outs/possorted_genome_bam.bam`

But, the `velocyto run10x` command encountered the error as below. 

Would you mind giving me some advice?

Thank you for your help!

```
/package/python-cbrg/current/3.11/lib/python3.11/site-packages/loompy/bus_file.py:67: NumbaDeprecationWarning: [1mThe 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.[0m
  @jit
/package/python-cbrg/current/3.11/lib/python3.11/site-packages/loompy/bus_file.py:84: NumbaDeprecationWarning: [1mThe 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.[0m
  @jit
/package/python-cbrg/current/3.11/lib/python3.11/site-packages/loompy/bus_file.py:101: NumbaDeprecationWarning: [1mThe 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.[0m
  @jit
/package/python-cbrg/current/3.11/lib/python3.11/site-packages/velocyto/commands/run10x.py:106: UserWarning: loadtxt: input contained no data: "/ceph/project/borrowlab/shared/HIVBNAb_TotalCD8_scRNAseq/raw_03_12_2021HIVTodd_scRNAseq_10X_HIV_704707713_TotalCD8/HIVTodd_10x_scRNA_102105702704707713_TotalCD8_GEX/10x_scRNA_704-187_CD8P_GEX/outs/analysis/clustering/graphclust/clusters.csv"
  labels = np.loadtxt(clusters_file, usecols=(1, ), delimiter=',', skiprows=1)
Traceback (most recent call last):
  File "/package/python-cbrg/current/3.11/bin/velocyto", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/velocyto/commands/run10x.py", line 112, in run10x
    return _run(bamfile=(bamfile, ), gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/python-cbrg/current/3.11/lib/python3.11/site-packages/velocyto/commands/_run.py", line 106, in _run
    logging.debug(f"Example of barcode: {valid_bcs_list[0].split('-')[0]} and cell_id: {valid_cellid_list[0]}")
                                         ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by denvercal1234GitHub** [comment]
When unzip the `barcodes.tsv.gz` into `barcodes.tsv`, it works, but encounter error mentioned in #321
