### ISSUE TITLE
ImportError: speedboosted.cpython-38-x86_64-linux-gnu.so: undefined symbol: __log10_finite

### ISSUE THREAD

**Issue by lili03080317** [velocyto-team/velocyto.py#377]
Hi. when I run "velocyto --help",I got the errors. How to fix it? Thank you.

$ velocyto --help
Traceback (most recent call last):
  File "/home/lxl/softwares/miniconda/miniconda3/envs/velocytoP38/bin/velocyto", line 5, in <module>
    from velocyto.commands.velocyto import cli
  File "/home/lxl/softwares/miniconda/miniconda3/envs/velocytoP38/lib/python3.8/site-packages/velocyto/__init__.py", line 13, in <module>
    from .estimation import fit_slope, _fit1_slope, clusters_stats
  File "/home/lxl/softwares/miniconda/miniconda3/envs/velocytoP38/lib/python3.8/site-packages/velocyto/estimation.py", line 7, in <module>
    from .speedboosted import _colDeltaCor, _colDeltaCorLog10, _colDeltaCorSqrt
ImportError: /home/lxl/softwares/miniconda/miniconda3/envs/velocytoP38/lib/python3.8/site-packages/velocyto/speedboosted.cpython-38-x86_64-linux-gnu.so: undefined symbol: __log10_finite

**Comment by taffy-miao** [comment]
try this:
`cd /home/lxl/softwares/miniconda/miniconda3/envs/velocytoP38/lib/python3.8/site-packages/velocyto/`
`md5sum speedboosted.cpython-38-x86_64-linux-gnu.so`


I'm using python 3.9.18 in different server installing velocyto, while server B is successed, A failed. Then I check the file's md5 value, only speedboosted.cpython-38-x86_64-linux-gnu.so is different. When I copy this file from B to A, it successed.
The correct md5sum from my server is e14624358ba9e210cbbd2c86635ca311, please check yours.

**Comment by CWYuan08** [comment]
Hi @lili03080317 @taffy-miao @JobLeonard @pberkes @olgabot 
I also encountered the same issue... I have it with python 3.6.15, not sure where to find the file with the right md5sum.
Do you have any suggestions on how to fix this?

Thank you very much!
Best,
CW

**Comment by WWXkenmo** [comment]
Hey I just manage to fix this error, just uninstall your velocyto, and install it either use conda or mamba

`conda install bioconda::velocyto.py`

**Comment by See-Threepioo** [comment]
Have you resolved this issue? I’ve encountered exactly the same problem. Do you know how to fix it?
