### ISSUE TITLE
[E::bgzf_read_block] Failed to read BGZF header at offset X

### ISSUE THREAD

**Issue by YitengDang** [velocyto-team/velocyto.py#381]
I'm running velocyto with standard 10x data and a standard reference genome (mouse mm10, downloaded from Cell Ranger website). So all I'm doing is

```
GTF_path="[...]/refdata-gex-mm10-2020-A/genes/genes.gtf"
Sample_path_10x="[...]/cellranger_output/L122603" 
velocyto run10x --dtype uint32 -vvv ${Sample_path_10x} $GTF_path
```

However, this throws an error after 1-2 hours, and seems to be related to samtools / bcftools. The error is mentioned at https://www.biostars.org/p/9528498/ but not solved. Does anyone have any clue?

<details>
2023-12-12 17:38:57,969 - DEBUG - Counting for batch 46, containing 100 cells and 2099882 reads
2023-12-12 17:46:03,477 - DEBUG - 0 reads not considered because fully enclosed in repeat masked regions
[E::bgzf_read_block] Failed to read BGZF header at offset 11326734466
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
Traceback (most recent call last):
  File "/Users/yitengdang/miniconda3/envs/velocyto/bin/velocyto", line 33, in <module>
    sys.exit(load_entry_point('velocyto', 'console_scripts', 'velocyto')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yitengdang/miniconda3/envs/velocyto/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yitengdang/miniconda3/envs/velocyto/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/yitengdang/miniconda3/envs/velocyto/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yitengdang/miniconda3/envs/velocyto/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yitengdang/miniconda3/envs/velocyto/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yitengdang/Documents/Projects/Tabler_skull/RNA_seq_BAPN/temp/velocyto.py/velocyto/commands/run10x.py", line 112, in run10x
    return _run(bamfile=(bamfile, ), gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yitengdang/Documents/Projects/Tabler_skull/RNA_seq_BAPN/temp/velocyto.py/velocyto/commands/_run.py", line 229, in _run
    results = exincounter.count(bamfile_cellsorted, multimap=multimap)  # NOTE: we would avoid some millions of if statements evaluations if we write two function count and count_with output
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yitengdang/Documents/Projects/Tabler_skull/RNA_seq_BAPN/temp/velocyto.py/velocyto/counter.py", line 756, in count
    for r in self.iter_alignments(bamfile, unique=not multimap):
  File "/Users/yitengdang/Documents/Projects/Tabler_skull/RNA_seq_BAPN/temp/velocyto.py/velocyto/counter.py", line 252, in iter_alignments
    for i, read in enumerate(fin):
  File "pysam/libcalignmentfile.pyx", line 1877, in pysam.libcalignmentfile.AlignmentFile.__next__
OSError: truncated file
OSError: [Errno 5] Input/output error
Exception ignored in: 'pysam.libcalignmentfile.AlignmentFile.__dealloc__'
OSError: [Errno 5] Input/output error
</details>

It also throws many warnings along the way, including
<details>
2023-12-12 15:38:51,167 - WARNING - Not found cell and umi barcode in entry 81 of the bam file
2023-12-12 15:38:51,167 - WARNING - Not found cell and umi barcode in entry 87 of the bam file
[+more entries]
...
2023-12-12 15:45:21,108 - WARNING - Trashing read, too long span
A01182:143:H7LNVDSX5:4:1449:30165:11553	0	chr12	17890937	255	64M3358848N37M	*	0	0	CTCAGATTGATAACCCCACTGCACCTTGGGTAATGGGCTATGCAAGCTCTTCCCCTGGATTTCAGGAAGAACTACTGAACAAAATAAAAAGTAGAAGGAAA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFFFFF:F:FFFFFFFFF	NH:i:1	HI:i:1	AS:i:86	nM:i:1	RG:Z:L122603:0:1:H7LNVDSX5:4	RE:A:I	xf:i:0	CR:Z:TTCCACGCATAAGATG	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:TTCCACGCATAAGATG-1	UR:Z:CAGTATCACCGG	UY:Z:FFFFFFFFFFFF	UB:Z:CAGTATCACCGG
...
2023-12-12 16:10:30,645 - WARNING - The .bam file refers to a chromosome 'MT+' not present in the annotation (.gtf) file
2023-12-12 16:10:30,645 - WARNING - The .bam file refers to a chromosome 'MT-' not present in the annotation (.gtf) file
...
2023-12-12 17:09:47,704 - DEBUG - Features available for chromosomes : ['GL456210.1-', 'GL456210.1+', 'GL456211.1-', 'GL456211.1+', 'GL456212.1-', 'GL456216.1+', 'GL456219.1-', 'GL456221.1-', 'GL456221.1+', 'GL456233.1-', 'GL456233.1+', 'GL456350.1-', 'GL456354.1-', 'GL456354.1+', 'JH584292.1+', 'JH584293.1-', 'JH584293.1+', 'JH584294.1-', 'JH584294.1+', 'JH584295.1-', 'JH584296.1-', 'JH584297.1-', 'JH584297.1+', 'JH584298.1-', 'JH584298.1+', 'JH584299.1-', 'JH584299.1+', 'JH584303.1+', 'JH584304.1-', '1-', '1+', '10-', '10+', '11-', '11+', '12-', '12+', '13-', '13+', '14-', '14+', '15-', '15+', '16-', '16+', '17-', '17+', '18-', '18+', '19-', '19+', '2-', '2+', '3-', '3+', '4-', '4+', '5-', '5+', '6-', '6+', '7-', '7+', '8-', '8+', '9-', '9+', 'M-', 'M+', 'X-', 'X+', 'Y-', 'Y+']
</details>

**Comment by YitengDang** [comment]
This is likely due to some files in the 10x output folder being zipped when running velocyto and seems to have disappeared after unzipping these files.
