### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by HSvitina** [velocyto-team/velocyto.py#405]
Dear developers

I have problems to install velocyto through anaconda mini-conda, through the Sryder console. pip install velocyto did not go on python 3.9 or 3.11.

Collecting velocyto
  Using cached velocyto-0.17.17.tar.gz (198 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\u0153852\AppData\Local\Temp\pip-install-55o8yc8v\velocyto_f8958368a200418ab96f142c9b467509\setup.py", line 3, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Can you suggest my mistake, please?

**Comment by AlessiaLeclercq** [comment]
hello, I have the same problem here while trying to install it. I first created a virtual environment and activated it
```
> python3 --version
Python 3.9.6
> python3 -m venv virtualEnv
> source virtualEnv/bin/activate
```

I then proceeded by installing velocyto using pip
```
> pip install velocyto 
```

I got the following error messagge
```
    ERROR: Command errored out with exit status 1:
     command: /Users/lrcq/Documents/devtraj/virtualEnv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kx/jq__74vx39z9tptjlhbh6m400000gn/T/pip-install-l7nk6mlv/velocyto_39181c4ec1d14fac87aec8f2aeb4d34f/setup.py'"'"'; __file__='"'"'/private/var/folders/kx/jq__74vx39z9tptjlhbh6m400000gn/T/pip-install-l7nk6mlv/velocyto_39181c4ec1d14fac87aec8f2aeb4d34f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/kx/jq__74vx39z9tptjlhbh6m400000gn/T/pip-pip-egg-info-gmv_k1sc
         cwd: /private/var/folders/kx/jq__74vx39z9tptjlhbh6m400000gn/T/pip-install-l7nk6mlv/velocyto_39181c4ec1d14fac87aec8f2aeb4d34f/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kx/jq__74vx39z9tptjlhbh6m400000gn/T/pip-install-l7nk6mlv/velocyto_39181c4ec1d14fac87aec8f2aeb4d34f/setup.py", line 3, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
```

So I proceeded by manually installing numpy and pysam into the virtualEnv 
```
> python3 -m pip install --upgrade pip
Requirement already satisfied: pip in ./virtualEnv/lib/python3.9/site-packages (21.2.4)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-24.3.1
> pip install numpy 
> pip install pysam
> pip freeze
numpy==2.0.2
pysam==0.22.1
```
When I try then to install again velocyto I get the following:
```
pip install velocyto 
Collecting velocyto
  Using cached velocyto-0.17.17.tar.gz (198 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/lrcq/Documents/devtraj/virtualEnv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/lrcq/Documents/devtraj/virtualEnv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/lrcq/Documents/devtraj/virtualEnv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/kx/jq__74vx39z9tptjlhbh6m400000gn/T/pip-build-env-3hk6f2a5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/kx/jq__74vx39z9tptjlhbh6m400000gn/T/pip-build-env-3hk6f2a5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/kx/jq__74vx39z9tptjlhbh6m400000gn/T/pip-build-env-3hk6f2a5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/kx/jq__74vx39z9tptjlhbh6m400000gn/T/pip-build-env-3hk6f2a5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
What am I missing?  currently running onto arm64 M3 with macOS Sonoma 14.5 :)

**Comment by ishwarvh** [comment]
I am facing this issue too. 

'numpy' installation completes without any issues, however 'pip install velocyto' fails citing 'ModuleNotFoundError: No module named 'numpy''

I installed 'numpy' with Conda and pip, velocity installation fails with the same error message.

**Comment by KokiBio** [comment]
I am also having installation issues. Not sure how to fix this.

Collecting velocyto
  Using cached velocyto-0.17.17.tar.gz (198 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (2.0.2)
Requirement already satisfied: scipy in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (1.15.1)
Requirement already satisfied: cython in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (3.0.11)
Requirement already satisfied: numba in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (0.60.0)
Requirement already satisfied: matplotlib in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (3.10.0)
Requirement already satisfied: scikit-learn in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (1.6.1)
Requirement already satisfied: h5py in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (3.12.1)
Collecting loompy (from velocyto)
  Using cached loompy-3.0.8-py3-none-any.whl
Requirement already satisfied: pysam in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (0.22.1)
Requirement already satisfied: Click in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (8.1.8)
Requirement already satisfied: pandas in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from velocyto) (2.2.3)
Requirement already satisfied: setuptools in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from loompy->velocyto) (75.8.0)
Collecting numpy-groupies (from loompy->velocyto)
  Using cached numpy_groupies-0.11.2-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: contourpy>=1.0.1 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from matplotlib->velocyto) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from matplotlib->velocyto) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from matplotlib->velocyto) (4.55.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from matplotlib->velocyto) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from matplotlib->velocyto) (24.2)
Requirement already satisfied: pillow>=8 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from matplotlib->velocyto) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from matplotlib->velocyto) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from matplotlib->velocyto) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from numba->velocyto) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from pandas->velocyto) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from pandas->velocyto) (2025.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from scikit-learn->velocyto) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from scikit-learn->velocyto) (3.5.0)
Requirement already satisfied: six>=1.5 in /Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->velocyto) (1.17.0)
Using cached numpy_groupies-0.11.2-py3-none-any.whl (40 kB)
Building wheels for collected packages: velocyto
  Building wheel for velocyto (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      ['/private/var/folders/vg/l_tx7bqj4973dqhl_9xxbqhr0000gn/T/pip-install-fbjyn_az/velocyto_c094df6c6f5b4239b6ae089371987457/setup.py', 'bdist_wheel', '-d', '/private/var/folders/vg/l_tx7bqj4973dqhl_9xxbqhr0000gn/T/pip-wheel-mn8pmac6']
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/transcript_model.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/diffusion.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/metadata.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/analysis.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/molitem.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/_version.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/neighbors.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/constants.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/estimation.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/feature.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/logic.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/indexes.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/utils.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/gene_info.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/r_interface.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/segment_match.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/counter.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/serialization.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      copying velocyto/read.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto
      creating build/lib.macosx-11.0-arm64-cpython-310/velocyto/commands
      copying velocyto/commands/velocyto.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto/commands
      copying velocyto/commands/run.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto/commands
      copying velocyto/commands/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto/commands
      copying velocyto/commands/run_smartseq2.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto/commands
      copying velocyto/commands/dropest_bc_correct.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto/commands
      copying velocyto/commands/run_dropest.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto/commands
      copying velocyto/commands/run10x.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto/commands
      copying velocyto/commands/_run.py -> build/lib.macosx-11.0-arm64-cpython-310/velocyto/commands
      running build_ext
      building 'velocyto.speedboosted' extension
      creating build/temp.macosx-11.0-arm64-cpython-310/velocyto
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/ad/miniconda3/envs/celloracle/include -arch arm64 -fPIC -O2 -isystem /Users/ad/miniconda3/envs/celloracle/include -arch arm64 -I/Users/ad/miniconda3/envs/celloracle/lib/python3.10/site-packages/numpy/_core/include -I/Users/ad/miniconda3/envs/celloracle/include/python3.10 -c velocyto/speedboosted.c -o build/temp.macosx-11.0-arm64-cpython-310/velocyto/speedboosted.o -fopenmp -ffast-math
      clang: error: unsupported option '-fopenmp'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for velocyto
  Running setup.py clean for velocyto
Failed to build velocyto
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (velocyto)

**Comment by louhao1129** [comment]
Might be related to the "recent" major numpy version update. When restricting it to numpy<2, at least the velocyto installation works

My solution:

```
conda create -n velocyto2 python=3.10 "numpy<2" scipy cython numba matplotlib scikit-learn h5py click
conda activate velocyto2
pip install velocyto

velocyto --help
```

**Comment by mikemartinez99** [comment]
Apparently velocyte imports numpy at setup time in a temporary virtual environment when installed with pip. 
My solution:

`pip install --no-build-isolation velocyto` 

This seemed to work for me. I'l attach my yaml for versions as well. 

```
name: velocyto-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - click=8.2.1=py310h06a4308_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - cython=3.1.4=py310hee96239_0
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h3385a95_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py310hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gettext=0.21.0=hedfda30_2
  - graphite2=1.3.14=h295c915_1
  - h5py=3.14.0=py310he0d80d8_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jansson=2.14=h5eee18b_1
  - joblib=1.5.2=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h0131e85_1
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm20=20.1.8=h465586c_0
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.0=hde9077f_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvmlite=0.45.1=py310h265b4e5_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.6=py310h06a4308_1
  - matplotlib-base=3.10.6=py310h71dd3da_1
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py310hacdc0fc_0
  - mkl_fft=2.1.1=py310h8fe796d_0
  - mkl_random=1.3.0=py310h505adc9_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py310hb6b6513_0
  - mpich=4.3.2=hf345156_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h7934f7d_0
  - numba=0.62.1=py310h505adc9_0
  - numpy=1.26.4=py310h64c44e4_1
  - numpy-base=1.26.4=py310he1678cf_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py310h06a4308_1
  - pcre2=10.42=hebb0a14_1
  - pillow=12.0.0=py310h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.2.0=py310h06a4308_0
  - pyqt=6.7.1=py310h8dad735_2
  - pyqt6-sip=13.9.1=py310h6ce4db3_2
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.3=hc2a1206_0
  - scikit-learn=1.7.2=py310h505adc9_0
  - scipy=1.15.3=py310h0a862cd_1
  - setuptools=80.9.0=py310h06a4308_0
  - sip=6.10.0=py310h6a678d5_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py310h06a4308_0
  - tornado=6.5.1=py310h5eee18b_0
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
    - loompy==3.0.8
    - numpy-groupies==0.11.3
    - pandas==2.3.3
    - pysam==0.23.3
    - pytz==2025.2
    - tzdata==2025.2
    - velocyto==0.17.17
  ```

**Comment by DrWangL** [comment]
It works
