### ISSUE TITLE
Could not create loom file

### ISSUE THREAD

**Issue by goldfish500** [velocyto-team/velocyto.py#44]
Hi,
I was trying to follow the procedure to run velocyto. However I got the error message when using 10X genomics cellranger output data, until the last step to form loom file. Is there possible reason why this happen? Thanks!

The command I used was:
~/anaconda3/bin/velocyto run10x -m ~/reference/mm10_rmsk.sorted.gtf ~/cellrangerpath/count-WT/ ~/reference/refdata-cellranger-mm10-1.2.0/genes/genes.gtf

It was all good until writing to data:
...
2018-01-25 02:58:37,430 - DEBUG - 866 reads not considered because fully enclosed in repeat masked regions
2018-01-25 02:58:37,681 - DEBUG - Counting done!
2018-01-25 02:58:37,691 - DEBUG - Generating output file /cellrangerpath/count-WT/velocyto/count-WT.loom
2018-01-25 02:58:37,691 - DEBUG - Collecting row attributes
2018-01-25 02:58:37,763 - DEBUG - Generating data table
2018-01-25 02:58:38,975 - DEBUG - Writing loom file
Traceback (most recent call last):
  File "/usr/home/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 100, in run10x
    samtools_memory=samtools_memory, additional_ca=additional_ca)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 222, in _run
    ds = loompy.create(filename=outfile, matrix=total, row_attrs=ra, col_attrs=ca, dtype="float32")
TypeError: create() got an unexpected keyword argument 'matrix'

**Comment by slinnarsson** [comment]
Sorry, this and some other issues were caused by a change in loompy v2.0 relative to v1.1.0. @gioelelm is currently fixing these bugs, but in the meantime, you should be able to use loompy 1.1.0 as before:

```
pip uninstall loompy
pip install loompy==1.1.0
```

Let me know if this works for you.

**Comment by gioelelm** [comment]
`v0.13.2` is an attempt to solve this and other bugs related to `loompy2` upgrade. Try upgrading `velocyto` and please report back if you encounter other errors.

**Comment by goldfish500** [comment]
Thanks! I just installed v0.13.2 but the error still exists. Should I completely reinstall it?

I used this command to update:
./pip install -U --no-deps velocyto
...
Successfully built velocyto
Installing collected packages: velocyto
  Found existing installation: velocyto 0.13.1
    Uninstalling velocyto-0.13.1:
      Successfully uninstalled velocyto-0.13.1
Successfully installed velocyto-0.13.2

After running the same command, I got additional error while the previous one still appeared. 

...
2018-01-25 09:15:10,369 - DEBUG - Counting done!
2018-01-25 09:15:10,382 - DEBUG - Generating output file /pathtocellranger/count-WT/velocyto/count-WT.loom
2018-01-25 09:15:10,382 - DEBUG - Collecting row attributes
2018-01-25 09:15:10,500 - DEBUG - Generating data table
2018-01-25 09:15:11,695 - DEBUG - Writing loom file
Traceback (most recent call last):
  File "/usr/home/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 222, in _run
    ds = loompy.create(filename=outfile, matrix=total, row_attrs=ra, col_attrs=ca, dtype="float32")
TypeError: create() got an unexpected keyword argument 'matrix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/home/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 100, in run10x
    samtools_memory=samtools_memory, additional_ca=additional_ca)
  File "/usr/home/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 235, in _run
    ds.attrs["velocyto.__version__"] = vcy.__version__
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by gioelelm** [comment]
Sorry again for this bug, but I did not prepare for the loompy2 API changes. I tried to fix the problem in v0.13.3 that is going to be available on pypi in few seconds. 
3...
2...
1...

**Comment by gioelelm** [comment]
Also notice that in this case, while the program terminates abruptly the file is generated nevertheless.

**Comment by goldfish500** [comment]
Thanks I could get the loom file now.
