### ISSUE TITLE
Compatible with C1 (Fluidigm) read data from SRA??

### ISSUE THREAD

**Issue by topherconley** [velocyto-team/velocyto.py#51]
Hi, 

I have extensively read the documentation and still have questions: 

+ Could you confirm alignments of C1 data (Fluidigm) is valid input to  Velocyto's `run` stage? 
+ Further, I have no valid cell barcodes available to me from the SRA sample FASTQs (short read archive). I don't  think that will be a problem, even though you warn against this. 
+ Please confirm the "ValidatedIntrons10X" logic option (default) is still appropriate for handling C1 data, in spite of the fact that it is not a Drop-Seq based technology? 

Thanks!

**Comment by gioelelm** [comment]
Hi,

> Could you confirm alignments of C1 data (Fluidigm) is valid input to Velocyto's run stage?

I have never tested with C1/SMART (only with C1/STRT) but analysis should be similar to SmartSeq2 (that is working) if I remember correctly. If that the case then you need to use the dev branch code and some flags (``-c``, ``-U``) need to be set. This is not fully documented yet and it will be released in a matter of days. The next release will include  a ``runC1``, right now we have a ``runSmartSeq2`` command.
Anyways, I will be running some tests with C1/SMART in the next weeks and add full support.

> Further, I have no valid cell barcodes available to me from the SRA sample FASTQs (short read archive). I don't think that will be a problem, even though you warn against this.

Yes you are right. For a situation like C1 or SmartSeq2 this is not a problem. bam files are already demultiplexed by barcode. In 10X or other droplet based techniques there are thousands of false positive/low counts beads ( with ~20 total molecules) those, if not masked, would end up in the final table making it huge.

> Please confirm the "ValidatedIntrons10X" logic option (default) is still appropriate for handling C1 data, in spite of the fact that it is not a Drop-Seq based technology?

``SmartSeq2`` Logic would be the more appropriate.

Sorry for the incompleteness but we are still in some kind of transition from a alpha/beta version to something definitive. We are also improving the confidence of the estimates and I expect the software to improve accuracy by dealing with some corner cases in the next few weeks.

**Comment by topherconley** [comment]
Thanks! I will let you know if I run into any relevant issues.

**Comment by topherconley** [comment]
Hi, 

I successfully installed the development version of velocyto with conda through the following dev_velocyto.yml file. 

> name: dev_velocyto
   channels:
    - javascript
  dependencies:
    - python=3.6   
    - numpy 
    - scipy
    - cython 
    - numba
    - matplotlib
    - scikit-learn
    - h5py
    - click
    - pip:
      - "--editable=git+https://github.com/velocyto-team/velocyto.py.git#egg=velocyto.py"

After creating and activating the environment

```
conda env create -f dev_velocyto.yml 
conda activate dev_velocyto
python
```

I get the following error from `import velocity`

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/u0672406/conda_env_files/src/velocyto.py/velocyto/__init__.py", line 15, in <module>
    from .analysis import VelocytoLoom, scatter_viz, ixs_thatsort_a2b, load_velocyto_hdf5
  File "/home/u0672406/conda_env_files/src/velocyto.py/velocyto/analysis.py", line 1936, in <module>
    colors20 = np.vstack((plt.cm.Vega20b(np.linspace(0., 1, 20))[::2], plt.cm.Vega20c(np.linspace(0, 1, 20))[1::2]))
AttributeError: module 'matplotlib.cm' has no attribute 'Vega20b'

Any suggestions?

**Comment by topherconley** [comment]
Should I instead just use the `velocyto.R::velocyto.R::read.smartseq2.bams` function? Will that work instead?

**Comment by gioelelm** [comment]
Sorry for not noticing the continuation of this issue earlier.
This problem is solved installing the from `dev` branch.

**Comment by gioelelm** [comment]
I apologize but I had not time to test the Fluidigm C1/SMART chemistry. I never analysed that chemistry myself actually, is there a significance difference in the bam file format and content from what one usually have for SmartSeq2? Or any difference that would require a different logic? As far as I understand there shouldn't be any major difference. If that is so then ``runSmartSeq2 `` should work of out the box.

**Comment by gioelelm** [comment]
Should I consider this a closed issue?

**Comment by benslack19** [comment]
Hi Velocyto team,

Thanks for making this package and for the responsiveness here on GitHub. I'm seeing some errors that are similar to things that others have posted like [here](https://github.com/velocyto-team/velocyto.py/issues/99), [here](https://github.com/velocyto-team/velocyto.py/issues/97) and this thread. I'm trying to follow some suggestions but still running into an error. I'm running C1 SMARTer chemistry so there are no UMIs.

Velocyto version: 0.17.13

Command:
`velocyto run_smartseq2 $BAM /home/singlecell/refs/gtf/Homo_sapiens.GRCh38.94.gtf`

Error section of output:
`2018-10-02 15:32:09,803 - DEBUG - Read first 0 million reads
Traceback (most recent call last):
  File "/home/singlecell/anaconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/home/singlecell/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/singlecell/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/singlecell/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/singlecell/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/singlecell/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/singlecell/anaconda3/lib/python3.6/site-packages/velocyto/commands/run_smartseq2.py", line 71, in run_smartseq2
    samtools_memory=1, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/home/singlecell/anaconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 229, in _run
    results = exincounter.count(bamfile_cellsorted, multimap=multimap)  # NOTE: we would avoid some millions of if statements evalution if we write two function count and count_with output
  File "/home/singlecell/anaconda3/lib/python3.6/site-packages/velocyto/counter.py", line 754, in count
    for r in self.iter_alignments(bamfile, unique=not multimap):
  File "/home/singlecell/anaconda3/lib/python3.6/site-packages/velocyto/counter.py", line 256, in iter_alignments
    if unique and read.get_tag("NH") != 1:
  File "pysam/libcalignedsegment.pyx", line 2392, in pysam.libcalignedsegment.AlignedSegment.get_tag
  File "pysam/libcalignedsegment.pyx", line 2434, in pysam.libcalignedsegment.AlignedSegment.get_tag
KeyError: "tag 'NH' not present"`

I'm guessing you would ask about the BAM file so here it is:
`$SAMTOOLS view $BAMsorted | head`

output:
`M02294:378:000000000-BFB2P:1:1107:27209:11999   99      NM_001087       943     100     72M     =       1107    236     GTTCCTTTCAGTACATGGATAGGGCTTCCCTGCTTCAGGTCCCAAATCCTGATGGTCCCATCTTCATAGCCT        CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG        XA:i:1  MD:Z:2C69       NM:i:1  ZW:f:1
M02294:378:000000000-BFB2P:1:1111:22606:4490    99      NM_001087       1006    100     72M     =       1051    118     TCTAAGCCTACCACAGCTCTCTTCCCATCAGGGAGGACTCGGCCACAGGTGGCTGGGCAGTTGGGACCCTGG        CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG        XA:i:2  MD:Z:2A0T68     NM:i:2  ZW:f:1
M02294:378:000000000-BFB2P:1:2101:11803:4213    99      NM_001087       1006    100     72M     =       1051    118     TCTAAGCCTACCACAGCTCTCTTCCCATCAGGGAGGACTCGGCCACAGGTGGCTGGGCAGTTGGGACCCTGG        CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG        XA:i:2  MD:Z:2A0T68     NM:i:2  ZW:f:1
M02294:378:000000000-BFB2P:1:1111:22606:4490    147     NM_001087       1051    100     73M     =       1006    -118    CAGGTGGCTGGGCAGTTGGGACCCTGGAAGGTCTTGCAGTCACCATTCGGGACTTTCCACATCCAGGTGTTGC       GGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCC       XA:i:0  MD:Z:73 NM:i:0  ZW:f:1
M02294:378:000000000-BFB2P:1:2101:11803:4213    147     NM_001087       1051    100     73M     =       1006    -118    CAGGTGGCTGGGCAGTTGGGACCCTGGAAGGTCTTGCAGTCACCATTCGGGACTTTCCACATCCAGGTGTTGC       GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCC       XA:i:0  MD:Z:73 NM:i:0  ZW:f:1
M02294:378:000000000-BFB2P:1:1107:27209:11999   147     NM_001087       1107    100     72M     =       943     -236    CCACATCCAGGTGTTGCCGTCAGCTGTGCCCGCCAACAGGACAGGTGCCCGAGGATGCCACTCCATCCACTC        GGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCC        XA:i:0  MD:Z:72 NM:i:0  ZW:f:1
M02294:378:000000000-BFB2P:1:1103:9435:17386    99      NM_001605       408     100     72M     =       640     305     TGCCTGTGGCCTGTGCAGACACATCCTTGCCACCACCTTTACCGTCCATCAAGCCTGACACCTGCTGCACCC        CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG        XA:i:0  MD:Z:72 NM:i:0  ZW:f:1
M02294:378:000000000-BFB2P:1:1103:9435:17386    147     NM_001605       640     100     73M     =       408     -305    GCCGCTCTCCATCTCCAGGATGACAAGAGGCTGGTTGGGGTTGCTGTCGATGAACTGCTTCGTCTTCTCTAAC       GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCC       XA:i:0  MD:Z:73 NM:i:0  ZW:f:1
M02294:378:000000000-BFB2P:1:1108:16377:3308    99      NM_001605       2159    100     72M     =       2205    119     TCTCCCAGGGACTGGACGACAACATCCACTAACGTAGCAAAGAAGCCCCTGCTGGCATTGAGCTTTTCATGG        CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG        XA:i:0  MD:Z:72 NM:i:0  ZW:f:1
M02294:378:000000000-BFB2P:1:2114:22144:16145   99      NM_001605       2159    100     72M     =       2205    119     TCTCCCAGGGACTGGACGACAACATCCACTAACGTAGCAAAGAAGCCCCTGCTGGCATTGAGCTTTTCATGG        CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGG        XA:i:0  MD:Z:72 NM:i:0  ZW:f:1`

I appreciate any assistance.

Best,
Ben

**Comment by benslack19** [comment]
Hi @gioelelm and @topherconley , I'm just curious if you had any tips on my case. I'd greatly appreciate any assistance. Do you see anything weird about my environment or BAM? Thank you so much.

Best,
Ben

**Comment by livnatje** [comment]
Hi Velocyto team,

Thanks for making the code available! I managed to run it on 10x data, and the results are super interesting. But on smart-seq data I get this error: "KeyError: "tag 'NH' not present", which was also reported here before. Any ideas?

Thanks!
Livnat

**Comment by cap76** [comment]
Having same problem at the moment ... did you figure out a solution?
