### ISSUE TITLE
AttributeError: module 'matplotlib.cm' has no attribute 'Vega20b'

### ISSUE THREAD

**Issue by evanbiederstedt** [velocyto-team/velocyto.py#54]
I'm having some problems getting velocyto installed properly with python-3.6.1. The package appears to install properly, but doesn't import. I get the following matplotlib issue:

```
Successfully installed velocyto
You are using pip version 9.0.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@mskilab02 velocyto.py]# python
Python 3.6.1 (default, Mar 19 2018, 15:38:01)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import velocyto
/path/software/python-3.6.1/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/Software/src/velocyto.py/velocyto/__init__.py", line 15, in <module>
    from .analysis import VelocytoLoom, scatter_viz, ixs_thatsort_a2b, load_velocyto_hdf5
  File "/path/Software/src/velocyto.py/velocyto/analysis.py", line 1936, in <module>
    colors20 = np.vstack((plt.cm.Vega20b(np.linspace(0., 1, 20))[::2], plt.cm.Vega20c(np.linspace(0, 1, 20))[1::2]))
AttributeError: module 'matplotlib.cm' has no attribute 'Vega20b'
```

Loompy appears to have installed correctly though...
```

>>> import loompy
/path/software/python-3.6.1/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```

Any troubleshooting tips?  Should I be trying a different python? Thanks for any help.

**Comment by gioelelm** [comment]
This was solved in https://github.com/velocyto-team/velocyto.py/issues/52 

If the suggestion there does not work for you. Just install from source the dev version

**Comment by evanbiederstedt** [comment]
Hi @gioelelm 

Thanks for the help. 

It looks like that solved the issue. 

```
Python 3.6.3 (default, Mar 21 2018, 17:01:44) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import velocyto         
/gpfs/commons/home/biederstedte-934/software/Python-3.6.3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> 
```

A slight favor: could you make it more clear on the README here (and on the website) that users should use`matplotlib==2.1.0`. It might be good to put this in a common troubleshooting FAQ as it has come up more than once. 

Otherwise, thanks for the speedy help! I appreciate it

**Comment by gioelelm** [comment]
New version compatible with the latest matplotlib will be released shortly.
