### ISSUE TITLE
Issue with ERCC spike-ins in the GTF when using run_smartseq2

### ISSUE THREAD

**Issue by danielseaton** [velocyto-team/velocyto.py#57]
I ran this command, for SmartSeq2 data:

```
velocyto run_smartseq2 -o ./velocyto star/22606_3#7*/22606_3#7*.2pass.Aligned.sortedByCoord.dedup.bam $GTF
```

I was using a bam file with some reads mapped to ERCC spike-ins, so I have a GTF file with ERCC transcripts described like this (for example):

```
ERCC-00157	ERCC	exon	1	1019	0.000000	+	.	gene_id "ERCC-00157"; transcript_id "DQ839618";
ERCC-00158	ERCC	exon	1	1027	0.000000	+	.	gene_id "ERCC-00158"; transcript_id "DQ516795";
ERCC-00160	ERCC	exon	1	743	0.000000	+	.	gene_id "ERCC-00160"; transcript_id "DQ883658";
ERCC-00162	ERCC	exon	1	523	0.000000	+	.	gene_id "ERCC-00162"; transcript_id "DQ516750";
ERCC-00163	ERCC	exon	1	543	0.000000	+	.	gene_id "ERCC-00163"; transcript_id "DQ668359";
ERCC-00164	ERCC	exon	1	1022	0.000000	+	.	gene_id "ERCC-00164"; transcript_id "DQ516779";
ERCC-00165	ERCC	exon	1	872	0.000000	+	.	gene_id "ERCC-00165"; transcript_id "DQ668363";
ERCC-00168	ERCC	exon	1	1024	0.000000	+	.	gene_id "ERCC-00168"; transcript_id "DQ516776";
ERCC-00170	ERCC	exon	1	1023	0.000000	+	.	gene_id "ERCC-00170"; transcript_id "DQ516773";
ERCC-00171	ERCC	exon	1	505	0.000000	+	.	gene_id "ERCC-00171"; transcript_id "DQ854994";
```

And this seems to cause an error:

```
2018-03-25 21:03:50,535 - INFO - Load the annotation from /hps/nobackup/stegle/datasets/references/human/GRCh37/gencode.v19.annotation_ERCC.gtf
2018-03-25 21:03:59,379 - DEBUG - Parsing Chromosome ERCC-00002 strand + [line 0]
Traceback (most recent call last):
  File "/nfs/software/stegle/users/dseaton/conda-envs/velocyto_env/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto', 'console_scripts', 'velocyto')()
  File "/nfs/software/stegle/users/dseaton/conda-envs/velocyto_env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/software/stegle/users/dseaton/conda-envs/velocyto_env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nfs/software/stegle/users/dseaton/conda-envs/velocyto_env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/software/stegle/users/dseaton/conda-envs/velocyto_env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/software/stegle/users/dseaton/conda-envs/velocyto_env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nfs/software/stegle/users/dseaton/python_packages/velocyto.py/velocyto/commands/run_smartseq2.py", line 72, in run_smartseq2
    samtools_memory=1, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/nfs/software/stegle/users/dseaton/python_packages/velocyto.py/velocyto/commands/_run.py", line 180, in _run
    annotations_by_chrm_strand = exincounter.read_transcriptmodels(gtffile)
  File "/nfs/software/stegle/users/dseaton/python_packages/velocyto.py/velocyto/counter.py", line 467, in read_transcriptmodels
    trname = regex_trname.search(tags).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

I got around this no problem by just removing the ERCC chromosomes from the gtf, but thought maybe this would be an issue for others, since I think quite a few people have used ERCC spike-ins with the SmartSeq2 protocol.

**Comment by gioelelm** [comment]
Sorry for the late reply.
velocyto is looking for the following standard entry in the gtf files:
```
transcript_id, transcript_name, gene_id, gene_name, exon_number
```
This info should be contained in a gtf file formated according GENCODE standard. However I see the issue here. I could easily catch this error and return some default not informative value like

```
transcript_id="NoId", transcript_name="NoName", gene_id="NoId", gene_name="NoName", exon_number="1"
```
However I am afraid that this sometimes will lead to not accurate with uncorrectly formatted gtf files to some weird errors.

I think the best solution is to still throw an error and return a more informative error message. (Even though here the second last line was kind of clear that the `regex_trname` was failing, but I can try to be even more explicit)

**Comment by gioelelm** [comment]
Note that now velocyto will be a little more forgiving and if transcript_name or exon_number are not specified no error will be thrown.

**Comment by gioelelm** [comment]
Velocyto now also prints the line of the gtf that cause the error, helping the user to debug. I still think that too much "secret patching" of the gtf data where the user is not aware of what is going on, should be avoided, because it might generate anomalies difficult to trace back.
