### ISSUE TITLE
subprocess.CalledProcessError returned non-zero exit status 1.

### ISSUE THREAD

**Issue by harmbrugge** [velocyto-team/velocyto.py#59]
I've installed velocyto.py from source in a cluster environment running on CentOS (6.9).

Im trying to use the cli run command like so:
`velocyto run -b barcodes.tsv -o ~/output/ possorted_genome_bam.bam hg19.gtf`

Yielding the following error:
```
2018-04-05 16:20:21,604 - DEBUG - No SAMPLEID specified, the sample will be called possorted_genome_bam_5N1Y2
2018-04-05 16:20:21,605 - DEBUG - Using logic: Default
2018-04-05 16:20:21,612 - DEBUG - Read 4913 cell barcodes from /target/gpfs2/groups/umcg-wijmenga/tmp02/projects/scRNAseq_10X_pilot/pilot4/pilot4_lane_2/outs/filtered_gene_bc_matrices/hg19/barcodes.tsv
2018-04-05 16:20:21,612 - DEBUG - Example of barcode: AAACCTGAGATGTGTA and cell_id: possorted_genome_bam_5N1Y2:AAACCTGAGATGTGTA-1
Traceback (most recent call last):
  File "./velocyto", line 11, in <module>
    load_entry_point('velocyto==0.13.8', 'console_scripts', 'velocyto')()
  File "/home/umcg-hbrugge/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/umcg-hbrugge/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/umcg-hbrugge/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/umcg-hbrugge/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/umcg-hbrugge/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/umcg-hbrugge/.local/lib/python3.6/site-packages/velocyto/commands/run.py", line 102, in run
    samtools_memory=samtools_memory, additional_ca=additional_ca)
  File "/home/umcg-hbrugge/.local/lib/python3.6/site-packages/velocyto/commands/_run.py", line 110, in _run
    mb_available = int(subprocess.check_output('grep MemAvailable /proc/meminfo'.split()).split()[1]) / 1000
  File "/apps/software/Python/3.6.3-foss-2015b/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/apps/software/Python/3.6.3-foss-2015b/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['grep', 'MemAvailable', '/proc/meminfo']' returned non-zero exit status 1.
```

Do you have any idea what might cause this issue?

**Comment by gioelelm** [comment]
Try to install from the dev branch, the bug should be solved.

Sorry if master branch is behind but until we uptate docs and notebooks I cannot make a new realease, it would be confusing.

**Comment by harmbrugge** [comment]
Thanks for the quick response again. The dev branch seems to be working.
