### ISSUE TITLE
run10x for non-model organism

### ISSUE THREAD

**Issue by cds1** [velocyto-team/velocyto.py#73]
Hello again, 
I wonder if you can help with this issue. I am trying to obtain a loom file from 10x data. I know the program runs well in human 10x data (tried and tested) but when I try to run it on a non-model organims I am working with, it gives me an error which I think it is to do with the type of annotation. I wonder if you could have a look at the error below? Have you seen this error before? I would be very greateful if you could help with this. 
Many thanks in advance and apologies for the many questions
PS: I am have also attached the velocyto log file. Hope you can see it

Cheers, Carmen

2018-05-16 20:42:58,966 - WARNING - The entry exon_number was not present in the gtf file. It will be infferred from the position.
2018-05-16 20:43:02,117 - DEBUG - Parsing Chromosome SM_V7_1 strand - [line 0]
2018-05-16 20:43:07,784 - DEBUG - Fixing corner cases of transcript models containg intron longer than 1000Kbp
/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 104, in run10x
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/velocyto/commands/_run.py", line 180, in _run
    annotations_by_chrm_strand = exincounter.read_transcriptmodels(gtffile)
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/velocyto/counter.py", line 512, in read_transcriptmodels
    tm.chop_if_long_intron()  # Change it in place
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/velocyto/transcript_model.py", line 93, in chop_if_long_intron
    long_feats = [i for i in self.list_features if len(i) > maxlen and i.kind == ord("i")]
  File "/nfs/users/nfs_m/my4/scratch/src/miniconda3/lib/python3.6/site-packages/velocyto/transcript_model.py", line 93, in <listcomp>
    long_feats = [i for i in self.list_features if len(i) > maxlen and i.kind == ord("i")]
ValueError: __len__() should return >= 0

[veloctyo.log](https://github.com/velocyto-team/velocyto.py/files/2012922/veloctyo.log)

**Comment by gioelelm** [comment]
The problem is related with the fact that one of your transcript models is not annotated correctly.

The error is basically saying: when doing end - start (+1, because of indexing conventions) I get a negative value.

In particular you probably have a transcript model exon structure spans different chromosomes or more general it implies that an intron has end_position > start_position, or something like that. This might arise by not appropriately giving unique transcript id names for example. It surely would be avoided if following gencode instruction formatting [gtf files](https://www.gencodegenes.org/gencodeformat.html) end icluding appropriatelly numbered exons.
Further information on the input requirements [here](http://velocyto.org/velocyto.py/tutorial/cli.html#requirements-on-the-input-files).

**Comment by gioelelm** [comment]
I recommend inspecting the genome annotation using IGV, if it can load everything correctly and nothing looks weird at a quick inspection (e.g. MBs long introns) it is a first good sign and a good enough evidence that the problem is on my side and I should test more those lines of code.

**Comment by cds1** [comment]
Great, thanks. I am trying a few things now and will add that to the list. Thanks a lot. I think it's not on your side because it runs well with other human data. We do have things like split exons, micro exons, very long and very short introns. I thought maybe those were giving problems.  IGV is a great idea.

**Comment by cds1** [comment]
Hello, I found regions where end-start =0 so I put those in the mask file (albeit still getting errors) such as: 
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/commands/run10x.py", line 81, in run10x
    os.path.normcase("outs/filtered_gene_bc_matrices/*/barcodes.tsv")))[0]
IndexError: list index out of range
So I guess as a general rule, if I find annotations that velocyto does not like, can I input those in a mask file or do I need to re-run the cell ranger software with a new gtf file excluding those regions? Thanks again

**Comment by cds1** [comment]
Thanks. It was a problem with the gtf as you said. I get error somewhere else which I have posted in another post because it is exactly the same. Hope this is ok.
Many thanks as usual.

**Comment by Bio-MingChen** [comment]
I recently encountered the same error in my gtf of non-model organism , the reason is exons' coordinates have overlap for the same transcript resulting in a intron with length less than 0. just look at the image below:
![image](https://user-images.githubusercontent.com/16701253/116640885-2411b800-a99e-11eb-86c9-1345ac07bec3.png)

**Comment by wuzhigui** [comment]
I have got the best way to solve this error !
`sed -n '/exon/p' genes_filter1.gtf | sed -n '/gene_name/p'  >  GRCh38_rmsk.gtf`
'genes_filter1.gtf' is the gtf file you have used to run 10X cellranger .
Then 
`velocyto run -b /barcode/${i}.txt -@ 10 --samtools-memory 1024 --sampleid ${i} -o ./out ${i}_new.bam  GRCh38_rmsk.gtf`
thanks!
