### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by oliviamr** [velocyto-team/velocyto.py#76]
Hi, 

I am getting the following error:

    dict_layers_columns[layer_name] = np.zeros(shape, dtype=vcy.LOOM_NUMERIC_DTYPE, order="C")
MemoryError

I am running the command for 10x: 
velocyto run10x -m ./mm10_rmsk.gtf ./10x-171031-27/ ./refdata-cellranger-mm10-1.2.0/genes/genes.gtf 

any clue as to why this error arise?
Thank you!
Olivia

**Comment by gioelelm** [comment]
Probably you are not specifying the valid barcodes list file and running
out of memory when trying to allocate the matrix, because there are
hundreds of thousands of barcodes in a typical dtoplet esperiment.

**Comment by oliviamr** [comment]
It is pointing into the right list of barcodes from what I see in the logs. Any other suggestion?

**Comment by gioelelm** [comment]
Were you running several processes ? Could it be that you actually just run
out of memory? How much memory your system has available?

Also could you attach the log?

**Comment by gioelelm** [comment]
Otherwise try to use 'run' instead of 'run10x' and specify the arguments
manually; if that works I can isolate the problem as coming from the
'run10x' specific code.

**Comment by oliviamr** [comment]
After running the different modes I still get the same error but I have been able to detect that is not able to execute the -t in the samtools sort command. My version of samtools 1.3 does not recognize -t but -T ...Would that be it?

**Comment by cds1** [comment]
Actually I was about to ask you the same thing so I have added it to this post. Looking at the source code, I think it is trying to make a matrix of all the zeros and it is running out of memory. 

Actual error

  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/commands/_run.py", line 223, in _run
    results = exincounter.count(bamfile_cellsorted, multimap=multimap)  # NOTE: we would avoid some millions of if statements evalution if we write two function count and count_with output
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/counter.py", line 729, in count
    dict_layer_columns, list_bcs = self.count_cell_batch()
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/counter.py", line 813, in _count_cell_batch_stranded
    dict_layers_columns[layer_name] = np.zeros(shape, dtype=vcy.LOOM_NUMERIC_DTYPE, order="C")
MemoryError


I am doing 'run' instead of run10x. I am also pointing to the barcodes from the filtered folder. You can see I am giving it a fair amount of memory and I should also point out that I have run it with 170,000MB so I am not sure it is actually a memory issue. Could this be a python thing? Would this be related to something in the gtf. I have checked my gtf and it seems ok. I am not sure how to debug this. 

Resource usage summary:

    CPU time :                                   14007.15 sec.
    Max Memory :                                 18663 MB
    Average Memory :                             2685.89 MB
    Total Requested Memory :                     64000.00 MB
    Delta Memory :                               45337.00 MB
    Max Swap :                                   264590 MB
    Max Processes :                              3
    Max Threads :                                5


Many thanks in advance, 

Carmen

**Comment by cds1** [comment]
Thanks for letting me know. Glad your sorted the problem. I sorted separately with samtools 1.6 and it is able to detect the file. Still giving me error though so it may be something different

**Comment by cds1** [comment]
So, I did what you mentioned but I still get a new error. I guess new errors at least mean some sort of advancing. Also, it is failing right at the end. It writes a loom file but with nothing on it
8 -rw-r--r-- 1 cds1 team 4824 May 25 20:34 D7119553.loom

Thanks in advance!

[bam_sort_core] merging from 96 files and 16 in-memory blocks...
Traceback (most recent call last):
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/velocyto/commands/_run.py", line 280, in _run
    ds = loompy.create(filename=outfile, matrix=total, row_attrs=ra, col_attrs=ca, dtype="float32")
TypeError: create() got an unexpected keyword argument 'matrix'

**Comment by gioelelm** [comment]
There is something extremely weird here, I don't understand it:
This error should be currently catched and it is related with maintaining compatibility with old and newer versions of loompy.

The source-code of the part of the code that throws the error is:


```
    try:
        ds = loompy.create(filename=outfile, matrix=total, row_attrs=ra, col_attrs=ca, dtype="float32")
        for layer_name in logic_obj.layers:
            ds.set_layer(name=layer_name, matrix=layers[layer_name], dtype=vcy.LOOM_NUMERIC_DTYPE)
        ds.attrs["velocyto.__version__"] = vcy.__version__
        ds.attrs["velocyto.logic"] = logic
        ds.close()
    except TypeError:
        # If user is using loompy2
        tmp_layers = {"": total.astype("float32", order="C", copy=False)}
        tmp_layers.update({layer_name: layers[layer_name].astype(vcy.LOOM_NUMERIC_DTYPE, order="C", copy=False) for layer_name in logic_obj.layers})
        loompy.create(filename=outfile, layers=tmp_layers, row_attrs=ra, col_attrs=ca, file_attrs={"velocyto.__version__": vcy.__version__, "velocyto.logic": logic})
    logging.debug("Terminated Succesfully!")
```
As you can see the error should not be thrown.
Are you using a recent version of velocyto?

**Comment by cds1** [comment]
@gioelelm thanks for all your help. Finally I get a job with "Successfully completed" on it.  I think the fact that it seemed weird to you made me doublecheck that everything was properly installed. The programme was installed in our central system, so I used virtual environment and re-installed everything. I think using velocyto has been a masterclass of system debugging for me.
I would say that in case someone reads this:
1) It seems there are important things like having samtools 1.6
2)Check GTF (seems obvious but up until using your programme I thought the GTF I was using was fine and it wasn't)
3)Make sure Loompy is installed properly. I installed loompy before installing velocyto
Thanks again and hopefully no more issues with velocyto for a long time

**Comment by denvercal1234GitHub** [comment]
@cdsoria -- When you said you installed everything in your virtual environment created within the cluster, what did you have to reinstall? samtools, python, velocyto, etc.? Thank you so much. For me, I activate the virtual environment, module load python and module samtools then run velocyto, but it gave me errors as described in #320.

**Comment by cdiaz45** [comment]
Hi @denvercal1234GitHub so this info I am giving you may be out of date as it was a few years back. Apart from from checking your gtf does not have duplicated entries or is a bit funny going on (like mine), and your files are fine in general. What I did was:
Velocyto
 
1) install miniconda/anaconda with python 3.6
2)Make a virtual environment and install packages
 
a) conda install numpy scipy cython numba matplotlib scikit-learn h5py click loompy
b) pip install velocyto
 
3) Run but before check:
 
a) outs folder with _log file containing the following statement: Pipestance completed successfully!
b) samtools-1.6 in your path
 
velocyto run --samtools-memory 1024 --samtools-threads 4 -b /lustre/barcodes.tsv /lustre/possorted_genome_bam.bam /nfs/genes.gtf
 
4) After loom file, start the the analysis

Let me know if it works. if not, I can ask around to try and help you. 
Good luck.

**Comment by cdiaz45** [comment]
Also @denvercal1234GitHub, After these changes, I tried it in their data first if I remember correctly to check it ran, and then on mine.

**Comment by denvercal1234GitHub** [comment]
@cdiaz45 -- Thank you for your response. Do I need to put all the files (the bam file, the genes.gtf, the mm10_rmsk.gtf and the barcode.csv in the same directory? Or, I can just put the full path to them in the run command?

**Comment by cdiaz45** [comment]
Hi, I believe the path will do. The paths in my example look the same but that's because I deleted details of the group details and project for confidentiality etc.

**Comment by denvercal1234GitHub** [comment]
Thanks @cdiaz45. I will now also include in the run command the cell barcode file (barcodes.tsv) for the sample that I took directly from /run_count_R5neg/count_T230_CD8R5neg_R1/outs/filtered_feature_bc_matrix directory. 

Btw, I understand that cellranger count will already sort the bam file by position, that is why we have the run_count_R5neg/count_T230_CD8R5neg_R1/outs/possorted_genome_bam.bam file. But, did you and if so how did you check whether it fulfill points 2, 3, and 4 below? I plan to follow the guides here at http://quinlanlab.org/tutorials/samtools/samtools.html

2. Represents either a single sample (multiple cells prepared using a certain barcode set in a single experiment) or single cell.
3. Contain an error corrected cell barcodes as a TAG named CB or XC.
4. Contain an error corrected molecular barcodes as a TAG named UB or XM.

**Comment by denvercal1234GitHub** [comment]
@cdiaz45 - I tried again as described in #320 just now, but it failed again... 🥵
