### ISSUE TITLE
All chunk dimensions must be positive

### ISSUE THREAD

**Issue by qinzhu** [velocyto-team/velocyto.py#92]
Hi,

I ran into a bug when running velocyto. The bug occurs during writing the loom file, and seems to be associated with loompy/h5py.

Here's the traceback

```
Traceback (most recent call last):
  File "/kimdata/zhuqin/HSC/scAtlas/hsc_preprocess/velocyto/velocyto.py/velocyto/commands/_run.py", line 280, in _run
    ds = loompy.create(filename=outfile, matrix=total, row_attrs=ra, col_attrs=ca, dtype="float32")
TypeError: create() got an unexpected keyword argument 'matrix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuqin/anaconda/envs/py36/bin/velocyto", line 11, in <module>
    load_entry_point('velocyto', 'console_scripts', 'velocyto')()
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/kimdata/zhuqin/HSC/scAtlas/hsc_preprocess/velocyto/velocyto.py/velocyto/commands/run.py", line 113, in run
    samtools_memory=samtools_memory, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/kimdata/zhuqin/HSC/scAtlas/hsc_preprocess/velocyto/velocyto.py/velocyto/commands/_run.py", line 293, in _run
    loompy.create(filename=outfile, layers=tmp_layers, row_attrs=ra, col_attrs=ca, file_attrs={"velocyto.__version__": vcy.__version__, "velocyto.logic": logic})
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/loompy/loompy.py", line 883, in create
    raise ve
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/loompy/loompy.py", line 864, in create
    ds.layer[key] = vals
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/loompy/layer_manager.py", line 85, in __setitem__
    return self.__setattr__(name, val)
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/loompy/layer_manager.py", line 119, in __setattr__
    compression_opts=2
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/h5py/_hl/group.py", line 106, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 120, in make_new_dset
    shuffle, fletcher32, maxshape, scaleoffset)
  File "/home/zhuqin/anaconda/envs/py36/lib/python3.6/site-packages/h5py/_hl/filters.py", line 175, in generate_dcpl
    plist.set_chunk(chunks)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5p.pyx", line 427, in h5py.h5p.PropDCID.set_chunk
ValueError: All chunk dimensions must be positive (all chunk dimensions must be positive)
```

The first one seem to be loompy 2 issue but is correctly handled, but the second "dimension positive" bug is breaking my run. Could you help? 

Thanks a lot!

**Comment by gioelelm** [comment]
I don't recognize the error at all. Was velocyto working for you before?
(thinking ir might be an API change from hdf5) Are you using conda to
install everything. It seems an error coming from loompy interface with
h5py.

Gioele

**Comment by qinzhu** [comment]
Thanks for the quick reply! I was new to velocyto so just followed the installation procedure listed on the webpage. 
Below is my conda list:

```
# packages in environment at /home/zhuqin/anaconda/envs/py36:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.10           py36h306e16b_0  
anaconda                  custom           py36hbbc8b67_0  
anaconda-client           1.6.14                   py36_0  
anaconda-project          0.8.2            py36h44fb852_0  
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.3                    py36_0  
astropy                   3.0.2            py36h3010b51_1  
attrs                     18.1.0                   py36_0  
babel                     2.5.3                    py36_0  
backcall                  0.1.0                    py36_0  
backports                 1.0              py36hfa02d7e_1  
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
beautifulsoup4            4.6.0            py36h49b8c8c_1  
bitarray                  0.8.1            py36h14c3975_1  
bkcharts                  0.2              py36h735825a_0  
blas                      1.1                    openblas    conda-forge
blaze                     0.11.3           py36h4e06776_0  
bleach                    2.1.3                    py36_0  
blosc                     1.14.3               hdbcaa40_0  
bokeh                     0.12.16                  py36_0  
boto                      2.48.0           py36h6e4cd66_1  
bottleneck                1.2.1            py36haac1ea0_0  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.12              h8948797_3  
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5           py36h9745a5d_0  
chardet                   3.0.4            py36h0f667ec_1  
click                     6.7                      py36_0  
cloudpickle               0.5.3                    py36_0  
clyent                    1.2.2            py36h7e57e65_1  
colorama                  0.3.9            py36h489cec4_0  
contextlib2               0.5.5            py36h6c84a62_0  
cryptography              2.2.2            py36h14c3975_0  
curl                      7.60.0               h84994c4_0  
cycler                    0.10.0           py36h93f1223_0  
cython                    0.28.3           py36h14c3975_0  
cytoolz                   0.9.0.1          py36h14c3975_0  
dask                      0.17.5                   py36_0  
dask-core                 0.17.5                   py36_0  
datashape                 0.5.4            py36h3ad6b5c_0  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py36_0  
distributed               1.21.8                   py36_0  
docutils                  0.14             py36hb0f60f5_0  
entrypoints               0.2.3            py36h1aec115_2  
et_xmlfile                1.0.1            py36hd6bccc3_0  
expat                     2.2.5                he0dffb1_0  
fastcache                 1.0.2            py36h14c3975_2  
filelock                  3.0.4                    py36_0  
flask                     1.0.2                    py36_1  
flask-cors                3.0.4                    py36_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_0  
fribidi                   1.0.4                h14c3975_0  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.3.0            py36h14c3975_0  
glib                      2.56.1               h000015b_0  
glob2                     0.6              py36he249c77_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36hc8893dd_2  
graphite2                 1.3.11               h16798f4_2  
greenlet                  0.4.13           py36h14c3975_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.7.1                    py36_2    conda-forge
harfbuzz                  1.7.6                hec2c2bc_3  
hdf5                      1.10.1                        2    conda-forge
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.6              py36h82fb2a8_1  
imageio                   2.3.0                    py36_0  
imagesize                 1.0.0                    py36_0  
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py36_0  
ipython                   6.4.0                    py36_0  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.2.1                    py36_0  
isort                     4.3.4                    py36_0  
itsdangerous              0.24             py36h93cc618_1  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4                      py36_0  
jedi                      0.12.0                   py36_1  
jinja2                    2.10             py36ha16c418_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0            py36h006f8b5_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.4.0            py36h7c827e3_0  
jupyterlab                0.32.1                   py36_0  
jupyterlab_launcher       0.10.5                   py36_0  
kiwisolver                1.0.1            py36h764f252_0  
lazy-object-proxy         1.3.1            py36h10fcdad_0  
libcurl                   7.60.0               h1ad7b7a_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.34               hb9fc6fc_0  
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he85c1e1_1  
libtool                   2.4.6                h544aabb_3  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
libxslt                   1.1.32               h1312cb7_0  
llvmlite                  0.24.0           py36hdbcaa40_0  
locket                    0.2.0            py36h787c0ad_1  
loompy                    2.0.9                    py36_0    bioconda
lxml                      4.2.1            py36h23eabaa_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.0              py36hd9260cd_1  
matplotlib                2.2.2            py36hb69df0a_2  
mccabe                    0.6.1            py36h5ad9710_1  
mistune                   0.8.3            py36h14c3975_1  
mkl                       2018.0.3                      1  
mkl-service               1.1.2            py36h17a0993_4  
mkl_fft                   1.0.1            py36h3010b51_0  
mkl_random                1.0.1            py36h629b387_0  
more-itertools            4.1.0                    py36_0  
mpc                       1.0.3                hec55b23_5  
mpfr                      3.1.5                h11a74b3_2  
mpmath                    1.0.0            py36hfeacd6b_2  
msgpack                   0.5.6                     <pip>
msgpack-python            0.5.6            py36h6bb024c_0  
multipledispatch          0.5.0                    py36_0  
nbconvert                 5.3.1            py36hb41ffb7_0  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.1                  hf484d3e_0  
networkx                  2.1                      py36_0  
nltk                      3.3.0                    py36_0  
nose                      1.3.7            py36hcdf7029_2  
notebook                  5.5.0                    py36_0  
numba                     0.39.0           py36h04863e7_0  
numexpr                   2.6.5            py36h7bf3b9c_0  
numpy                     1.14.0          py36_blas_openblas_200  [blas_openblas]  conda-forge
numpy-base                1.14.3           py36h0ea5e3f_1  
numpydoc                  0.8.0                    py36_0  
odo                       0.5.1            py36h90ed295_0  
olefile                   0.45.1                   py36_0  
openblas                  0.2.20                        8    conda-forge
openpyxl                  2.5.3                    py36_0  
openssl                   1.0.2o                        0    conda-forge
packaging                 17.1                     py36_0  
pandas                    0.23.0           py36h637b7d7_0  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py36ha6701b7_1  
pango                     1.42.1               h8589676_0  
parso                     0.2.0                    py36_0  
partd                     0.3.8            py36h36fd896_0  
patchelf                  0.9                  hf79760b_2  
path.py                   11.0.1                   py36_0  
pathlib2                  2.3.2                    py36_0  
patsy                     0.5.0                    py36_0  
pcre                      8.42                 h439df22_0  
pep8                      1.7.1                    py36_0  
pexpect                   4.5.0                    py36_0  
pickleshare               0.7.4            py36h63277f8_0  
pillow                    5.1.0            py36heded4f4_0  
pip                       10.0.1                   py36_0  
pixman                    0.34.0               hceecf20_3  
pkginfo                   1.4.2                    py36_1  
pluggy                    0.6.0            py36hb689045_0  
ply                       3.11                     py36_0  
prompt_toolkit            1.0.15           py36h17d85b1_0  
psutil                    5.4.5            py36h14c3975_0  
ptyprocess                0.5.2            py36h69acd42_0  
py                        1.5.3                    py36_0  
pycodestyle               2.4.0                    py36_0  
pycosat                   0.6.3            py36h0a5515d_0  
pycparser                 2.18             py36hf9f622e_1  
pycrypto                  2.6.1            py36h14c3975_8  
pycurl                    7.43.0.1         py36hb7f436b_0  
pyflakes                  1.6.0            py36h7bd6a15_0  
pygments                  2.2.0            py36h0d3125c_0  
pylint                    1.8.4                    py36_0  
pyodbc                    4.0.23           py36hf484d3e_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.9.2            py36h751905a_0  
pysam                     0.14.1                    <pip>
pysocks                   1.6.8                    py36_0  
pytables                  3.4.4                    py36_8    conda-forge
pytest                    3.5.1                    py36_0  
pytest-arraydiff          0.2                      py36_0  
pytest-astropy            0.3.0                    py36_0  
pytest-doctestplus        0.1.3                    py36_0  
pytest-openfiles          0.3.0                    py36_0  
pytest-remotedata         0.2.1                    py36_0  
python                    3.6.5                hc3d631a_2  
python-dateutil           2.7.3                    py36_0  
pytz                      2018.4                   py36_0  
pywavelets                0.5.2            py36he602eb0_0  
pyyaml                    3.12             py36hafb9ca4_1  
pyzmq                     17.0.0           py36h14c3975_0  
qt                        5.9.6                h52aff34_0  
qtawesome                 0.4.4            py36h609ed8c_0  
qtconsole                 4.3.1            py36h8f73b5b_0  
qtpy                      1.4.1                    py36_0  
readline                  7.0                  ha6073c6_4  
requests                  2.18.4           py36he2e5f8d_1  
rope                      0.10.7           py36h147e2ec_0  
ruamel_yaml               0.15.35          py36h14c3975_1  
scikit-image              0.13.1           py36h14c3975_1  
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.1.0           py36_blas_openblashd3ea46f_201  [blas_openblas]  conda-forge
seaborn                   0.8.1            py36hfad7ec4_0  
send2trash                1.5.0                    py36_0  
setuptools                39.1.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
singledispatch            3.4.0.3          py36h7a266c3_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0           py36h372c433_1  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1            py36h6febd40_0  
sortedcollections         0.6.1                    py36_0  
sortedcontainers          1.5.10                   py36_0  
sphinx                    1.7.4                    py36_0  
sphinxcontrib             1.0              py36h6d0f590_1  
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
spyder                    3.2.8                    py36_0  
sqlalchemy                1.2.7            py36h6b74fdf_0  
sqlite                    3.23.1               he433501_0  
statsmodels               0.9.0            py36h3010b51_0  
sympy                     1.1.1            py36hc6d1c1c_0  
tblib                     1.3.2            py36h34cf8b6_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h8cadb63_0  
tk                        8.6.7                hc745277_3  
toolz                     0.9.0                    py36_0  
tornado                   5.0.2                    py36_0  
traitlets                 4.3.2            py36h674d592_0  
typing                    3.6.4                    py36_0  
unicodecsv                0.14.1           py36ha668878_0  
unixodbc                  2.3.6                h1bed415_0  
urllib3                   1.22             py36hbe7ace6_0  
velocyto                  0.17.8                    <pip>
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
werkzeug                  0.14.1                   py36_0  
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.2.1                    py36_0  
wrapt                     1.10.11          py36h28b7045_0  
xlrd                      1.1.0            py36h1db9f0c_1  
xlsxwriter                1.0.4                    py36_0  
xlwt                      1.3.0            py36h7b00a1f_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                h439df22_0  
zict                      0.1.3            py36h3a3bf81_0  
zlib                      1.2.11               ha838bed_2
```

**Comment by gioelelm** [comment]
Try with reinstalling h5py with conda and loompy from source

**Comment by qinzhu** [comment]
Still the same. I'll perhaps try on another linux machine see if things works out. Will update once tested. Appreciate your help!

**Comment by qinzhu** [comment]
One thing I was not sure about when running with the advanced mode is the format of the barcode file. I have a list of barcodes which passed my cell filter so I just want to run velocyto on these. Is the below barcode format correct for input into velocyto? I wonder if wrong barcode file format could be the reason my run fails.

barcode.tsv:

```
"AAACCTGAGCGCCTCA-1"
"AAACCTGCAATGACCT-1"
"AAACCTGCACTTAACG-1"
"AAACCTGCAGTCAGCC-1"
"AAACCTGCATACTACG-1"
"AAACCTGCATGCGCAC-1"
"AAACCTGGTAGCTTGT-1"
"AAACCTGGTTGTGGCC-1"
"AAACCTGTCAAGCCTA-1"
"AAACCTGTCAGGCGAA-1"
"AAACCTGTCAGGTAAA-1"
"AAACCTGTCATTTGGG-1"
"AAACCTGTCTATCCTA-1"
"AAACCTGTCTTGACGA-1"
"AAACGGGAGGAGCGTT-1"
"AAACGGGCATTGAGCT-1"
"AAACGGGGTCTAGCCG-1"
```

**Comment by qinzhu** [comment]
Update: Appears it is associated with my barcode file, or me running velocyto using the customized mode. I ran the 10x mode and the program successfully finishes.

**Comment by gioelelm** [comment]
Can you specift the commands that you are using? Thanks

**Comment by qinzhu** [comment]
```
velocyto run -b barcode.tsv -@ 32 --samtools-memory 6000 -o testout -m mm10_rmsk.gtf test.bam refdata-cellranger-mm10-1.2.0/genes/genes.gtf
```
This is the command that did not work for me.

**Comment by qinzhu** [comment]
Just a follow up related question: Is there a way to specify a barcode list/filter criteria for the run10x pipeline? It seems currently velocyto uses the filtered_bc_matrix to determine which cell barcode to include in counting. However for my 10x run many real cells did not pass the 10x filtering so is present in the raw_bc_matrix. It would be nice to have run10x allow a customized barcode input.

**Comment by gioelelm** [comment]
You have to use `run`, and add the extra couple of parameters manually.
