### ISSUE TITLE
`run_smartseq2` wants UMIs

### ISSUE THREAD

**Issue by d-j-k** [velocyto-team/velocyto.py#97]
Dear Velocyto Team,

It looks like that version `0.17.10` introduced a bug into `run_smartseq2`.

When running
`velocyto run_smartseq2 -o OUTPUT -m mm10_rmsk.gtf -e 35_rmsk ../bam-star/35/Aligned.sortedByCoord.out.bam gencode.vM18.primary_assembly.annotation.gtf`

I get the following (shortened) error:
```DEBUG - Using logic: SmartSeq2
DEBUG - Cell barcodes will be determined while reading the .bam file
DEBUG - The multi input option
DEBUG - Peeking into /home/ubuntu/data/bam-star/35/
Aligned.sortedByCoord.out.bam
WARNING - Not found cell and umi barcode in entry 0 of the bam file
WARNING - Not found cell and umi barcode in entry 1 of the bam file
WARNING - Not found cell and umi barcode in entry 2 of the bam file
```
This used to be working in `0.17.8`.

Thank you!

**Comment by gioelelm** [comment]
Thank you for reporting.

From the log I see some warnings but not an error. How does the log
continues? Does it throw this kind of warnings without ever stopping?

**Comment by d-j-k** [comment]
Sorry, I forgot to include the last bit of the error log:

```Traceback (most recent call last):
  File "/usr/local/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/run_smartseq2.py", line 71, in run_smartseq2
    samtools_memory=1, dump=dump, verbose=verbose, additional_ca=additional_ca)
  File "/usr/local/lib/python3.6/dist-packages/velocyto/commands/_run.py", line 155, in _run
    exincounter.peek_umi_only(bamfile[0])
  File "/usr/local/lib/python3.6/dist-packages/velocyto/counter.py", line 186, in peek_umi_only
    raise IOError("The bam file does not contain umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")
OSError: The bam file does not contain umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.
```


Everything before that are just warnings for each entry of the bam file. After this output velocyto stops without producing any output.

**Comment by gioelelm** [comment]
I recall this bug was discussed already in a previous issue, but actually I
couldn't find it myself now by quickly skimming through... . Anyways it is
a bug affecting using smartseq2 with only one file, where it expects
multiple files instead if you use 2 or more (e. G. with glob expansion) the
problem is solved. Otherwise use 'run' with the appropriate combination of
parameters, see the docs for further info.

I will try to bugfix in 0.17.11
